//! `effect.lock`: the pins, as a file a human reads and a reviewer diffs.
//!
//! A pin is trust on first use, so the file has to be legible to whoever is
//! asked to approve it. That is the whole reason it is TOML grouped by domain
//! rather than a serialisation of the memo table: a reviewer wants to see
//! every pin one fetcher took, next to each other, with the person and the
//! moment attached.
//!
//! # Byte stability
//!
//! Saving the same rows twice produces the same bytes, and loading then saving
//! is a fixed point. Without that a lock file re-serialises into spurious diff
//! noise, and reviewers stop reading the diff, which defeats the file. It is
//! achieved by rendering rather than serialising: domains and keys come from
//! `BTreeMap`s, and the fields inside a row are written in a fixed order. Hex
//! is lowercase and fixed-width, so `BTreeMap` order over the raw hashes is
//! also alphabetical order over the hex, and the file sorts the way it looks
//! like it sorts.
//!
//! The reader is the `toml` crate; the writer is by hand for exactly the
//! reason above. A serialiser is free to reorder, re-wrap or re-quote, and
//! that freedom is the thing being removed.

use crate::error::{KernelError, Result};
use crate::hash::Hash;
use crate::id::{Domain, Key, ObjId};
use crate::table::{Entry, MemoTable, Policy, Provenance, RefreshPolicy};
use std::collections::BTreeMap;
use std::fmt::Write as _;
use std::fs;
use std::path::Path;

/// One pin.
#[derive(Clone, Debug, PartialEq, Eq)]
pub struct LockRow {
    /// Human-facing name for the request, carried because a reviewer cannot
    /// read a key. Optional: the kernel never depends on it, and it is
    /// deliberately not hashed, so renaming a pin is not a re-pin.
    pub label: Option<String>,
    pub key: Key,
    pub output: ObjId,
    /// Which canonical encoding minted the key. Redundant with the domain,
    /// which already covers it, and written anyway so that a file whose
    /// domains nobody can re-derive is still self-describing.
    pub canon_version: String,
    /// RFC 3339, supplied by the caller. See [`crate::dispatch::PerformCtx`]
    /// for why the kernel reads no clock.
    pub performed_at: String,
    /// Who took responsibility.
    pub by: String,
    /// Optional signature over the row. Nothing verifies it yet; the field
    /// exists so that adding verification is not a format change.
    pub sig: Option<Vec<u8>>,
}

/// The parsed contents of an `effect.lock`.
#[derive(Clone, Debug, Default, PartialEq, Eq)]
pub struct EffectLock {
    rows: BTreeMap<Domain, BTreeMap<Key, LockRow>>,
}

const HEADER: &str = "\
# effect.lock -- pins recorded on first use.
#
# Grouped by effect domain, rows sorted by key. Regenerated byte-for-byte, so
# any diff here is a real change to what this build trusts.
";

impl EffectLock {
    #[must_use]
    pub fn new() -> Self {
        Self::default()
    }

    #[must_use]
    pub fn get(&self, domain: Domain, key: Key) -> Option<&LockRow> {
        self.rows.get(&domain).and_then(|keys| keys.get(&key))
    }

    /// Insert or replace a pin, returning what it displaced.
    pub fn insert(&mut self, domain: Domain, row: LockRow) -> Option<LockRow> {
        self.rows.entry(domain).or_default().insert(row.key, row)
    }

    pub fn remove(&mut self, domain: Domain, key: Key) -> Option<LockRow> {
        let keys = self.rows.get_mut(&domain)?;
        let removed = keys.remove(&key);
        if keys.is_empty() {
            self.rows.remove(&domain);
        }
        removed
    }

    #[must_use]
    pub fn len(&self) -> usize {
        self.rows.values().map(BTreeMap::len).sum()
    }

    #[must_use]
    pub fn is_empty(&self) -> bool {
        self.rows.values().all(BTreeMap::is_empty)
    }

    /// Every pin, in file order.
    pub fn iter(&self) -> impl Iterator<Item = (Domain, &LockRow)> {
        self.rows
            .iter()
            .flat_map(|(domain, keys)| keys.values().map(move |row| (*domain, row)))
    }

    /// Union two lock files.
    ///
    /// Two files pinning one key to two outputs is refused rather than
    /// resolved. Whichever side lost would be somebody's reviewed answer being
    /// dropped without anybody being told, and the fix (decide which pin is
    /// right) needs a human who knows what the effect does. Rows agreeing on
    /// the output keep ours, so merging is idempotent and does not churn
    /// timestamps.
    pub fn merge(&mut self, other: &Self) -> Result<()> {
        for (domain, row) in other.iter() {
            match self.get(domain, row.key) {
                Some(ours) if ours.output != row.output => {
                    return Err(KernelError::conflict(
                        domain,
                        row.key,
                        ours.output,
                        row.output,
                    ));
                }
                Some(_) => {}
                None => {
                    self.insert(domain, row.clone());
                }
            }
        }
        Ok(())
    }

    /// Load pins into a memo table, so a fresh process hits instead of
    /// re-performing.
    ///
    /// Replayed rows come back as `Pinned(Manual)`. The file does not record a
    /// refresh policy, and `Manual` is the only choice that cannot invent
    /// permission the file never granted: it is also harmless, because refresh
    /// is decided by the policy at the call site, not by the one stored on the
    /// row.
    pub fn replay_into(&self, table: &mut MemoTable) {
        for (domain, row) in self.iter() {
            table.insert(
                domain,
                row.key,
                Entry {
                    output: row.output,
                    policy: Policy::Pinned(RefreshPolicy::Manual),
                    provenance: Provenance::Blessed {
                        who: row.by.clone(),
                        when: row.performed_at.clone(),
                        sig: row.sig.clone(),
                    },
                },
            );
        }
    }

    /// Render to the exact bytes [`save`] writes.
    ///
    /// [`save`]: EffectLock::save
    #[must_use]
    pub fn render(&self) -> String {
        let mut out = String::from(HEADER);
        for (domain, keys) in &self.rows {
            for row in keys.values() {
                out.push('\n');
                // A bare key: hex is `[0-9a-f]`, which TOML accepts unquoted.
                let _ = writeln!(out, "[[{domain}]]");
                if let Some(label) = &row.label {
                    let _ = writeln!(out, "label = {}", quote(label));
                }
                let _ = writeln!(out, "key = \"{}\"", row.key);
                let _ = writeln!(out, "output = \"{}\"", row.output);
                let _ = writeln!(out, "canon_version = {}", quote(&row.canon_version));
                let _ = writeln!(out, "performed_at = {}", quote(&row.performed_at));
                let _ = writeln!(out, "by = {}", quote(&row.by));
                if let Some(sig) = &row.sig {
                    let _ = writeln!(out, "sig = \"{}\"", to_hex(sig));
                }
            }
        }
        out
    }

    /// Parse what [`render`] produced.
    ///
    /// [`render`]: EffectLock::render
    pub fn parse(text: &str) -> Result<Self> {
        let document: toml::Value =
            toml::from_str(text).map_err(|error| KernelError::lock(error.to_string()))?;
        let toml::Value::Table(table) = document else {
            return Err(KernelError::lock("top level is not a table"));
        };

        let mut lock = Self::new();
        for (domain_hex, value) in table {
            let domain = Domain::from_hash(
                Hash::from_hex(&domain_hex)
                    .map_err(|source| KernelError::hex(format!("domain {domain_hex}"), source))?,
            );
            let toml::Value::Array(entries) = value else {
                return Err(KernelError::lock(format!(
                    "domain {domain_hex} is not an array of tables"
                )));
            };
            for entry in entries {
                let toml::Value::Table(fields) = entry else {
                    return Err(KernelError::lock(format!(
                        "domain {domain_hex} contains a non-table row"
                    )));
                };
                let row = parse_row(&domain_hex, &fields)?;
                if let Some(previous) = lock.insert(domain, row.clone())
                    && previous.output != row.output
                {
                    return Err(KernelError::conflict(
                        domain,
                        row.key,
                        previous.output,
                        row.output,
                    ));
                }
            }
        }
        Ok(lock)
    }

    /// Read a lock file. A missing file is an empty lock, not an error: the
    /// first run of a project has no pins and must not need a placeholder.
    pub fn load(path: impl AsRef<Path>) -> Result<Self> {
        let path = path.as_ref();
        match fs::read_to_string(path) {
            Ok(text) => Self::parse(&text),
            Err(source) if source.kind() == std::io::ErrorKind::NotFound => Ok(Self::new()),
            Err(source) => Err(KernelError::io(
                format!("reading {}", path.display()),
                source,
            )),
        }
    }

    pub fn save(&self, path: impl AsRef<Path>) -> Result<()> {
        let path = path.as_ref();
        fs::write(path, self.render())
            .map_err(|source| KernelError::io(format!("writing {}", path.display()), source))
    }
}

fn parse_row(domain_hex: &str, fields: &toml::Table) -> Result<LockRow> {
    let required_hash = |name: &str| -> Result<Hash> {
        let text = string_field(fields, name)?.ok_or_else(|| {
            KernelError::lock(format!("domain {domain_hex}: row is missing `{name}`"))
        })?;
        Hash::from_hex(text)
            .map_err(|source| KernelError::hex(format!("{name} in {domain_hex}"), source))
    };

    let required_text = |name: &str| -> Result<String> {
        Ok(string_field(fields, name)?
            .ok_or_else(|| {
                KernelError::lock(format!("domain {domain_hex}: row is missing `{name}`"))
            })?
            .to_owned())
    };

    Ok(LockRow {
        label: string_field(fields, "label")?.map(str::to_owned),
        key: Key::from_hash(required_hash("key")?),
        output: ObjId::from_hash(required_hash("output")?),
        canon_version: required_text("canon_version")?,
        performed_at: required_text("performed_at")?,
        by: required_text("by")?,
        sig: string_field(fields, "sig")?.map(from_hex).transpose()?,
    })
}

fn string_field<'a>(fields: &'a toml::Table, name: &str) -> Result<Option<&'a str>> {
    match fields.get(name) {
        None => Ok(None),
        Some(toml::Value::String(text)) => Ok(Some(text)),
        Some(other) => Err(KernelError::lock(format!(
            "`{name}` should be a string, got {}",
            other.type_str()
        ))),
    }
}

fn to_hex(bytes: &[u8]) -> String {
    let mut out = String::with_capacity(bytes.len() * 2);
    for byte in bytes {
        let _ = write!(out, "{byte:02x}");
    }
    out
}

fn from_hex(text: &str) -> Result<Vec<u8>> {
    if !text.len().is_multiple_of(2) {
        return Err(KernelError::lock(format!(
            "`sig` has an odd number of hex digits ({})",
            text.len()
        )));
    }
    text.as_bytes()
        .chunks_exact(2)
        .map(|pair| {
            let digits = str::from_utf8(pair)
                .map_err(|_| KernelError::lock("`sig` is not hex".to_owned()))?;
            u8::from_str_radix(digits, 16)
                .map_err(|error| KernelError::lock(format!("`sig` is not hex: {error}")))
        })
        .collect()
}

/// A TOML basic string. Escapes the two structural characters plus everything
/// the spec forbids raw, so a label containing a quote or a newline round-trips
/// instead of producing a file that no longer parses.
fn quote(text: &str) -> String {
    let mut out = String::with_capacity(text.len() + 2);
    out.push('"');
    for character in text.chars() {
        match character {
            '"' => out.push_str("\\\""),
            '\\' => out.push_str("\\\\"),
            '\n' => out.push_str("\\n"),
            '\r' => out.push_str("\\r"),
            '\t' => out.push_str("\\t"),
            '\u{8}' => out.push_str("\\b"),
            '\u{c}' => out.push_str("\\f"),
            control if control < ' ' || control == '\u{7f}' => {
                let _ = write!(out, "\\u{:04X}", control as u32);
            }
            other => out.push(other),
        }
    }
    out.push('"');
    out
}

#[cfg(test)]
mod tests {
    use super::*;
    use crate::canon;

    fn domain(op: &str) -> Domain {
        Domain::mint("test-effect", op)
    }

    fn row(domain: Domain, req: &[u8], output: &[u8]) -> LockRow {
        LockRow {
            label: Some(format!("pin for {}", String::from_utf8_lossy(req))),
            key: Key::mint(domain, req),
            output: ObjId::of(output),
            canon_version: canon::VERSION.to_owned(),
            performed_at: "2026-08-02T12:00:00Z".to_owned(),
            by: "tester".to_owned(),
            sig: None,
        }
    }

    fn sample() -> EffectLock {
        let mut lock = EffectLock::new();
        // Inserted out of order on purpose: the file must not remember this.
        lock.insert(domain("zeta"), row(domain("zeta"), b"b", b"B"));
        lock.insert(domain("alpha"), row(domain("alpha"), b"a", b"A"));
        lock.insert(domain("zeta"), row(domain("zeta"), b"a", b"A"));
        lock
    }

    #[test]
    fn render_parse_render_is_a_fixed_point() -> Result<()> {
        let once = sample().render();
        let twice = EffectLock::parse(&once)?.render();
        assert_eq!(once, twice);
        Ok(())
    }

    #[test]
    fn parsing_recovers_the_same_rows() -> Result<()> {
        let original = sample();
        assert_eq!(EffectLock::parse(&original.render())?, original);
        Ok(())
    }

    #[test]
    fn insertion_order_does_not_reach_the_file() -> Result<()> {
        let mut reversed = EffectLock::new();
        reversed.insert(domain("zeta"), row(domain("zeta"), b"a", b"A"));
        reversed.insert(domain("alpha"), row(domain("alpha"), b"a", b"A"));
        reversed.insert(domain("zeta"), row(domain("zeta"), b"b", b"B"));
        assert_eq!(reversed.render(), sample().render());
        Ok(())
    }

    /// Domain headers ascend, and within one domain the keys ascend. Read off
    /// the rendered text rather than the map, since the file is the artefact
    /// whose order matters.
    #[test]
    fn the_file_is_domain_major_and_sorted() {
        let text = sample().render();
        let mut headers: Vec<&str> = Vec::new();
        let mut groups: Vec<Vec<&str>> = Vec::new();
        for line in text.lines() {
            if let Some(rest) = line.strip_prefix("[[")
                && let Some(hex) = rest.strip_suffix("]]")
            {
                if headers.last() != Some(&hex) {
                    headers.push(hex);
                    groups.push(Vec::new());
                }
            } else if let Some(rest) = line.strip_prefix("key = \"")
                && let Some(hex) = rest.strip_suffix('"')
                && let Some(group) = groups.last_mut()
            {
                group.push(hex);
            }
        }
        assert_eq!(headers.len(), 2, "two domains in the sample");
        assert_eq!(groups.iter().map(Vec::len).sum::<usize>(), 3);
        assert!(headers.is_sorted(), "domain headers out of order");
        for group in &groups {
            assert!(group.is_sorted(), "keys out of order within a domain");
        }
    }

    #[test]
    fn labels_with_awkward_characters_round_trip() -> Result<()> {
        let mut lock = EffectLock::new();
        let mut awkward = row(domain("a"), b"r", b"o");
        awkward.label = Some("say \"hi\"\n\tand \\ that\u{1}".to_owned());
        lock.insert(domain("a"), awkward);
        assert_eq!(EffectLock::parse(&lock.render())?, lock);
        Ok(())
    }

    #[test]
    fn signatures_round_trip_as_hex() -> Result<()> {
        let mut lock = EffectLock::new();
        let mut signed = row(domain("a"), b"r", b"o");
        signed.sig = Some(vec![0x00, 0xde, 0xad, 0xff]);
        lock.insert(domain("a"), signed);
        assert_eq!(EffectLock::parse(&lock.render())?, lock);
        Ok(())
    }

    #[test]
    fn an_empty_lock_renders_to_just_the_header() -> Result<()> {
        let empty = EffectLock::new();
        assert_eq!(empty.render(), HEADER);
        assert_eq!(EffectLock::parse(&empty.render())?, empty);
        Ok(())
    }

    #[test]
    fn merge_is_a_union() -> Result<()> {
        let mut left = EffectLock::new();
        left.insert(domain("a"), row(domain("a"), b"1", b"A"));
        let mut right = EffectLock::new();
        right.insert(domain("b"), row(domain("b"), b"2", b"B"));
        left.merge(&right)?;
        assert_eq!(left.len(), 2);
        // Idempotent: merging again changes nothing.
        let once = left.render();
        left.merge(&right)?;
        assert_eq!(left.render(), once);
        Ok(())
    }

    #[test]
    fn merge_refuses_to_pick_a_side() {
        let mut left = EffectLock::new();
        left.insert(domain("a"), row(domain("a"), b"1", b"A"));
        let mut right = EffectLock::new();
        right.insert(domain("a"), row(domain("a"), b"1", b"DIFFERENT"));
        let refused = left.merge(&right);
        assert!(
            matches!(refused, Err(KernelError::LockConflict(_))),
            "expected a conflict, got {refused:?}"
        );
        // Both outputs are named, so the reader can go and look at each.
        if let Err(KernelError::LockConflict(detail)) = &refused {
            assert_eq!(detail.ours, ObjId::of(b"A"));
            assert_eq!(detail.theirs, ObjId::of(b"DIFFERENT"));
        }
    }

    #[test]
    fn a_missing_file_loads_as_an_empty_lock() -> Result<()> {
        let path =
            std::env::temp_dir().join(format!("ix-kernel-absent-{}.lock", std::process::id()));
        drop(fs::remove_file(&path));
        assert_eq!(EffectLock::load(&path)?, EffectLock::new());
        Ok(())
    }

    #[test]
    fn saving_and_loading_preserves_the_bytes() -> Result<()> {
        let path = std::env::temp_dir().join(format!("ix-kernel-save-{}.lock", std::process::id()));
        let lock = sample();
        lock.save(&path)?;
        let reloaded = EffectLock::load(&path)?;
        let on_disk =
            fs::read_to_string(&path).map_err(|source| KernelError::io("reading back", source))?;
        drop(fs::remove_file(&path));
        assert_eq!(reloaded, lock);
        assert_eq!(on_disk, lock.render());
        Ok(())
    }

    #[test]
    fn malformed_files_are_refused_rather_than_guessed_at() {
        assert!(EffectLock::parse("[[not-hex]]\nkey = \"x\"\n").is_err());
        let good_domain = domain("a").to_string();
        // Missing `output`.
        let missing = format!(
            "[[{good_domain}]]\nkey = \"{}\"\ncanon_version = \"canon-v1\"\n\
             performed_at = \"t\"\nby = \"me\"\n",
            Key::mint(domain("a"), b"r")
        );
        assert!(EffectLock::parse(&missing).is_err());
        // `key` is not a string.
        let wrong_type = format!("[[{good_domain}]]\nkey = 3\n");
        assert!(EffectLock::parse(&wrong_type).is_err());
    }

    #[test]
    fn replaying_pins_fills_the_table() {
        let lock = sample();
        let mut table = MemoTable::new();
        lock.replay_into(&mut table);
        assert_eq!(table.len(), lock.len());
        for (domain, row) in lock.iter() {
            let found = table.get(domain, row.key);
            assert_eq!(found.map(|entry| entry.output), Some(row.output));
            assert!(matches!(
                found.map(|entry| &entry.policy),
                Some(Policy::Pinned(RefreshPolicy::Manual))
            ));
        }
    }
}
