"""Type stubs for the native PyO3 module.

Hand-maintained to mirror crates/ix/sdk-py/src/. Keep in sync when adding or
changing PyO3 bindings — pyright uses this file to type-check the wrapper
layer in __init__.py.

Methods that the wrapper does not call are intentionally omitted to keep the
stub small. Add them when needed.
"""
from __future__ import annotations

import enum
from collections.abc import AsyncIterator

__version__: str

# ── Errors ──────────────────────────────────────────────────────────

class IxError(RuntimeError): ...
class IxAuthError(IxError): ...
class IxNotFoundError(IxError): ...
class IxValidationError(IxError): ...
class IxRateLimitError(IxError): ...
class IxConflictError(IxError): ...
class IxCapacityError(IxError): ...
class IxPaymentError(IxError): ...
class IxUnavailableError(IxError): ...
class IxConnectionError(IxError): ...
class IxTimeoutError(IxError): ...

# ── Enums ───────────────────────────────────────────────────────────

class BranchStatus(enum.Enum):
    RUNNING = ...
    STOPPED = ...
    FAILED = ...

class RuntimeState(enum.Enum):
    UNKNOWN = ...
    RUNNING = ...
    PAUSE_REQUESTED = ...
    PAUSED = ...
    CAPTURE_REQUESTED = ...
    CAPTURED = ...
    RUNNING_AND_CAPTURING = ...
    SHUTDOWN_REQUESTED = ...
    SHUTDOWN = ...
    FAILED = ...

class RuntimeHealthState(enum.Enum):
    HEALTHY = ...
    DEGRADED = ...
    FAILED = ...

class RuntimeControlIssue(enum.Enum):
    GUEST_RPC_TRANSPORT_UNAVAILABLE = ...

class RuntimeNetworkIssue(enum.Enum):
    VSOCK_TRANSPORT_RESET_REPLAY_FAILED = ...
    VSOCK_ACTIVATION_FAILED = ...
    NET_ACTIVATION_FAILED = ...

class RuntimeVirtioMemIssue(enum.Enum):
    TRANSPORT_UNAVAILABLE = ...

class RuntimeCaptureIssue(enum.Enum):
    REQUEST_FAILED = ...

class RuntimeVcpuIssueKind(enum.Enum):
    VCPU_RUN = ...
    INTERRUPTED_SPIN = ...

class StartupMode(enum.Enum):
    FULL_BOOT = ...
    GOLDEN_RESTORE = ...
    FORK_RESTORE = ...

class MigrationPhase(enum.Enum):
    PLANNING = ...
    CAPTURING_SOURCE = ...
    SOURCE_CAPTURED = ...
    PREPARING_TARGET = ...
    RESTORING_TARGET = ...
    TARGET_READY = ...
    DRAINING_SOURCE = ...
    CUTTING_OVER = ...
    VM_RESUMED = ...
    COMMITTED = ...
    CLEANING_UP = ...
    COMPLETED = ...
    FAILED = ...
    CANCELLED = ...

# ── Data classes ────────────────────────────────────────────────────

class RegionInfo:
    @property
    def id(self) -> str: ...
    @property
    def slug(self) -> str: ...
    @property
    def display_name(self) -> str: ...
    @property
    def status(self) -> str: ...

class BranchInfo:
    @property
    def id(self) -> str: ...
    @property
    def name(self) -> str: ...
    @property
    def image(self) -> str: ...
    @property
    def status(self) -> BranchStatus: ...
    @property
    def ipv6(self) -> str: ...
    @property
    def ipv4(self) -> str | None: ...
    @property
    def subdomain(self) -> str | None: ...
    @property
    def ephemeral(self) -> bool: ...
    @property
    def started_at(self) -> int | None: ...
    @property
    def stopped_at(self) -> int | None: ...
    @property
    def failure_reason(self) -> str | None: ...
    @property
    def created_at(self) -> int: ...
    @property
    def updated_at(self) -> int: ...
    @property
    def region(self) -> RegionInfo | None: ...
    @property
    def owner_id(self) -> str: ...

class ExecResult:
    def __init__(self, exit_code: int, stdout: str, stderr: str) -> None: ...
    @property
    def exit_code(self) -> int: ...
    @property
    def stdout(self) -> str: ...
    @property
    def stderr(self) -> str: ...

class ExecChunk:
    @property
    def stdout(self) -> bytes: ...
    @property
    def stderr(self) -> bytes: ...

class FsReadResult:
    @property
    def path(self) -> str: ...
    @property
    def text(self) -> str: ...

class FsWriteResult:
    @property
    def bytes_written(self) -> int: ...

class FsEntry:
    def __init__(
        self,
        name: str,
        size: int,
        mode: int,
        mtime_ns: int,
        is_dir: bool,
    ) -> None: ...
    @property
    def name(self) -> str: ...
    @property
    def size(self) -> int: ...
    @property
    def mode(self) -> int: ...
    @property
    def mtime_ns(self) -> int: ...
    @property
    def is_dir(self) -> bool: ...

class LogEntry:
    @property
    def timestamp(self) -> int: ...
    @property
    def vm_id(self) -> str: ...
    @property
    def stream(self) -> str: ...
    @property
    def message(self) -> str: ...

class Secret:
    @property
    def id(self) -> str: ...
    @property
    def name(self) -> str: ...
    @property
    def created_at(self) -> int: ...
    @property
    def updated_at(self) -> int: ...

class MetricsInfo:
    @property
    def vm_id(self) -> str: ...
    @property
    def cpu_percent(self) -> float: ...
    @property
    def memory_percent(self) -> float: ...
    @property
    def network_rx_bytes(self) -> int: ...
    @property
    def network_tx_bytes(self) -> int: ...
    @property
    def uptime_secs(self) -> int: ...
    @property
    def collected_at(self) -> int: ...
    @property
    def memory_bytes(self) -> int: ...
    @property
    def memory_limit_bytes(self) -> int: ...
    @property
    def io_read_bytes(self) -> int: ...
    @property
    def io_write_bytes(self) -> int: ...

class StartupStagesInfo:
    @property
    def rootfs_prepare_ms(self) -> int | None: ...
    @property
    def vmfs_start_ms(self) -> int | None: ...
    @property
    def boot_ms(self) -> int | None: ...
    @property
    def golden_template_ms(self) -> int | None: ...
    @property
    def create_tap_ms(self) -> int | None: ...
    @property
    def spawn_vmm_ms(self) -> int | None: ...
    @property
    def vsock_wait_ms(self) -> int | None: ...
    @property
    def guest_ready_ms(self) -> int | None: ...

class StartupInfo:
    @property
    def mode(self) -> StartupMode: ...
    @property
    def total_ms(self) -> int: ...
    @property
    def stages(self) -> StartupStagesInfo | None: ...

class RuntimeStatusInfo:
    @property
    def state(self) -> RuntimeState: ...
    @property
    def memory_mib(self) -> int | None: ...
    @property
    def guest_rpc_transport_ready(self) -> bool | None: ...
    @property
    def virtio_mem_transport_ready(self) -> bool | None: ...
    @property
    def health(self) -> RuntimeHealthInfo | None: ...

class RuntimeControlHealthInfo:
    @property
    def guest_rpc_transport(self) -> RuntimeControlIssue | None: ...

class RuntimeNetworkHealthInfo:
    @property
    def vsock_transport_reset_replay(self) -> RuntimeNetworkIssue | None: ...
    @property
    def vsock_activation(self) -> RuntimeNetworkIssue | None: ...
    @property
    def net_activation(self) -> RuntimeNetworkIssue | None: ...

class RuntimeVirtioMemHealthInfo:
    @property
    def transport(self) -> RuntimeVirtioMemIssue | None: ...

class RuntimeCaptureHealthInfo:
    @property
    def request(self) -> RuntimeCaptureIssue | None: ...

class RuntimeVcpuHealthInfo:
    @property
    def vcpu_id(self) -> int: ...
    @property
    def issue(self) -> RuntimeVcpuIssue | None: ...

class RuntimeVcpuIssue:
    @property
    def kind(self) -> RuntimeVcpuIssueKind: ...
    @property
    def errno(self) -> int | None: ...
    @property
    def interrupted_streak(self) -> int | None: ...

class RuntimeHealthInfo:
    @property
    def overall(self) -> RuntimeHealthState: ...
    @property
    def control(self) -> RuntimeControlHealthInfo: ...
    @property
    def network(self) -> RuntimeNetworkHealthInfo: ...
    @property
    def virtio_mem(self) -> RuntimeVirtioMemHealthInfo: ...
    @property
    def capture(self) -> RuntimeCaptureHealthInfo: ...
    @property
    def vcpus(self) -> list[RuntimeVcpuHealthInfo]: ...

class UserInfo:
    @property
    def id(self) -> str: ...
    @property
    def username(self) -> str: ...
    @property
    def display_name(self) -> str | None: ...
    @property
    def email(self) -> str: ...
    @property
    def is_admin(self) -> bool: ...
    @property
    def created_at(self) -> int: ...

class BillingStatus:
    @property
    def balance(self) -> int: ...
    @property
    def monthly_credits(self) -> int: ...
    @property
    def total_granted(self) -> int: ...
    @property
    def total_consumed(self) -> int: ...
    @property
    def plan(self) -> str: ...

class ApiToken:
    @property
    def id(self) -> str: ...
    @property
    def name(self) -> str: ...
    @property
    def token_prefix(self) -> str | None: ...
    @property
    def credits_consumed(self) -> int: ...
    @property
    def created_at(self) -> int: ...

class VolumeInfo:
    @property
    def id(self) -> str: ...
    @property
    def name(self) -> str: ...
    @property
    def vm_id(self) -> str | None: ...
    @property
    def size_bytes(self) -> int: ...
    @property
    def created_at(self) -> int: ...
    @property
    def updated_at(self) -> int: ...

class VolumeSnapshot:
    @property
    def id(self) -> str: ...
    @property
    def volume_id(self) -> str: ...
    @property
    def name(self) -> str: ...
    @property
    def manifest_timestamp(self) -> str: ...
    @property
    def created_at(self) -> int: ...

class PreviewInfo:
    @property
    def id(self) -> str: ...
    @property
    def image_tag(self) -> str: ...
    @property
    def status(self) -> str: ...
    @property
    def created_at(self) -> int: ...
    @property
    def service_count(self) -> int: ...
    @property
    def healthy_count(self) -> int: ...

class PreviewDetail:
    @property
    def id(self) -> str: ...
    @property
    def image_tag(self) -> str: ...
    @property
    def status(self) -> str: ...
    @property
    def created_at(self) -> int: ...

class MigrationStart:
    @property
    def migration_id(self) -> str: ...
    @property
    def phase(self) -> MigrationPhase: ...

class MigrationInfo:
    @property
    def migration_id(self) -> str: ...
    @property
    def vm_id(self) -> str: ...
    @property
    def phase(self) -> MigrationPhase: ...
    @property
    def failure_reason(self) -> str | None: ...
    @property
    def created_at(self) -> int: ...

class TraceSummary:
    @property
    def trace_id(self) -> str: ...
    @property
    def root_span_name(self) -> str | None: ...
    @property
    def service_names(self) -> list[str]: ...
    @property
    def started_at(self) -> int: ...
    @property
    def ended_at(self) -> int: ...
    @property
    def duration_ms(self) -> int: ...
    @property
    def span_count(self) -> int: ...

class ObservabilityLogEntry:
    @property
    def timestamp(self) -> int: ...
    @property
    def trace_id(self) -> str | None: ...
    @property
    def severity_text(self) -> str | None: ...
    @property
    def service_name(self) -> str: ...
    @property
    def body(self) -> str: ...

class VmStatusEvent:
    @property
    def vm_id(self) -> str: ...
    @property
    def status(self) -> BranchStatus: ...
    @property
    def timestamp(self) -> int: ...

class ProgressEvent:
    @property
    def stage(self) -> str: ...
    @property
    def detail(self) -> str: ...
    @property
    def file_count(self) -> int | None: ...
    @property
    def block_count(self) -> int | None: ...
    @property
    def total_bytes(self) -> int | None: ...
    @property
    def from_cache(self) -> bool | None: ...
    @property
    def item_count(self) -> int | None: ...
    @property
    def cached(self) -> bool | None: ...
    @property
    def elapsed_ms(self) -> int | None: ...
    @property
    def vm_id(self) -> str | None: ...

# Runtime status observation has Present/Absent variants — wrapper layer
# doesn't currently use it directly, so the stub stays minimal.
class RuntimeStatusObservationKind(enum.Enum):
    PRESENT = ...
    ABSENT = ...

class RuntimeStatusAbsenceReason(enum.Enum):
    NODE_AGENT_NOT_TRACKED = ...
    VMM_NOT_TRACKED = ...

class Commit:
    """Snapshot of a VM, with metadata fields and branch/fork methods."""
    @property
    def id(self) -> str: ...
    @property
    def branch_id(self) -> str: ...
    @property
    def parent_id(self) -> str | None: ...
    @property
    def status(self) -> str: ...
    @property
    def memory_mib(self) -> int: ...
    @property
    def manifest_key(self) -> str | None: ...
    @property
    def created_at_millis(self) -> int: ...
    async def branch(self, name: str | None = ...) -> Branch: ...
    def branch_with_progress(self, name: str | None = ...) -> StartProgressStream: ...
    async def fork(self, name: str | None = ...) -> Branch: ...

# ── Streams ─────────────────────────────────────────────────────────

class ExecOutputStream(AsyncIterator[ExecChunk]):
    @property
    def exit_code(self) -> int | None: ...
    def __aiter__(self) -> ExecOutputStream: ...
    async def __anext__(self) -> ExecChunk: ...

class LogOutputStream(AsyncIterator[bytes]):
    def __aiter__(self) -> LogOutputStream: ...
    async def __anext__(self) -> bytes: ...

class CreateProgressStream(AsyncIterator["ProgressEvent | Branch"]):
    def __aiter__(self) -> CreateProgressStream: ...
    async def __anext__(self) -> ProgressEvent | Branch: ...

class StartProgressStream(AsyncIterator["ProgressEvent | Branch"]):
    def __aiter__(self) -> StartProgressStream: ...
    async def __anext__(self) -> ProgressEvent | Branch: ...

class ForkProgressStream(AsyncIterator["ProgressEvent | Branch"]):
    def __aiter__(self) -> ForkProgressStream: ...
    async def __anext__(self) -> ProgressEvent | Branch: ...

class VmStatusStream(AsyncIterator[VmStatusEvent]):
    def __aiter__(self) -> VmStatusStream: ...
    async def __anext__(self) -> VmStatusEvent: ...

class StreamConnection:
    async def read(self, n: int) -> bytes: ...
    async def write(self, data: bytes) -> int: ...
    async def close(self) -> None: ...

# ── Handles ─────────────────────────────────────────────────────────

class FsHandle:
    async def read(self, path: str) -> FsReadResult: ...
    async def read_bytes(
        self, path: str, offset: int = ..., length: int | None = ...
    ) -> bytes: ...
    async def read_all_bytes(self, path: str) -> bytes: ...
    async def write(
        self, path: str, text: str, mode: int | None = ...
    ) -> FsWriteResult: ...
    async def write_bytes(
        self, path: str, data: bytes, mode: int | None = ...
    ) -> int: ...
    async def list(self, path: str) -> list[FsEntry]: ...

class SecretsHandle:
    async def set(self, key: str, value: str) -> None: ...
    async def delete(self, key: str) -> None: ...
    async def list(self) -> list[Secret]: ...

# ── Branch ──────────────────────────────────────────────────────────

class Branch:
    @property
    def id(self) -> str: ...
    async def info(self) -> BranchInfo: ...
    async def delete(self) -> None: ...
    async def pause(self) -> Commit: ...
    async def snapshot(self) -> Commit: ...
    async def start(self) -> BranchInfo: ...
    def start_with_progress(self) -> StartProgressStream: ...
    async def restart(self) -> BranchInfo: ...
    async def metrics(self) -> MetricsInfo | None: ...
    async def runtime_status(self) -> RuntimeStatusInfo | None: ...
    async def startup_info(self) -> StartupInfo | None: ...
    async def fork(
        self, snapshot_id: str | None = ..., name: str | None = ...
    ) -> Branch: ...
    def fork_with_progress(
        self, snapshot_id: str, name: str | None = ...
    ) -> ForkProgressStream: ...
    async def migrate(self, target_node_id: str | None = ...) -> MigrationStart: ...
    async def cancel_migration(self, migration_id: str) -> None: ...
    async def migration(self) -> MigrationInfo | None: ...
    async def console_connect(self) -> StreamConnection: ...
    async def port_forward(self, port: int) -> StreamConnection: ...
    def subscribe_status(self) -> VmStatusStream: ...
    async def exec(
        self, command: list[str], working_dir: str | None = ...
    ) -> ExecResult: ...
    async def exec_checked(
        self, command: list[str], working_dir: str | None = ...
    ) -> ExecResult: ...
    def exec_stream(
        self, command: list[str], working_dir: str | None = ...
    ) -> ExecOutputStream: ...
    async def bash(
        self, script: str, working_dir: str | None = ...
    ) -> ExecResult: ...
    async def bash_checked(
        self, script: str, working_dir: str | None = ...
    ) -> ExecResult: ...
    def bash_stream(
        self, script: str, working_dir: str | None = ...
    ) -> ExecOutputStream: ...
    async def spawn(
        self, command: list[str], working_dir: str | None = ...
    ) -> int: ...
    async def log(self) -> list[Commit]: ...
    def fs(self) -> FsHandle: ...
    def secrets(self) -> SecretsHandle: ...
    def logs_stream(self, stream: str = ...) -> LogOutputStream: ...
    async def logs(
        self, stream: str, limit: int, since: int | None = ...
    ) -> list[LogEntry]: ...

# ── Client ──────────────────────────────────────────────────────────

class Client:
    def __init__(
        self, token: str | None = ..., base_url: str | None = ...
    ) -> None: ...
    def base_url(self) -> str: ...
    async def get(self, id: str) -> Branch: ...
    async def get_by_name(self, name: str) -> Branch: ...
    async def build_snapshot_from_oci(
        self,
        image: str,
        region: str,
        name: str | None = ...,
        env: dict[str, str] | None = ...,
        l7_proxy_ports: list[int] | None = ...,
        ipv4: bool = ...,
    ) -> Commit: ...
    def create_with_progress(
        self,
        image: str,
        region: str,
        name: str | None = ...,
        env: dict[str, str] | None = ...,
        l7_proxy_ports: list[int] | None = ...,
        ipv4: bool = ...,
    ) -> CreateProgressStream: ...
    async def snapshot(self, name: str) -> BranchInfo: ...
    async def switch_system(
        self, name: str, target: str, build_on: str | None = ...
    ) -> BranchInfo: ...
    async def branches(self) -> list[BranchInfo]: ...
    async def regions(self) -> list[RegionInfo]: ...
    async def me(self) -> UserInfo | None: ...
    async def billing_status(self) -> BillingStatus: ...
    async def list_api_tokens(self) -> list[ApiToken]: ...
    async def revoke_api_token(self, token_id: str) -> None: ...
    async def get_volume(self, volume_id: str) -> VolumeInfo: ...
    async def list_volumes(self) -> list[VolumeInfo]: ...
    async def list_volume_snapshots(self, volume_id: str) -> list[VolumeSnapshot]: ...
    async def create_preview(
        self, image_tag: str | None = ..., fork_volumes: bool | None = ...
    ) -> PreviewDetail: ...
    async def list_previews(self) -> list[PreviewInfo]: ...
    async def stop_preview(self, preview_id: str) -> None: ...
    async def get_preview(self, preview_id: str) -> PreviewDetail: ...
    async def promote_preview(self, preview_id: str) -> PreviewDetail: ...
    async def query_logs(
        self,
        limit: int,
        trace_id: str | None = ...,
        request_id: str | None = ...,
        since: int | None = ...,
        until: int | None = ...,
    ) -> list[ObservabilityLogEntry]: ...
    async def search_traces(
        self,
        limit: int,
        trace_id: str | None = ...,
        request_id: str | None = ...,
        since: int | None = ...,
        until: int | None = ...,
    ) -> list[TraceSummary]: ...
