"""Type stubs for the native PyO3 module.

Hand-maintained to mirror packages/tui-py/src/. Keep in sync when adding or
changing PyO3 bindings — pyright/mypy use this file to type-check callers.
Every I/O method returns a native asyncio-awaitable coroutine produced by
pyo3-async-runtimes; awaiting it drives the underlying tokio future. Only the
pure accessors stay synchronous.
"""

from __future__ import annotations

from collections.abc import Awaitable
from typing import TypeAlias

import numpy as np
from numpy.typing import NDArray

__version__: str

#: A cell color: `None` is the terminal default, an `int` is a palette index,
#: an `(r, g, b)` tuple is truecolor.
_Color: TypeAlias = int | tuple[int, int, int] | None

class StyledCell:
    """A single terminal cell: character plus VT100 styling."""

    @property
    def char(self) -> str: ...
    @property
    def fg(self) -> _Color: ...
    @property
    def bg(self) -> _Color: ...
    @property
    def bold(self) -> bool: ...
    @property
    def italic(self) -> bool: ...
    @property
    def underline(self) -> bool: ...
    @property
    def inverse(self) -> bool: ...
    def __repr__(self) -> str: ...

class TuiInstance:
    """A handle to a single spawned TUI process. Spawning is the constructor."""

    def __init__(
        self,
        command: str,
        args: list[str] | None = ...,
        rows: int | None = ...,
        cols: int | None = ...,
        scrollback_lines: int | None = ...,
    ) -> None: ...
    @staticmethod
    def list_all() -> list[TuiInstance]: ...
    @property
    def id(self) -> str: ...
    @property
    def command(self) -> str: ...
    @property
    def args(self) -> list[str]: ...
    @property
    def cols(self) -> int: ...
    @property
    def rows(self) -> int: ...
    @property
    def scrollback_limit(self) -> int: ...

    # --- pure accessors (synchronous) -------------------------------------
    def is_alive(self) -> bool: ...
    def exit_code(self) -> int | None: ...

    # --- async I/O (native pyo3-async-runtimes coroutines) ----------------
    def write_async(self, data: str) -> Awaitable[None]: ...
    def read_viewport_async(self) -> Awaitable[list[str]]: ...
    def read_scrollback_async(self) -> Awaitable[list[str]]: ...
    def read_full_async(self) -> Awaitable[tuple[list[str], list[str]]]: ...
    def read_blocking_async(self, timeout_ms: int) -> Awaitable[list[str]]: ...
    def read_chars_array_async(self) -> Awaitable[NDArray[np.uint32]]: ...
    def read_styled_cells_async(self) -> Awaitable[list[list[StyledCell]]]: ...
    def resize_async(self, rows: int, cols: int) -> Awaitable[None]: ...
    def kill_async(self) -> Awaitable[None]: ...
    def wait_async(self) -> Awaitable[int | None]: ...
    def close_async(self) -> Awaitable[None]: ...
    def __repr__(self) -> str: ...

class Dashboard:
    """Handle to a running Loro-backed web dashboard. Stop with `await stop()`."""

    @property
    def addr(self) -> str: ...
    @property
    def url(self) -> str: ...
    def stop(self) -> Awaitable[None]: ...
    def __repr__(self) -> str: ...

def serve(host: str = ..., port: int = ..., poll_ms: int = ...) -> Awaitable[Dashboard]: ...
