{
  description = "Index developer tools, modules, and fleet examples";

  # Keep the repo cache available for repo-owned tools that CI has already built.
  # `cache.ix.dev` is the ix public cache (ncps fronting the `ix-public` atticd
  # cache); it serves repo-owned artifacts and falls through to cache.nixos.org
  # for generic nixpkgs paths, so a single substituter covers both. Everything
  # there is signed `ix-workspace:` (atticd signs served narinfos server-side),
  # so that one trusted key verifies both ix's builds and index's published
  # packages (pushed by cache-push.yml).
  nixConfig = {
    extra-substituters = ["https://cache.ix.dev"];
    extra-trusted-public-keys = [
      "ix-workspace:JuAaeOPfR3GL3nUICpEz/88/+S3BzGF3L6bPYFy0GwI="
    ];
    # The rust workspace units default to `contentAddressed = true`
    # (lib/rust/cargo-unit.nix), so evaluating `.#checks` / `.#packages`
    # resolves floating content-addressed derivations. Without this feature the
    # evaluator aborts with "experimental Nix feature 'ca-derivations' is
    # disabled". Declared here so any eval against this flake (CI's
    # `accept-flake-config` runs, a local `nix flake check`, `nix build
    # .#checks.<sys>.<name>`) picks it up from one source of truth.
    extra-experimental-features = ["ca-derivations"];
  };

  inputs = {
    nixpkgs.url = "github:NixOS/nixpkgs/nixos-unstable";

    # Relative-path ("subflake") inputs for the repo's independent data
    # subtrees. With lazy source trees a flake that reaches its whole tree via
    # `self` gives every package the entire repo as its source identity: any
    # file change anywhere re-hashes and re-copies the full tree per eval and
    # invalidates every dependent. Declaring each pure-data subtree as its own
    # `flake = false` path input scopes a consumer's source to just the subtree
    # it reads, so an edit under `packages/site/` no longer perturbs a
    # `packages/agent/skills` package's drvPath. nix and nox both resolve
    # these as lock nodes
    # `{ type = "path"; path = "./<dir>"; parent = []; }` against the parent
    # tree, with no separate fetch. Nix-code roots the flake itself imports
    # (`modules`, `packages`) stay ordinary relative paths: they are
    # import-time, not source identity. See ENG-2362.
    skills = {
      url = "path:./packages/agent/skills";
      flake = false;
    };
    examples = {
      url = "path:./examples";
      flake = false;
    };
    tests = {
      url = "path:./tests";
      flake = false;
    };
    bench-filesystem = {
      url = "path:./packages/indexbench/filesystem";
      flake = false;
    };
    site = {
      url = "path:./packages/site";
      flake = false;
    };

    rust-overlay = {
      url = "github:oxalica/rust-overlay";
      inputs.nixpkgs.follows = "nixpkgs";
    };

    # Pinned evaluation context for the prebuilt public-SDK `ix-sdk-wire` rlib
    # (packages/sdk/rust/build.nix). The artifact's manifest records the store
    # path of the toolchain it was compiled with, and that path folds the whole
    # nixpkgs + rust-overlay evaluation, so it is only reproducible from the
    # exact revs the artifact was published against. Pinned BY REV: a blanket
    # `nix flake update` re-locks the same rev, so the hourly flake bump can
    # never move this context out from under the artifact (#2131). A
    # republication of the rlib bumps these two revs together with
    # packages/sdk/rust/pins.json.
    sdk-prebuilt-nixpkgs = {
      url = "github:NixOS/nixpkgs/a799d3e3886da994fa307f817a6bc705ae538eeb";
      flake = false;
    };
    sdk-prebuilt-rust-overlay = {
      url = "github:oxalica/rust-overlay/107c334f141854f563f8adf1db781dc453d92639";
      flake = false;
    };

    # Home Manager wired in via its NixOS module for per-tool XDG-shaped
    # config (Nushell, atuin, zoxide, starship, ...). Tracks master so it
    # stays on the same release as nixpkgs-unstable; the per-release
    # branches lag (no release-26.05 exists at the time of writing) and
    # the mismatch fires a noisy `enableNixpkgsReleaseCheck` warning on
    # every eval.
    home-manager = {
      url = "github:nix-community/home-manager";
      inputs.nixpkgs.follows = "nixpkgs";
    };

    # Upstream rust-lang/rust-clippy, patched in-repo with the restriction lints
    # tuned for LLM-assisted codebases (packages/llm-clippy/patches). Pinned BY
    # REV, not a floating branch: clippy-driver links rustc_private and must match
    # the repo's pinned nightly (root rust-toolchain.toml) exactly, or every
    # per-unit clippy gate fails with E0514 "compiled by an incompatible version
    # of rustc". Never free-float under a blanket `nix flake update`.
    #
    # The repo nightly (2026-05-27) sits between
    # upstream clippy's autogenerated sync points (05-13 -> 05-28), so no
    # upstream rev compiles against it as-is. The series' first patch bridges
    # that gap (toolchain file + rustc_private adaptations). Bump this rev only
    # inside the same change that bumps the repo rust toolchain; if the new
    # nightly matches an upstream sync commit, drop the bridge patch, otherwise
    # regenerate it. Then `nix run .#rebase-patches -- clippy` for the rest.
    clippy-src = {
      url = "github:rust-lang/rust-clippy/512551c839fc711fc925c8a862a9abd4bde0812f";
      flake = false;
    };

    # Upstream openai/codex, patched in-repo (packages/agent/codex/patches).
    # Pinned BY REV: the package vendors its Cargo dependencies behind a fixed
    # `cargoHash` (packages/agent/codex/default.nix), so the base and the hash
    # must move together. A branch-loose URL here lets any blanket `nix flake
    # update` -- ours or a downstream consumer's (ix locks this input
    # transitively) -- float the base past the hash, which broke every ix prod
    # deploy for 13h on 2026-07-07. Bump this rev deliberately, then
    # `nix run .#rebase-patches -- codex` and regenerate the cargoHash in the
    # same change (fork-packages.nix marks it `autoUpdate = false`, so the
    # scheduled fork-sync leaves it alone).
    codex-src = {
      url = "github:openai/codex/be33f80bc65159c094ecd06bf155afa3061ce23d";
      flake = false;
    };

    # Upstream NixOS/nix, patched in-repo (packages/nix/nix/patches). Pinned BY
    # REV at tag 2.34.7, the version the hydra daemon runs (`nix store info` ->
    # `Version: 2.34.7`): nix is our daemon toolchain, so the patched package
    # must stay a protocol-compatible drop-in for the running daemon. The base
    # moves DELIBERATELY, never under a routine `nix flake update`
    # (fork-packages.nix marks it `autoUpdate = false`, so the scheduled
    # fork-sync leaves it alone): bump this rev only when we intend to move the
    # daemon version too, then `nix run .#rebase-patches -- nix` to regenerate
    # the series on the new base.
    nix-src = {
      url = "github:NixOS/nix/2c6d06e9387cf58167cb5a7ab91cee7333d8d17c";
      flake = false;
    };

    # Upstream aristocratos/btop, patched in-repo (packages/terminal/btop/patches).
    # Tracks upstream main (autoUpdate = true in lib/fork-packages.nix): the base
    # free-floats under the scheduled fork-sync, which runs `nix flake update
    # btop-src` + `nix run .#rebase-patches -- btop` to advance the two patches
    # (macOS disk IO sorting, cwd detail box) onto the new tail.
    btop-src = {
      url = "github:aristocratos/btop";
      flake = false;
    };

    drgn-src = {
      url = "git+https://github.com/osandov/drgn?ref=refs/tags/v0.2.0&submodules=1";
      flake = false;
    };

    perftest-src = {
      url = "git+https://github.com/linux-rdma/perftest?ref=refs/tags/26.04.17";
      flake = false;
    };

    # PostgreSQL uint128 extension source. The package marks the extension trusted
    # so non-superuser database owners can run `CREATE EXTENSION uint128`.
    pg-uint128-src = {
      url = "github:pg-uint/pg-uint128/1.2.0";
      flake = false;
    };

    fff-src = {
      url = "github:dmtrKovalenko/fff/v0.9.1";
      flake = false;
    };

    nu-jupyter-kernel-src = {
      url = "github:cptpiepmatz/nu-jupyter-kernel/016d5089d9b0c66beb95311e339e252c8b9dd4e4";
      flake = false;
    };

    launchk-src = {
      url = "github:mach-kernel/launchk/6f5f09e0dfa3fea662e859de5d7d49ac09a9dbe6";
      flake = false;
    };

    # snix (Rust reimplementation of Nix; TVL-style depot, no flake.nix) consumed
    # as a source tree so `packages/snix` builds its CLI through cargo-unit
    # instead of the upstream crate2nix `Cargo.nix`. The Cargo workspace lives in
    # the repo's `snix/` subdirectory. Pinned in flake.lock; `nix flake update
    # snix-src` to bump.
    #
    # `shallow=1` is load-bearing, not cosmetic: only the source tree at the
    # pinned rev is ever used (`ix.snixSrc` -> `packages/nix/snix`), never git
    # history or `revCount`. Without it the lock records `revCount`, which forces
    # Nix to clone snix's entire ~22k-commit history (~500 MB) to materialize the
    # input. nix-direnv's `use flake` then runs `nix flake archive` on every cold
    # load (it gc-roots every input), so that full clone ran on each fresh
    # `direnv` load and hung the shell for minutes. git.snix.dev serves an
    # arbitrary SHA at depth 1, so the shallow fetch grabs just the pinned commit
    # (~2 s) even after `canon` has moved ahead of the pin.
    snix-src = {
      url = "git+https://git.snix.dev/snix/snix?ref=canon&shallow=1";
      flake = false;
    };

    # Nous Research's Hermes agent ships its own NixOS module
    # (`nixosModules.default`) and uv2nix-built Python closure. Pinned to
    # a release tag so routine bumps are review events; `nix flake update
    # hermes-agent` after bumping the tag is the supported intake path.
    # Surfaced through `ix.hermesAgent` and consumed by
    # `examples/hermes/agent/`.
    hermes-agent = {
      url = "github:NousResearch/hermes-agent/v2026.5.16";
      inputs.nixpkgs.follows = "nixpkgs";
    };

    # TODO: re-add the `symphony` flake input that provided
    # `pkgs.symphony-room-server`. room-server's real home is the ix monorepo
    # (`crates/room`, `ix#packages.x86_64-linux.room-server`), but ix already
    # inputs index (`ix/flake.nix`), so index cannot source it from ix without a
    # circular flake dependency. Pin removed for now; re-add once that cycle is
    # resolved or room-server moves into this repo.

    # Ghostty's terminal VT engine, consumed as a source tree (not a flake) so
    # `packages/tui/vt/libghostty-vt` owns the build. Pinned to the commit the
    # local clone validated against; `requireZig` in `build.zig.zon` is exact
    # minor (0.15.x), so the build uses `pkgs.zig_0_15`. The pinned tree ships
    # `build.zig.zon.nix` (zon2nix output), which vendors every lazy Zig
    # dependency with SRI hashes for a network-free build. Bump by repointing
    # this rev and running `nix flake update ghostty`.
    ghostty = {
      url = "github:ghostty-org/ghostty/fd49716ea2084108aa098db390931c007495a1ab";
      flake = false;
    };

    # Upstream mesa (gitlab.freedesktop.org), patched in-repo for the panes GPU
    # guest (packages/vm/panes/guest-image/mesa/patches): the venus driver-side
    # external-semaphore delta (index#1742). De-forking replacement for the old
    # `indexable-inc/mesa` snapshot fork tarball; pinned by the `mesa-26.1.2`
    # tag, so the patched tree is the upstream tag tree plus the venus commits.
    #
    # `shallow=1` is load-bearing (same reason as snix-src): mesa's git history
    # is huge, and only the source tree at the pinned tag is ever used (through
    # `ix.mesaSrc` -> patchedSrc), never history or revCount. Without it the
    # lock records `revCount`, forcing a full-history clone on every cold
    # `nix flake archive` / direnv load. `flake.lock` still records the rev, so
    # `rebase-patches` can read the base rev; the URL is a real git remote so
    # its scratch-clone fetch works. Pinned by rev (autoUpdate = false in
    # lib/fork-packages.nix): a mesa bump must be rebased AND boot-validated on
    # a linux GPU host (the venus patch is validated by running the guest, not
    # by CI), so it moves only under a deliberate manual bump, never the cron.
    mesa-src = {
      url = "git+https://gitlab.freedesktop.org/mesa/mesa?ref=refs/tags/mesa-26.1.2&shallow=1";
      flake = false;
    };
  };

  outputs = {
    self,
    nixpkgs,
    rust-overlay,
    sdk-prebuilt-nixpkgs,
    sdk-prebuilt-rust-overlay,
    home-manager,
    hermes-agent,
    btop-src,
    drgn-src,
    perftest-src,
    pg-uint128-src,
    fff-src,
    nu-jupyter-kernel-src,
    launchk-src,
    snix-src,
    clippy-src,
    codex-src,
    nix-src,
    ghostty,
    mesa-src,
    skills,
    examples,
    tests,
    bench-filesystem,
    site,
    ...
  }: let
    inherit (nixpkgs) lib;

    # The flake's own source revision, threaded into `ix` so packages can
    # stamp the running build (e.g. the MCP server reports it as its
    # `serverInfo.version`). Clean tree -> the commit hash; dirty tree ->
    # `<commit>-dirty`; neither (eval from a non-git source) -> "dev".
    rev = self.rev or self.dirtyRev or "dev";

    # Commit time of that revision as unix epoch seconds, threaded alongside
    # `rev` so a build can stamp a human date and relative age. Under
    # reproducible builds there is no wall-clock compile time; this is the
    # source date Nix already records (`self.lastModified`): the commit time
    # on a clean tree, the working-tree mtime on a dirty one. `0` when
    # evaluated from a non-git source.
    revEpoch = self.lastModified or 0;

    # All path literals the flake exposes. Centralized so lib/ and
    # lib/per-system.nix have a single source of truth.
    # The data-subtree entries below resolve to the `outPath` of relative-path
    # inputs (declared `flake = false` above) instead of bare `./<dir>`
    # literals, so each consumer's source identity is scoped to just that
    # subtree. Nix-code roots the flake imports directly (`modules`,
    # `packagesRoot`) and the whole-repo `root` (the lint source intentionally
    # covers the entire tree) stay ordinary relative paths: those are
    # import-time / whole-repo by design, not per-subtree source identity.
    paths = {
      root = ./.;
      skills = skills.outPath;
      modules = ./modules;
      examples = examples.outPath;
      tests = tests.outPath;
      bench.filesystem = bench-filesystem.outPath;
      site = site.outPath;
      pgUint128Src = pg-uint128-src;
      packagesRoot = ./packages;
      minecraftCatalogs = ./packages/minecraft/catalogs;
      minecraftMods = ./packages/minecraft/catalogs/mods;
      minecraftPaperPlugins = ./packages/minecraft/catalogs/plugins/paper;
      minecraftVelocityPlugins = ./packages/minecraft/catalogs/plugins/velocity;
      minecraftLoaders = {
        paper = ./packages/minecraft/catalogs/loaders/paper;
        velocity = ./packages/minecraft/catalogs/loaders/velocity;
        fabric = ./packages/minecraft/catalogs/loaders/fabric;
      };
      # Repo maintenance scripts and package-owned source updaters.
      tools = {
        cveScan = ./packages/cve-scan/cve-scan.py;
        ixShellSyncIgnored = ./packages/maintainers/scripts/ix-shell-sync-ignored.py;
        mcSource = ./packages/minecraft/tools/mc-source.nu;
        updateSounds = ./packages/minecraft/tools/update-sounds.nu;
        updateLoaders = ./packages/minecraft/tools/update-loaders.py;
        updateMods = ./packages/minecraft/tools/update-mods.py;
      };
    };

    ix = import ./lib {
      inherit
        self
        rev
        revEpoch
        nixpkgs
        paths
        rust-overlay
        sdk-prebuilt-nixpkgs
        sdk-prebuilt-rust-overlay
        home-manager
        hermes-agent
        btop-src
        drgn-src
        perftest-src
        fff-src
        nu-jupyter-kernel-src
        launchk-src
        snix-src
        clippy-src
        codex-src
        nix-src
        ghostty
        mesa-src
        ;
    };
    devSystems = [
      "x86_64-linux"
      "aarch64-linux"
      "aarch64-darwin"
      "x86_64-darwin"
    ];
    perSystem = lib.genAttrs devSystems (
      system:
        import ./lib/per-system.nix {
          inherit
            system
            ix
            nixpkgs
            paths
            rust-overlay
            home-manager
            ;
        }
    );
    collect = key: lib.mapAttrs (_: out: out.${key}) perSystem;
    linuxDarwinAliases = perSystem.x86_64-linux.darwinPackageAliases or {};
    # Graft the Linux->Darwin cross aliases over a collected per-system set, so
    # a Darwin namespace resolves an aliased attr to the cross-compiled
    # x86_64-linux derivation instead of a native rebuild. Applied to both
    # `packages` (the consumer surface) and `cachePushRoots` (what
    # cache-push.yml publishes): the darwin cache lane realises the post-alias
    # set filtered to native aarch64-darwin drvs, so an alias-shadowed native
    # variant (e.g. dag-runner) is neither built nor published -- consumers can
    # never install it (#1890).
    withDarwinAliases = raw:
      raw
      // lib.genAttrs [
        "aarch64-darwin"
        "x86_64-darwin"
      ] (system: raw.${system} // (linuxDarwinAliases.${system} or {}));
    packages = withDarwinAliases (collect "packages");
  in {
    lib = ix;
    inherit (ix) nixosModules;
    darwinModules = {
      # Personal-but-shareable nix-darwin module for github:andrewgazelka: the
      # Homebrew package set (GUI casks, the `mas` brew, Mac App Store apps).
      # Companion to homeModules.andrewgazelka (which owns the home-manager
      # services); import it from a darwin host to get the casks merged in. See
      # users/andrewgazelka/darwin.nix.
      andrewgazelka = ./users/andrewgazelka/darwin.nix;
    };
    homeModules = {
      # Workstation-facing home-manager module: declare a service once, get a
      # native launchd agent on macOS and native systemd user units on Linux.
      portable-services = ix.portableServices.homeModule;
      # Declarative-but-writable JSON config files (last-applied 3-way merge),
      # for config an app rewrites at runtime. See lib/mutable-json.nix.
      mutable-json = ix.mutableJson.homeModule;
      # Reusable workstation module (macOS): declare Raycast Focus session
      # defaults (title, filter mode, duration) and have them written to the
      # com.raycast.macos defaults domain at switch time. Import it and set
      # `programs.raycast.focus = { enable = true; ... }`. See
      # modules/home/raycast.nix.
      raycast = ./modules/home/raycast.nix;
      # Agent CLI modules: Home Manager is the user-facing configuration
      # surface, while the package wrappers remain the implementation detail.
      claude-code = import ./packages/agent/home-manager/claude-code.nix {
        indexPackages = system: packages.${system};
      };
      codex = import ./packages/agent/home-manager/codex.nix {
        indexPackages = system: packages.${system};
      };
      # Personal-but-shareable workstation module for github:andrewgazelka: the
      # ix.dev downtime watcher + boss bar overlay + the shared say-detached
      # sound helper, all as portable services. Closed over the per-system
      # flake packages so it resolves bossbar / minecraft-sound for the host it
      # runs on. See users/andrewgazelka/home.nix.
      andrewgazelka = import ./users/andrewgazelka/home.nix {
        indexPackages = system: packages.${system};
        portableServicesModule = ix.portableServices.homeModule;
        claudeCodeModule = import ./packages/agent/home-manager/claude-code.nix {
          indexPackages = system: packages.${system};
        };
        inherit ix;
      };
      # Reusable workstation module: draw one Minecraft boss bar per in-flight
      # GitHub Actions run across a set of repos (green = running, filled by
      # elapsed / average duration; purple = queued/unpicked). Import it and set
      # `services.ciBars = { enable = true; repos = [ ... ]; }`. Closed over the
      # per-system packages so it resolves the `bossbar` CLI for the host. See
      # packages/minecraft/bossbar-overlay/ci-bars-home-module.nix.
      ci-bars = import ./packages/minecraft/bossbar-overlay/ci-bars-home-module.nix {
        indexPackages = system: packages.${system};
        portableServicesModule = ix.portableServices.homeModule;
        inherit ix;
      };
      # Workstation-facing module to sync corpus sources (agent/shell history,
      # Slack/Linear exports, git repos) to an S3/R2 parquet archive and/or
      # Mixedbread, as a portable timer service. Closed over the per-system
      # packages so it resolves the `indexer` for the host. See
      # packages/search/indexer/home-module.nix.
      indexer = import ./packages/search/indexer/home-module.nix {
        indexPackages = system: packages.${system};
        portableServicesModule = ix.portableServices.homeModule;
      };
      # Workstation-facing module: run the Symphony BEAM runtime as a user
      # service (native launchd agent on macOS, systemd user unit on Linux)
      # by composing portable-services. Mirrors the NixOS module's option
      # vocabulary; point `packDir` at a mutable checkout for hot-reloaded
      # workflows and skills. See packages/agent/symphony/home-module.nix.
      symphony = import ./packages/agent/symphony/home-module.nix {
        indexPackages = system: packages.${system};
        portableServicesModule = ix.portableServices.homeModule;
        # The beamvm runtime (services.symphony.runtime = "beamvm", the
        # default) hosts the compiled release in the persistent VM; the
        # module composes it directly so importing homeModules.symphony
        # alone is enough.
        beamvmModule = import ./packages/beamvm/home-module.nix {
          indexPackages = system: packages.${system};
          portableServicesModule = ix.portableServices.homeModule;
          inherit ix;
        };
        inherit ix;
      };
      # Workstation-facing module: persistent BEAM VMs as user services with
      # the OTP applications they host declared in Nix. Updating an app
      # hot-swaps its code in the running VM (no restart, no dropped
      # connections); only a beamvm/toolchain update restarts. See
      # packages/beamvm/home-module.nix and packages/beamvm/harness.ex.
      beamvm = import ./packages/beamvm/home-module.nix {
        indexPackages = system: packages.${system};
        portableServicesModule = ix.portableServices.homeModule;
        inherit ix;
      };
    };
    overlays.default = ix.overlay;
    templates = {};
    inherit packages;
    checks = collect "checks";
    # Sharded keying of the same check derivations for the memory-bounded CI
    # evaluator (the `.#check` gate and blast-radius); see lib/per-system.nix
    # (ENG-2201). Kept separate from `checks` because its per-package
    # `recurseForDerivations` groups are not derivations, which the flake
    # `checks` schema requires.
    ciChecks = collect "ciChecks";
    # Registry-derived map of package directory -> flake attr for every
    # `updateScript` package exposed on a system. update.yml's "Build changed
    # packages" step evaluates this to find which attr owns each file the
    # updaters changed, instead of deriving an attr from path segments
    # (#2036). Non-schema, so surfaced through `collect` like `ciChecks`.
    updatablePackages = collect "updatablePackages";
    # Per-attempt-patch closure build gates (RFC 0010 A3, #2098), keyed
    # `<system>.<fork>.<patch>`: the fork package rebuilt with the series
    # restricted to that patch's dag.json closure. Deliberately NOT under
    # `checks` (per-PR flake-check cost stays flat): built post-merge by the
    # scheduled fork-closure-gates workflow and by the `upstream-sync --open`
    # preflight. Non-schema, so surfaced through `collect` like `ciChecks`.
    forkClosureGates = collect "forkClosureGates";
    # CI-only view of `packages` with each NixOS image swapped for its
    # `toplevel` closure; cache-push.yml publishes this instead of the
    # monolithic `*-oci.tar` archives, which nothing substitutes. Non-schema,
    # so surfaced through `collect` like `ciChecks`. See lib/per-system.nix.
    cachePushRoots = withDarwinAliases (collect "cachePushRoots");
    formatter = collect "formatter";
    apps = collect "apps";
    devShells = collect "devShells";
  };
}
