# Import a `.ix` module: convert it to Nix source in-eval through the compiled
# ix2nix plugin (`builtins.wasm`, behind the `wasm-builtin` experimental
# feature of the patched nix-ix evaluator), then `import` the result.
#
# The converter the repo wires in (lib/default.nix, `importIxWasm`) is the
# `<out>/lib/ix2nix.wasm` of the `ix2nix-wasm` package, so importing a `.ix`
# file is import-from-derivation. Until 2026-07-25 it was a COMMITTED
# `lib/ix2nix.wasm` (#4136) precisely to avoid that: a `.ix` eval realized no
# store path, stayed offline, and needed no builder. The committed file had
# to be regenerated by hand after any edit under packages/ix2nix, a CI gate
# byte-compared it, and the gate spent more time red than the IFD costs.
# Building it cannot drift from the crate source because it IS the crate
# source.
#
# The build is pinned to x86_64-linux and that pin is load-bearing: the
# wasm32 artifact is not bit-identical across build hosts, since the native
# toolchain's store path feeds `-C metadata`. See `wasm/default.nix`.
#
# The wasm detour itself is transitional: once nix has
# proper parallel IFD we hope to drop the wasm converter and run the native
# ix2nix binary instead.
#
# Every converted module renders as `{ __dir, __importIx, __ixTy }: <body>`
# -- one calling convention regardless of whether the source uses `import()`
# or type annotations -- so this shim applies exactly that attrset: `__dir`
# anchors the module's relative `import()` specifiers, `__importIx` recurses
# through this same function for `.ix` imports, and `__ixTy` is the type
# runtime that decides whether emitted annotations check (`assert`) or cost
# nothing (`erase`).
{
  # The compiled converter (`ix2nix.wasm`). A parameter, not a default, so
  # this file never has to name the package that builds it: the repo wires in
  # the `ix2nix-wasm` output from lib/default.nix, pre-#4125 scaffolded flakes
  # pass the same output they already interpolate, and the e2e passes the
  # freshly built package. All three now agree on one value.
  converter,
  # Type-check mode for every module this shim imports; see `ix-ty.nix`.
  typeMode ? "assert",
}: let
  ixTy = import ./ix-ty.nix {mode = typeMode;};
  # `builtins.wasm` only exists under `wasm-builtin`; forced when a `.ix`
  # file is actually imported, and the throw names the two working setups so
  # a stock-nix eval fails with instructions instead of a missing-attribute
  # error.
  convert =
    if builtins ? wasm
    then
      builtins.wasm {
        path = converter;
        function = "convert";
      }
    else
      throw (
        "importIx: this evaluator has no `builtins.wasm`, so it cannot convert `.ix` modules. "
        + "Run through `ix eval` or `ix apply`, or use the nix-ix client with "
        + "`wasm-builtin` in `extra-experimental-features`."
      );
  importIx = path: let
    # Strings derived from a file inside a flake's realized source tree
    # (`baseNameOf path`, `readFile path`) carry that store path's context,
    # and `toFile` refuses both a name and contents that reference store
    # paths. Drop the context on both: the converted text is self-contained
    # source and the name is just a label, so neither loses a real
    # dependency (the eval depends on the `.ix` file through `readFile`
    # itself, not through the context).
    fileName = builtins.unsafeDiscardStringContext (baseNameOf path + ".nix");
    nixSource = builtins.unsafeDiscardStringContext (convert (builtins.readFile path));
  in
    import (builtins.toFile fileName nixSource) {
      __dir = dirOf path;
      __importIx = importIx;
      __ixTy = ixTy.forModule (toString path);
    };
in
  importIx
