[
  "set clipboard+=unnamed"
  "let mapleader=\" \""
  "\" FunctionTextObj"
  "\" dif  - delete the function body"
  "\" caf  - change the entire function"
  "\" vif  - visually select the function body"
  "\" yaf  - yank (copy) the entire function"
  "set functiontextobj"
  "Plug 'dbakker/vim-paragraph-motion'"
  "\" <count>ai\tAn Indentation level and line above."
  "\" <count>ii\tInner Indentation level (no line above)."
  "\" <count>aI\tAn Indentation level and lines above/below."
  "\" <count>iI\tInner Indentation level (no lines above/below)."
  "Plug 'michaeljsmith/vim-indent-object'"
  "Plug 'preservim/nerdtree'"
  "Plug 'terryma/vim-multiple-cursors'"
  "\" cx"
  "\" On the first use, define the first {motion} to exchange. On the second use, define the second {motion} and perform the exchange."
  "\""
  "\" cxx"
  "\""
  "\" Like cx, but use the current line."
  "Plug 'tommcdo/vim-exchange'"
  "Plug 'tpope/vim-commentary'"
  "Plug 'tpope/vim-surround'"
  "Plug 'vim-scripts/argtextobj.vim'"
  "\" Remap multiple-cursors shortcuts to match terryma/vim-multiple-cursors"
  "nmap <C-n> <Plug>NextWholeOccurrence"
  "xmap <C-n> <Plug>NextWholeOccurrence"
  "\"nmap <C-n> <Plug>NextOccurrence"
  "\"xmap <C-n> <Plug>NextOccurrence"
  "xmap <C-x> <Plug>SkipOccurrence"
  "xmap <C-p> <Plug>RemoveOccurrence"
  "\" Note that the default <A-n> and g<A-n> shortcuts don't work on Mac due to dead keys."
  "\" <A-n> is used to enter accented text e.g. ñ"
  "\" Feel free to pick your own mappings that are not affected. I like to use <leader>"
  "nmap <leader><C-n> <Plug>AllWholeOccurrences"
  "xmap <leader><C-n> <Plug>AllWholeOccurrences"
  "nmap <leader>g<C-n> <Plug>AllOccurrences"
  "xmap <leader>g<C-n> <Plug>AllOccurrences"
  "set rnu"
  "set scrolloff=30"
  "\"set scrolloff=200"
  "set hlsearch"
  "set nowrapscan"
  "nmap <S-A-j> <Action>(MethodDown)"
  "nmap <S-A-k> <Action>(MethodUp)"
  "nmap <leader>j <Action>(NextOccurence)"
  "nmap <leader>k <Action>(PreviousOccurence)"
  "nmap <leader>q <Action>(Rerun)"
  "\" Basic jumps"
  "nmap <leader><leader>s :action KJumpAction<cr>"
  "nmap <leader><leader>w :action KJumpAction.Word0<cr>"
  "nmap <leader><leader>l :action KJumpAction.Line<cr>"
  "nmap f :action KJumpAction.Word0<cr>"
  "nmap F :action KJumpAction.Line<cr>"
  "\" Additional jumps"
  "nmap <leader><leader>c :action KJumpAction.Char2<cr>"
  "nmap <leader><leader>f :action KJumpAction.Word1<cr>"
  "let g:argtextobj_pairs=\"(:),{:},<:>,{:}\""
  "nmap <leader>q <Action>(Run)"
  "nmap <leader><leader>h <Action>(Vcs.ShowTabbedFileHistory)"
  "nmap <leader>o ysiw>iOption<Esc>"
  "nnoremap ma mA"
  "nnoremap mb mB"
  "nnoremap mc mC"
  "nnoremap md mD"
  "nnoremap me mE"
  "nnoremap mf mF"
  "nnoremap mg mG"
  "nnoremap mh mH"
  "nnoremap mi mI"
  "nnoremap mj mJ"
  "nnoremap mk mK"
  "nnoremap ml mL"
  "nnoremap mm mM"
  "nnoremap mn mN"
  "nnoremap mo mO"
  "nnoremap mp mP"
  "nnoremap mq mQ"
  "nnoremap mr mR"
  "nnoremap ms mS"
  "nnoremap mt mT"
  "nnoremap mu mU"
  "nnoremap mv mV"
  "nnoremap mw mW"
  "nnoremap mx mX"
  "nnoremap my mY"
  "nnoremap mz mZ"
  "nnoremap 'a 'Azt"
  "nnoremap 'b 'Bzt"
  "nnoremap 'c 'Czt"
  "nnoremap 'd 'Dzt"
  "nnoremap 'e 'Ezt"
  "nnoremap 'f 'Fzt"
  "nnoremap 'g 'Gzt"
  "nnoremap 'h 'Hzt"
  "nnoremap 'i 'Izt"
  "nnoremap 'j 'Jzt"
  "nnoremap 'k 'Kzt"
  "nnoremap 'l 'Lzt"
  "nnoremap 'm 'Mzt"
  "nnoremap 'n 'Nzt"
  "nnoremap 'o 'Ozt"
  "nnoremap 'p 'Pzt"
  "nnoremap 'q 'Qzt"
  "nnoremap 'r 'Rzt"
  "nnoremap 's 'Szt"
  "nnoremap 't 'Tzt"
  "nnoremap 'u 'Uzt"
  "nnoremap 'v 'Vzt"
  "nnoremap 'w 'Wzt"
  "nnoremap 'x 'Xzt"
  "nnoremap 'y 'Yzt"
  "nnoremap 'z 'Zzt"
  "set ideajoin"
]
