// Generated by unibind's swift backend. Do not edit.
//
// A sample boundary exercising the swift backend surface.

/// Boundary failures.
public enum SampleError: Error {
    /// The store is gone.
    case storeGone(message: String)
    /// Bad input.
    case invalid(message: String)
}

extension __UnibindSampleError: Error {}

extension SampleError {
    init(__error: __UnibindSampleError) {
        switch __error {
        case .StoreGone(let message):
            self = .storeGone(message: message.toString())
        case .Invalid(let message):
            self = .invalid(message: message.toString())
        }
    }
}

/// A row.
public struct Row {
    /// Identifier.
    public var id: UInt64
    public var name: String
    public var tags: [String]
    public var weights: [String: Double]
    public var blob: [UInt8]
    public var home: String?

    public init(id: UInt64, name: String, tags: [String], weights: [String: Double], blob: [UInt8], home: String?) {
        self.id = id
        self.name = name
        self.tags = tags
        self.weights = weights
        self.blob = blob
        self.home = home
    }
}

extension Row {
    init(__handle: __UnibindRow) {
        self.id = __handle.id()
        self.name = __handle.name().toString()
        self.tags = { () -> [String] in let __box = __handle.tags(); var __out: [String] = []; for __index in 0..<__box.len() { __out.append(__box.get(__index).toString()) }; return __out }()
        self.weights = { () -> [String: Double] in let __box = __handle.weights(); var __out: [String: Double] = [:]; for __index in 0..<__box.len() { __out[__box.key_at(__index).toString()] = __box.value_at(__index) }; return __out }()
        self.blob = { () -> [UInt8] in let __vec = __handle.blob(); var __out: [UInt8] = []; for __index in 0..<UInt(__vec.len()) { __out.append(__vec.get(index: __index)!) }; return __out }()
        self.home = __handle.home().map { $0.toString() }
    }

    func __unibindHandle() -> __UnibindRow {
        let __field_tags = __unibind_new_vec_of_string()
        for __element in self.tags {
            __field_tags.push(__element)
        }
        let __field_weights = __unibind_new_map_of_string_to_f64()
        for (__key, __value) in self.weights {
            __field_weights.insert(__key, __value)
        }
        let __field_blob = RustVec<UInt8>()
        for __element in self.blob {
            __field_blob.push(value: __element)
        }
        return __unibind_new_row(self.id, self.name, __field_tags, __field_weights, __field_blob, self.home)
    }
}

/// Fetch rows.
///
/// Docs become documentation comments.
///
/// - Throws: `SampleError`.
public func rows(store: String, limit: UInt = 10, root: String? = nil) throws -> [Row] {
    do {
        let __result = try __unibind_fn_rows(store, limit, root)
        return { () -> [Row] in let __box = __result; var __out: [Row] = []; for __index in 0..<__box.len() { __out.append(Row(__handle: __box.get(__index))) }; return __out }()
    } catch let __error as __UnibindSampleError {
        throw SampleError(__error: __error)
    }
}

/// Echo the weights, sorted by key on the way back.
public func weightsEcho(weights: [String: Double]) -> [String: Double] {
    let __arg_weights = __unibind_new_map_of_string_to_f64()
    for (__key, __value) in weights {
        __arg_weights.insert(__key, __value)
    }
    let __result = __unibind_fn_weights_echo(__arg_weights)
    return { () -> [String: Double] in let __box = __result; var __out: [String: Double] = [:]; for __index in 0..<__box.len() { __out[__box.key_at(__index).toString()] = __box.value_at(__index) }; return __out }()
}

public func touch(path: String, data: [UInt8], ratio: Double = 0.5, note: String = "note", flush: Bool = false) -> Bool {
    let __arg_data = RustVec<UInt8>()
    for __element in data {
        __arg_data.push(value: __element)
    }
    let __result = __unibind_fn_touch(path, __arg_data, ratio, note, flush)
    return __result
}

/// The first row, if any.
public func first(rows: [Row]) -> Row? {
    let __arg_rows = __unibind_new_vec_of_row()
    for __element in rows {
        __arg_rows.push(__element.__unibindHandle())
    }
    let __result = __unibind_fn_first(__arg_rows)
    return { () -> Row? in let __box = __result; if __box.is_some() { return Row(__handle: __box.value()) }; return nil }()
}

/// Echo an optional label.
public func echoOptionString(value: String? = nil) -> String? {
    let __result = __unibind_fn_echo_option_string(value)
    return __result.map { $0.toString() }
}

/// Echo a nested composition: map values that are vectors.
public func series(table: [String: [Double]]) -> [String: [Double]] {
    let __arg_table = __unibind_new_map_of_string_to_vec_of_f64()
    for (__key, __value) in table {
        let __arg_table_v = RustVec<Double>()
        for __element in __value {
            __arg_table_v.push(value: __element)
        }
        __arg_table.insert(__key, __arg_table_v)
    }
    let __result = __unibind_fn_series(__arg_table)
    return { () -> [String: [Double]] in let __box = __result; var __out: [String: [Double]] = [:]; for __index in 0..<__box.len() { __out[__box.key_at(__index).toString()] = { () -> [Double] in let __vec = __box.value_at(__index); var __out: [Double] = []; for __index in 0..<UInt(__vec.len()) { __out.append(__vec.get(index: __index)!) }; return __out }() }; return __out }()
}

public func echoIsize(value: Int) -> Int {
    let __result = __unibind_fn_echo_isize(value)
    return __result
}

public func count(rows: [Row]) -> UInt {
    let __arg_rows = __unibind_new_vec_of_row()
    for __element in rows {
        __arg_rows.push(__element.__unibindHandle())
    }
    let __result = __unibind_fn_count(__arg_rows)
    return __result
}

/// Echo bytes by value.
public func echoBytes(value: [UInt8]) -> [UInt8] {
    let __arg_value = RustVec<UInt8>()
    for __element in value {
        __arg_value.push(value: __element)
    }
    let __result = __unibind_fn_echo_bytes(__arg_value)
    return { () -> [UInt8] in let __vec = __result; var __out: [UInt8] = []; for __index in 0..<UInt(__vec.len()) { __out.append(__vec.get(index: __index)!) }; return __out }()
}

/// Echo a float.
public func echoF32(value: Float) -> Float {
    let __result = __unibind_fn_echo_f32(value)
    return __result
}

