# The `ex` target of `unibind.lib.build`: the Elixir host modules generated
# straight from the crate's built NIF library (the IR travels in its link
# section), merged with the hand-written mix project into one mix-importable
# package: `lib/` (generated .ex), `priv/native/<soname>.so`, and the
# caller's `mix.exs` and tests.
{
  lib,
  pkgs,
  packageRegistry,
  rustWorkspace,
}: {
  crate,
  # Directory with the hand-written mix project files (`mix.exs`, tests,
  # `.formatter.exs`) overlaid onto the generated tree. `null` means the
  # package is fully generated (no runnable mix project, just `lib/` and the
  # NIF).
  mixSource ? null,
}: let
  entry =
    packageRegistry.byId.${crate}
      or (throw "unibind.lib.build: `${crate}` has no package.nix in the registry; add one with `inRustWorkspace = true`");

  libraryKey = lib.replaceStrings ["-"] ["_"] crate;
  library =
    rustWorkspace.units.libraries.${libraryKey}
      or (throw "unibind.lib.build: the shared workspace graph has no library unit `${libraryKey}` for `${crate}` (packages/${entry.relativePath})");

  genBin = rustWorkspace.units.binaries."unibind-gen";

  # `:erlang.load_nif/2` appends the platform extension itself, and the BEAM
  # loads `.so` on every unix including darwin, so the library installs
  # under one canonical name on both. The darwin link needs `-undefined
  # dynamic_lookup` for the `enif_*` symbols; unlike the py target's
  # `pyExtension` registry marker, the crate carries that itself in a
  # build.rs (see packages/unibind/conformance-ex/build.rs).
  soname = "lib${libraryKey}.so";

  # Locate the built NIF library: the unit output may suffix the metadata
  # hash, and the extension differs per OS. Same loop as ./py.nix.
  findCdylib = ''
    cdylib=""
    for candidate in \
      ${library}/lib/lib${libraryKey}.so \
      ${library}/lib/lib${libraryKey}-*.so \
      ${library}/lib/lib${libraryKey}.dylib \
      ${library}/lib/lib${libraryKey}-*.dylib
    do
      if [ -f "$candidate" ]; then
        cdylib="$candidate"
        break
      fi
    done
    if [ -z "$cdylib" ]; then
      echo "unibind: no cdylib under ${library}/lib" >&2
      ls -la ${library}/lib >&2 || true
      exit 1
    fi
  '';

  # The generated Elixir side: `lib/<app>/native.ex` (NIF stubs whose load
  # path is derived from the soname) and `lib/<app>.ex` (typespec'd
  # wrapper). The artifact is staged under the canonical soname so the
  # generated load call and the installed file cannot drift apart.
  generated =
    pkgs.runCommand "unibind-${crate}-ex-generated"
    {
      strictDeps = true;
      nativeBuildInputs = [genBin];
      meta.description = "unibind-generated Elixir host modules for ${crate}";
    }
    ''
      set -euo pipefail
      ${findCdylib}
      staged="$TMPDIR/${soname}"
      cp "$cdylib" "$staged"
      mkdir -p "$out"
      unibind-gen ex --artifact "$staged" --out "$out"
    '';

  # The mix-importable package: generated lib/ first, the NIF under
  # priv/native/, hand-written sources layered on top. A hand-written file
  # that shadows a generated one fails the build instead of silently
  # winning (mirrors ./py.nix).
  mixPackage =
    pkgs.runCommand "unibind-${crate}-mix-package"
    {
      strictDeps = true;
      meta.description = "Mix package for ${crate}: generated .ex modules plus the NIF library";
    }
    ''
      set -euo pipefail
      mkdir -p "$out/priv/native"
      cp -R ${generated}/. "$out/"
      chmod -R u+w "$out"
      ${findCdylib}
      install -m555 "$cdylib" "$out/priv/native/${soname}"
      ${lib.optionalString (mixSource != null) ''
        (cd ${mixSource} && find . -type f -print) | sed 's|^\./||' | while read -r file; do
          if [ -e "$out/$file" ]; then
            echo "unibind: $file is generated by unibind-gen; delete the hand-written copy" >&2
            exit 1
          fi
          mkdir -p "$out/$(dirname "$file")"
          cp ${mixSource}/"$file" "$out/$file"
        done
      ''}
    '';
in {
  inherit generated library mixPackage soname;
}
