# The `jvm` target of `unibind.lib.build`: the single Java class generated
# straight from the crate's built cdylib (the IR travels in its link
# section), plus the native library staged under the exact name
# `System.mapLibraryName` produces for the library key, merged with
# hand-written Java sources into one compilable tree: `java/` (generated +
# hand-written .java) and `native/<soname>`. Consumers compile `java/` with
# any JDK 22+ (the class uses the final FFM API) and run with
# `--enable-native-access=ALL-UNNAMED` plus either
# `-Dunibind.library.<key>=<path to native/<soname>>` or the native
# directory on `java.library.path`.
{
  lib,
  pkgs,
  rustWorkspace,
}: {
  crate,
  # Java package the generated class is declared in (`com.example.thing`);
  # the file lands under the matching directory tree inside `java/`. `null`
  # puts the class in the unnamed package at the `java/` root.
  package ? null,
  # Directory with hand-written .java sources overlaid onto the generated
  # tree under `java/`. `null` means the surface is fully generated.
  javaSource ? null,
}: let
  libraryKey = lib.replaceStrings ["-"] ["_"] crate;
  library =
    rustWorkspace.units.libraries.${libraryKey}
      or (throw "unibind.lib.build: the shared workspace graph has no library unit `${libraryKey}` for `${crate}`; the crate needs a cdylib target and a package.nix with inRustWorkspace");

  genBin = rustWorkspace.units.binaries.unibind-gen;

  # What `System.mapLibraryName("${libraryKey}")` returns on this OS; the
  # generated class falls back to it when the `unibind.library.<key>`
  # system property is unset, so the staged file must carry this name.
  soname =
    if pkgs.stdenv.hostPlatform.isDarwin
    then "lib${libraryKey}.dylib"
    else "lib${libraryKey}.so";

  # Locate the built cdylib: the unit output may suffix the metadata hash,
  # and the extension differs per OS. Same loop as ./py.nix.
  findCdylib = ''
    cdylib=""
    for candidate in \
      ${library}/lib/lib${libraryKey}.so \
      ${library}/lib/lib${libraryKey}-*.so \
      ${library}/lib/lib${libraryKey}.dylib \
      ${library}/lib/lib${libraryKey}-*.dylib
    do
      if [ -f "$candidate" ]; then
        cdylib="$candidate"
        break
      fi
    done
    if [ -z "$cdylib" ]; then
      echo "unibind: no cdylib under ${library}/lib" >&2
      ls -la ${library}/lib >&2 || true
      exit 1
    fi
  '';

  # The generated Java side: one `<Class>.java` under its package's
  # directory path.
  generated =
    pkgs.runCommand "unibind-${crate}-jvm-generated"
    {
      strictDeps = true;
      nativeBuildInputs = [genBin];
      meta.description = "unibind-generated Java host class for ${crate}";
    }
    ''
      set -euo pipefail
      ${findCdylib}
      mkdir -p "$out"
      unibind-gen jvm \
        --artifact "$cdylib" \
        ${lib.optionalString (package != null) "--package ${lib.escapeShellArg package}"} \
        --out "$out"
    '';

  # The compilable tree: generated java/ first, the native library under
  # native/, hand-written sources layered on top. A hand-written file that
  # shadows a generated one fails the build instead of silently winning
  # (mirrors ./ex.nix).
  jvmPackage =
    pkgs.runCommand "unibind-${crate}-jvm-package"
    {
      strictDeps = true;
      meta.description = "Java sources plus the native library for ${crate}";
    }
    ''
      set -euo pipefail
      mkdir -p "$out/java" "$out/native"
      cp -R ${generated}/. "$out/java/"
      chmod -R u+w "$out"
      ${findCdylib}
      install -m555 "$cdylib" "$out/native/${soname}"
      ${lib.optionalString (javaSource != null) ''
        (cd ${javaSource} && find . -type f -print) | sed 's|^\./||' | while read -r file; do
          if [ -e "$out/java/$file" ]; then
            echo "unibind: java/$file is generated by unibind-gen; delete the hand-written copy" >&2
            exit 1
          fi
          mkdir -p "$out/java/$(dirname "$file")"
          cp ${javaSource}/"$file" "$out/java/$file"
        done
      ''}
    '';
in {
  inherit generated jvmPackage library libraryKey soname;
}
