# The `py` target of `unibind.lib.build`: generated host files straight from
# the crate's built cdylib (the IR travels in its link section), the merged
# python site tree, the strict type gate over it, the importable module
# (the packages/mcp bundle shape), and the Linux wheel.
{
  lib,
  pkgs,
  packageRegistry,
  rustWorkspace,
  buildPyStrictCheck,
}: {
  crate,
  # Import-package name (`import <package>`); generated files land under
  # `<package>/`.
  package,
  # Filename stem of the native extension inside the package -- the pyo3
  # module name. The default matches the repo convention (`scipql` imports
  # `_scipql`).
  moduleName ? "_${package}",
  # PyPI distribution name stamped into the wheel.
  distName ? "ix-${package}",
  # Directory CONTAINING the package dir with hand-written sources (a
  # crate's `python/`, so `<pythonSource>/<package>/...` overlays the
  # generated files). `null` means the package is fully generated.
  pythonSource ? null,
  # Third-party imports of the hand-written sources, resolvable in the
  # strict check and propagated from the module output.
  pythonPackages ? (_ps: []),
}: let
  entry =
    packageRegistry.byId.${crate}
      or (throw "unibind.lib.build: `${crate}` has no package.nix in the registry; add one with `pyExtension = true`");

  libraryKey = lib.replaceStrings ["-"] ["_"] crate;
  library =
    if entry.pyExtension
    then rustWorkspace.units.libraries.${libraryKey}
        or (throw "unibind.lib.build: the shared workspace graph has no library unit `${libraryKey}` for `${crate}`")
    # The marker is load-bearing: it is what makes lib/rust/workspace.nix
    # inject the darwin `-undefined dynamic_lookup` link args into this
    # crate's cdylib link (the per-crate build.rs replacement).
    else throw "unibind.lib.build: `${crate}` must set `pyExtension = true` in packages/${entry.relativePath}/package.nix";

  genBin = rustWorkspace.units.binaries."unibind-gen";

  # Locate the built extension: the unit output may suffix the metadata hash,
  # and the extension differs per OS. Same loop the mcp module bundles use.
  findCdylib = ''
    cdylib=""
    for candidate in \
      ${library}/lib/lib${libraryKey}.so \
      ${library}/lib/lib${libraryKey}-*.so \
      ${library}/lib/lib${libraryKey}.dylib \
      ${library}/lib/lib${libraryKey}-*.dylib
    do
      if [ -f "$candidate" ]; then
        cdylib="$candidate"
        break
      fi
    done
    if [ -z "$cdylib" ]; then
      echo "unibind: no cdylib under ${library}/lib" >&2
      ls -la ${library}/lib >&2 || true
      exit 1
    fi
  '';

  # A hand-written `__init__.py` wins over the generated wrapper (`--skip-init`
  # below); every other collision is an error in the site merge.
  skipInit = pythonSource != null && builtins.pathExists "${pythonSource}/${package}/__init__.py";

  generated =
    pkgs.runCommand "unibind-${crate}-py-generated"
    {
      strictDeps = true;
      nativeBuildInputs = [genBin];
      meta.description = "unibind-generated Python host files for ${crate}";
    }
    ''
      set -euo pipefail
      ${findCdylib}
      mkdir -p "$out"
      unibind-gen py \
        --artifact "$cdylib" \
        --package ${lib.escapeShellArg package} \
        --out "$out" ${lib.optionalString skipInit "--skip-init"}
    '';

  # The one importable source tree: generated files first, hand-written
  # sources layered on top. A hand-written file that shadows a generated one
  # (other than `__init__.py`, which `--skip-init` already handled) fails the
  # build instead of silently winning.
  pythonSite =
    pkgs.runCommand "unibind-${crate}-python-site"
    {
      strictDeps = true;
      meta.description = "Merged generated + hand-written Python sources for ${crate}";
    }
    ''
      set -euo pipefail
      mkdir -p "$out/${package}"
      cp -R ${generated}/${package}/. "$out/${package}/"
      chmod -R u+w "$out/${package}"
      ${lib.optionalString (pythonSource != null) ''
        (cd ${pythonSource}/${package} && find . -type f -print) | sed 's|^\./||' | while read -r file; do
          if [ -e "$out/${package}/$file" ] && [ "$file" != "__init__.py" ]; then
            echo "unibind: ${package}/$file is generated by unibind-gen; delete the hand-written copy" >&2
            exit 1
          fi
          mkdir -p "$out/${package}/$(dirname "$file")"
          cp ${pythonSource}/${package}/"$file" "$out/${package}/$file"
        done
      ''}
    '';

  # Strict type + annotation gate (zuban --strict + ruff ANN) over the merged
  # tree, so hand-written wrappers are checked against the generated stubs.
  pyStrict = buildPyStrictCheck pkgs {
    pname = crate;
    pythonSrc = pythonSite;
    inherit pythonPackages;
  };

  # Importable module for interpreter bundles (packages/mcp): a site-packages
  # tree holding the merged package plus the cdylib installed as the abi3
  # extension. `toPythonModule` plus eval-level `propagatedBuildInputs` let
  # `python3.withPackages` pull the package's own third-party imports.
  module = pkgs.python3.pkgs.toPythonModule (
    pkgs.runCommand "unibind-${crate}-python-module"
    {
      strictDeps = true;
      propagatedBuildInputs = pythonPackages pkgs.python3.pkgs;
      meta.description = "${crate} PyO3 module (importable `${package}` package)";
    }
    ''
      set -euo pipefail
      site="$out/${pkgs.python3.sitePackages}/${package}"
      mkdir -p "$site"
      cp -R ${pythonSite}/${package}/. "$site/"
      chmod -R u+w "$site"
      ${findCdylib}
      install -m555 "$cdylib" "$site/${moduleName}.abi3.so"
    ''
  );

  # Wheel version: `__version__` in the module is CARGO_PKG_VERSION, and every
  # workspace crate inherits the workspace version, so the root manifest is
  # the single source of truth.
  workspaceVersion = (lib.importTOML (rustWorkspace.root + "/Cargo.toml")).workspace.package.version;

  platformTag =
    {
      x86_64-linux = "manylinux_2_34_x86_64";
      aarch64-linux = "manylinux_2_34_aarch64";
    }
    .${
      pkgs.stdenv.hostPlatform.system
    }
      or (throw "unibind: python wheels are Linux-only, got ${pkgs.stdenv.hostPlatform.system}; macOS needs install-name fixups and macosx tags nobody consumes yet (same policy as packages/search/search-py)");

  # Lazy: only forced when a caller demands the wheel, so the module/site
  # outputs stay usable on darwin.
  wheel =
    pkgs.runCommand "${distName}-wheel"
    {
      strictDeps = true;
      nativeBuildInputs = [
        pkgs.coreutils
        pkgs.python3
        pkgs.patchelf
        pkgs.removeReferencesTo
      ];
      meta.description = "${distName} Python wheel (unibind-generated PyO3 bindings for `${package}`)";
    }
    ''
      set -euo pipefail
      ${findCdylib}

      sanitized="$TMPDIR/$(basename "$cdylib")"
      cp "$cdylib" "$sanitized"
      chmod u+w "$sanitized"

      # Strip the build-time rpath and nixpkgs toolchain references so the
      # wheel is not pinned to this store path.
      if patchelf --print-rpath "$sanitized" >/dev/null 2>&1; then
        patchelf --remove-rpath "$sanitized"
      fi
      remove-references-to \
        -t ${pkgs.glibc} \
        -t ${pkgs.stdenv.cc.cc.lib} \
        "$sanitized"

      mkdir -p "$out"
      python3 ${./mkwheel.py} \
        --package ${lib.escapeShellArg package} \
        --dist-name ${lib.escapeShellArg distName} \
        --so-name ${lib.escapeShellArg "${moduleName}.abi3.so"} \
        --cdylib "$sanitized" \
        --python-src ${pythonSite} \
        --version ${lib.escapeShellArg workspaceVersion} \
        --platform-tag ${platformTag} \
        --out "$out"
    '';
in {
  inherit library module pythonSite wheel;
  tests = {inherit pyStrict;};
}
