//! Prune the monorepo `Cargo.lock` to the entries reachable from the mirrored
//! crates. No re-resolution: every kept entry is byte-identical in content to
//! the monorepo's, so a mirror builds against exactly the versions the
//! monorepo builds against. Output follows cargo's own serialization (field
//! order, one-space list indent, entry order preserved from the input, which
//! cargo keeps sorted).

use std::collections::{HashMap, HashSet, VecDeque};
use std::fmt::Write;

use anyhow::{Context, Result, bail};
use toml_edit::{DocumentMut, Item};

struct Package {
    name: String,
    version: String,
    source: Option<String>,
    checksum: Option<String>,
    dependencies: Vec<String>,
}

/// Emit the subset of `lock` reachable from the workspace members named in
/// `roots`.
pub fn prune(lock: &str, roots: &[&str]) -> Result<String> {
    let doc: DocumentMut = lock.parse().context("parsing Cargo.lock")?;
    let format_version = doc
        .get("version")
        .and_then(Item::as_integer)
        .context("Cargo.lock has no `version` field")?;
    let packages = parse_packages(&doc)?;

    let mut by_name: HashMap<&str, Vec<usize>> = HashMap::new();
    for (index, package) in packages.iter().enumerate() {
        by_name.entry(&package.name).or_default().push(index);
    }
    let resolve = |spec: &str| -> Result<usize> {
        let mut parts = spec.split_whitespace();
        let name = parts.next().context("empty dependency spec")?;
        let version = parts.next();
        let candidates = by_name
            .get(name)
            .with_context(|| format!("lock entry references unknown package `{name}`"))?;
        match version {
            Some(version) => candidates
                .iter()
                .copied()
                .find(|&index| packages[index].version == version)
                .with_context(|| format!("no lock entry for `{name} {version}`")),
            None => match candidates.as_slice() {
                [index] => Ok(*index),
                _ => bail!("ambiguous bare dependency `{name}` in Cargo.lock"),
            },
        }
    };

    let mut keep: HashSet<usize> = HashSet::new();
    let mut queue: VecDeque<usize> = roots
        .iter()
        .map(|root| resolve(root))
        .collect::<Result<_>>()
        .context("resolving mirrored crates in Cargo.lock")?;
    while let Some(index) = queue.pop_front() {
        if !keep.insert(index) {
            continue;
        }
        for spec in &packages[index].dependencies {
            queue.push_back(resolve(spec)?);
        }
    }

    let kept = packages
        .iter()
        .enumerate()
        .filter(|(index, _)| keep.contains(index))
        .map(|(_, package)| package);
    Ok(render(format_version, kept))
}

fn parse_packages(doc: &DocumentMut) -> Result<Vec<Package>> {
    let entries = doc
        .get("package")
        .and_then(Item::as_array_of_tables)
        .context("Cargo.lock has no [[package]] entries")?;
    let mut packages = Vec::new();
    for entry in entries {
        let field = |key: &str| entry.get(key).and_then(Item::as_str).map(str::to_owned);
        let name = field("name").context("lock entry without `name`")?;
        let version =
            field("version").with_context(|| format!("lock entry `{name}` without `version`"))?;
        let dependencies = entry
            .get("dependencies")
            .and_then(Item::as_array)
            .map(|list| {
                list.iter()
                    .filter_map(toml_edit::Value::as_str)
                    .map(str::to_owned)
                    .collect()
            })
            .unwrap_or_default();
        packages.push(Package {
            name,
            version,
            source: field("source"),
            checksum: field("checksum"),
            dependencies,
        });
    }
    Ok(packages)
}

fn render<'a>(format_version: i64, packages: impl Iterator<Item = &'a Package>) -> String {
    let mut out = String::from(
        "# This file is automatically @generated by Cargo.\n\
         # It is not intended for manual editing.\n",
    );
    let _ = writeln!(out, "version = {format_version}");
    for package in packages {
        out.push_str("\n[[package]]\n");
        let _ = writeln!(out, "name = \"{}\"", package.name);
        let _ = writeln!(out, "version = \"{}\"", package.version);
        if let Some(source) = &package.source {
            let _ = writeln!(out, "source = \"{source}\"");
        }
        if let Some(checksum) = &package.checksum {
            let _ = writeln!(out, "checksum = \"{checksum}\"");
        }
        if !package.dependencies.is_empty() {
            out.push_str("dependencies = [\n");
            for dependency in &package.dependencies {
                let _ = writeln!(out, " \"{dependency}\",");
            }
            out.push_str("]\n");
        }
    }
    out
}

#[cfg(test)]
mod tests {
    use super::*;

    // Shaped like the real root lock: a path-dep member (no source/checksum),
    // registry deps, and two versions of one crate to exercise disambiguated
    // `name version` specs.
    const LOCK: &str = r#"# This file is automatically @generated by Cargo.
# It is not intended for manual editing.
version = 4

[[package]]
name = "indicatif"
version = "0.18.3"
source = "registry+https://github.com/rust-lang/crates.io-index"
checksum = "0011aaf19375816b0a75dbe10f5e5143e828b40dc70f9dbe12ee7160b1a89f0"
dependencies = [
 "unit-prefix",
 "winnow 1.0.3",
]

[[package]]
name = "other-member"
version = "0.1.0"
dependencies = [
 "winnow 0.5.40",
]

[[package]]
name = "progress-style"
version = "0.1.0"
dependencies = [
 "indicatif",
]

[[package]]
name = "unit-prefix"
version = "0.5.1"
source = "registry+https://github.com/rust-lang/crates.io-index"
checksum = "323402cff2dd658f39ca17c789b502021b3f18707c91cdf22e3838e1b4023817"

[[package]]
name = "winnow"
version = "0.5.40"
source = "registry+https://github.com/rust-lang/crates.io-index"
checksum = "f593a95398737aeed53e489c785df13f3618e41dbcd6718c6addbf1395aa6876"

[[package]]
name = "winnow"
version = "1.0.3"
source = "registry+https://github.com/rust-lang/crates.io-index"
checksum = "21a0236b59786fed61e2a80582dd500fe61f18b6b3f3bc348bbc2b1c14262a1c"
"#;

    #[test]
    fn keeps_exactly_the_reachable_entries() {
        let pruned = prune(LOCK, &["progress-style"]).expect("prunes");
        assert!(pruned.contains("name = \"progress-style\""));
        assert!(pruned.contains("name = \"indicatif\""));
        assert!(pruned.contains("name = \"unit-prefix\""));
        assert!(pruned.contains("\"winnow 1.0.3\""));
        assert!(!pruned.contains("version = \"0.5.40\""));
        assert!(!pruned.contains("other-member"));
    }

    #[test]
    fn output_is_cargo_shaped_and_reparses() {
        let pruned = prune(LOCK, &["progress-style"]).expect("prunes");
        assert!(pruned.starts_with("# This file is automatically @generated by Cargo.\n"));
        assert!(pruned.contains("version = 4\n"));
        // The subset containing every input entry must round-trip byte-for-byte.
        let all = prune(LOCK, &["progress-style", "other-member"]).expect("prunes all");
        assert_eq!(all, LOCK);
    }

    #[test]
    fn rejects_unknown_root() {
        let err = prune(LOCK, &["nope"]).expect_err("must fail");
        assert!(
            err.to_string().contains("resolving mirrored crates"),
            "{err}"
        );
    }
}
