//! Over a real SCIP index of a two-file crate, so what is checked is what
//! rust-analyzer actually resolves rather than what a hand-built fixture
//! asserts. The fixture is scipql's, which is generated by the same indexer.

use std::path::Path;

use super::{Granularity, Options, graph, load_index, package_of};

fn fixture() -> (scip::types::Index, std::path::PathBuf) {
    let dir = Path::new(env!("CARGO_MANIFEST_DIR"))
        .parent()
        .and_then(Path::parent)
        .expect("packages/")
        .join("scipql");
    let index = load_index(&dir.join("core/tests/fixtures/two-sockets/index.scip")).expect("index");
    (index, dir.join("tests/fixtures/two-sockets"))
}

#[test]
fn a_file_depends_on_the_file_defining_what_it_uses() {
    let (index, root) = fixture();
    let dag = graph(&index, &root, &Options::default()).expect("graph");

    let module = dag
        .nodes()
        .find(|node| node.key.ends_with("net.rs"))
        .expect("net.rs is in the index");
    assert_eq!(module.kind.as_deref(), Some("module"));
    assert!(
        module.cost.is_some_and(|lines| lines > 0.0),
        "a module's cost is its line count",
    );

    let analysis = dag.analyze();
    let lib = analysis
        .ranked
        .iter()
        .find(|node| node.key.ends_with("lib.rs"))
        .expect("lib.rs is in the index");
    assert!(
        lib.blast_radius > 0 || lib.depth > 0,
        "lib.rs must be wired into the graph, got {lib:?}",
    );
}

#[test]
fn a_mod_declaration_is_not_a_dependency() {
    let (index, root) = fixture();
    let dag = graph(&index, &root, &Options::default()).expect("graph");

    // `lib.rs` says `mod net;` and `net.rs` uses items from `lib.rs`. Counting
    // the module path as an edge makes those two mutually dependent, and every
    // crate's module tree condenses into one node: over ix's workspace that
    // turned 2417 modules into 1052 and put the resulting blobs at the top of
    // the ranking.
    assert!(
        dag.nodes().all(|node| node.members.is_empty()),
        "a three-file crate must not contain a reference cycle: {:?}",
        dag.nodes()
            .filter(|node| !node.members.is_empty())
            .map(|node| node.members.clone())
            .collect::<Vec<_>>(),
    );
}

#[test]
fn crate_granularity_rolls_every_file_into_one_node() {
    let (index, root) = fixture();
    let modules = graph(&index, &root, &Options::default()).expect("graph");
    let crates = graph(
        &index,
        &root,
        &Options {
            granularity: Granularity::Crate,
            include_external: false,
        },
    )
    .expect("graph");

    assert!(
        crates.len() < modules.len(),
        "{} crates from {} modules",
        crates.len(),
        modules.len(),
    );
    assert!(crates.nodes().all(|node| node.kind.as_deref() == Some("crate")));
    // Rolling up must not lose the code: the crate's cost is its files' costs.
    let module_lines: f64 = modules.nodes().filter_map(|node| node.cost).sum();
    let crate_lines: f64 = crates.nodes().filter_map(|node| node.cost).sum();
    assert!(
        (module_lines - crate_lines).abs() < 1.0,
        "{module_lines} lines of modules became {crate_lines} lines of crates",
    );
}

#[test]
fn external_crates_are_left_out_unless_asked_for() {
    let (index, root) = fixture();
    let without = graph(&index, &root, &Options::default()).expect("graph");
    let with = graph(
        &index,
        &root,
        &Options {
            granularity: Granularity::Module,
            include_external: true,
        },
    )
    .expect("graph");

    assert!(without.nodes().all(|node| !node.key.starts_with("external:")));
    assert!(with.len() >= without.len());
}

#[test]
fn the_package_comes_out_of_the_moniker_not_the_path() {
    assert_eq!(
        package_of("rust-analyzer cargo two_sockets 0.1.0 net/Socket#"),
        Some("two_sockets"),
    );
    assert_eq!(package_of("local 3"), None);
}
