"""Type stubs for the native PyO3 module.

Hand-maintained to mirror packages/tui-py/src/. Keep in sync when adding or
changing PyO3 bindings — pyright/mypy use this file to type-check callers.
"""

from __future__ import annotations

import numpy as np
from numpy.typing import NDArray

__version__: str

class StyledCell:
    """A single terminal cell: character plus VT100 styling."""

    @property
    def character(self) -> str: ...
    @property
    def fgcolor(self) -> str | None: ...
    @property
    def bgcolor(self) -> str | None: ...
    @property
    def bold(self) -> bool: ...
    @property
    def italic(self) -> bool: ...
    @property
    def underline(self) -> bool: ...
    @property
    def inverse(self) -> bool: ...
    def __repr__(self) -> str: ...

class FullOutput:
    """Snapshot of both scrollback history and the current viewport."""

    @property
    def scrollback(self) -> list[str]: ...
    @property
    def viewport(self) -> list[str]: ...
    def __repr__(self) -> str: ...

class TuiInstance:
    """A handle to a single spawned TUI process."""

    @property
    def id(self) -> str: ...
    @property
    def command(self) -> str: ...
    @property
    def args(self) -> list[str]: ...
    @property
    def cols(self) -> int: ...
    @property
    def rows(self) -> int: ...
    @property
    def scrollback_limit(self) -> int: ...
    def __repr__(self) -> str: ...

class TuiManager:
    """Manages many concurrent PTY-backed TUI processes."""

    def __init__(self) -> None: ...
    def spawn(
        self,
        command: str,
        args: list[str] | None = ...,
        scrollback_lines: int = ...,
    ) -> TuiInstance: ...
    def list(self) -> list[TuiInstance]: ...
    def write(self, instance: TuiInstance, data: str) -> None: ...
    def read(self, instance: TuiInstance) -> list[str]: ...
    def read_viewport(self, instance: TuiInstance) -> list[str]: ...
    def read_scrollback(self, instance: TuiInstance) -> list[str]: ...
    def read_blocking(
        self, instance: TuiInstance, timeout_ms: int
    ) -> list[str]: ...
    def read_full(self, instance: TuiInstance) -> FullOutput: ...
    def read_chars(self, instance: TuiInstance) -> list[list[str]]: ...
    def read_chars_array(self, instance: TuiInstance) -> NDArray[np.uint32]: ...
    def read_styled_cells(
        self, instance: TuiInstance
    ) -> list[list[StyledCell]]: ...
