"""Type stubs for the native PyO3 module.

Hand-maintained to mirror packages/tui-py/src/. Keep in sync when adding or
changing PyO3 bindings — pyright/mypy use this file to type-check callers.
The async methods return native asyncio-awaitable coroutines produced by
pyo3-async-runtimes; awaiting them drives the underlying tokio future.
"""

from __future__ import annotations

from collections.abc import Awaitable

import numpy as np
from numpy.typing import NDArray

__version__: str

class StyledCell:
    """A single terminal cell: character plus VT100 styling."""

    @property
    def character(self) -> str: ...
    @property
    def fgcolor(self) -> str | None: ...
    @property
    def bgcolor(self) -> str | None: ...
    @property
    def bold(self) -> bool: ...
    @property
    def italic(self) -> bool: ...
    @property
    def underline(self) -> bool: ...
    @property
    def inverse(self) -> bool: ...
    def __repr__(self) -> str: ...

class FullOutput:
    """Snapshot of both scrollback history and the current viewport."""

    @property
    def scrollback(self) -> list[str]: ...
    @property
    def viewport(self) -> list[str]: ...
    def __repr__(self) -> str: ...

class TuiInstance:
    """A handle to a single spawned TUI process. I/O lives on this class."""

    @property
    def id(self) -> str: ...
    @property
    def command(self) -> str: ...
    @property
    def args(self) -> list[str]: ...
    @property
    def cols(self) -> int: ...
    @property
    def rows(self) -> int: ...
    @property
    def scrollback_limit(self) -> int: ...

    # --- sync I/O ---------------------------------------------------------
    def write(self, data: str) -> None: ...
    def read_viewport(self) -> list[str]: ...
    def read_scrollback(self) -> list[str]: ...
    def read_full(self) -> FullOutput: ...
    def read_blocking(self, timeout_ms: int) -> list[str]: ...
    def read_chars_array(self) -> NDArray[np.uint32]: ...
    def read_styled_cells(self) -> list[list[StyledCell]]: ...

    # --- async I/O (native pyo3-async-runtimes coroutines) ----------------
    def write_async(self, data: str) -> Awaitable[None]: ...
    def read_viewport_async(self) -> Awaitable[list[str]]: ...
    def read_scrollback_async(self) -> Awaitable[list[str]]: ...
    def read_full_async(self) -> Awaitable[FullOutput]: ...
    def read_blocking_async(self, timeout_ms: int) -> Awaitable[list[str]]: ...
    def read_chars_array_async(self) -> Awaitable[NDArray[np.uint32]]: ...
    def read_styled_cells_async(self) -> Awaitable[list[list[StyledCell]]]: ...

    def __repr__(self) -> str: ...

class TuiManager:
    """Manages many concurrent PTY-backed TUI processes."""

    def __init__(self) -> None: ...
    def spawn(
        self,
        command: str,
        args: list[str] | None = ...,
        scrollback_lines: int = ...,
    ) -> TuiInstance: ...
    def list(self) -> list[TuiInstance]: ...
