//!Generated unibind Rust client for the `sample` interface.
//!
//!Generated by `unibind-gen rs` (crate `sample-client`); do not edit by hand — regenerate from the engine cdylib's embedded IR instead.
//!
//!# Loading and the handshake
//!
//![`Engine::load`] dlopens the engine cdylib, resolves the handshake symbol first, and compares the engine's IR hash against the one baked into this crate. On any mismatch loading fails with [`LoadError::IrHashMismatch`]; there is no degraded mode. Every other symbol resolves through stabby's structural type-report check, so an ABI drift fails at load time, never at call time.
//!
//!# Allocator contract
//!
//!Values cross the boundary in stabby's default `RustAlloc`, which frees through whichever global allocator the *allocating* side compiled in. Both the engine and this client must therefore keep Rust's default global allocator (no `#[global_allocator]` on either side).
//!
//!# Library lifetime
//!
//!The [`Engine`] keeps the library mapped for its whole lifetime and never exposes unloading: returned values and futures carry vtable pointers into the engine's code, so unloading while any of them is alive would be undefined behavior.
pub mod abi;
pub mod engine;
pub mod error;
pub mod records;
pub use engine::Engine;
pub use engine::{DelayedDoubleFuture, FetchRowFuture};
pub use engine::LabelsStream;
pub use error::{LoadError, SampleError};
pub use records::{Row, Inner};
