# Scaffold-compat seam (#4125): flakes generated by `ix init` before the
# package flattening (#4119) hardcode
# `index + "/packages/nix/ix2nix/import-ix.nix"`, and those flakes float on
# index main, so deleting this path breaks every existing project's eval.
# Forward to the moved implementation and keep nothing else here. New
# consumers use the stable entry point `index.lib.importIxWasm` instead of
# any deep repo path.
# astlog-ignore: no-parent-path -- this seam exists to pin one fixed cross-directory hop
import ../../ix2nix/import-ix.nix
