defmodule IxMcp.Dashboard do
  @moduledoc """
  A live, human-editable document from a cell -- open a served dashboard,
  publish panes into it, read back what a human typed, and get woken when
  they type it. `Dashboard` in the workspace prelude.

      {:ok, url} = Dashboard.open("review")
      :ok = Dashboard.html("review", "diff", "Diff", "<pre>...</pre>")
      :ok = Dashboard.data("review", "stats", "Stats", "gauge", %{files: 12})
      :ok = Dashboard.view("review")     # wake me when a human edits it
      {:ok, doc} = Dashboard.value("review")

  The work happens in the `:dashboard_ex` NIF app (packages/dashboard/ex,
  generated by unibind over the Rust `dashboard-core` hub), loaded at runtime
  from `IX_MCP_DASHBOARD_EX` by `IxMcp.NifApp` -- the `IX_MCP_TUI_EX`
  pattern. Documents are string ids; they stay served until `close/1`.

  `view/1` subscribes *this* session. Every subscribed session gets its own
  durable notification per edit, so a second agent viewing the same document
  is woken too, and a viewer that is disconnected when the edit lands still
  gets it on reconnect. The subscription itself lives in
  `IxMcp.Dashboard.Bridge`, which explains why it has to.

  CRDT payloads (`snapshot/1`, `merge/2`) are plain binaries -- Loro bytes
  cross the unibind boundary natively, no base64 in between.

  ## Who may write what, when several agents share a document

  A document is meant to be co-maintained: several agents contributing to
  one report, and a human editing it. That works because the two halves of
  a pane merge differently -- and one of them does not merge at all:

    * a pane's **text** (an html body, an execution's output) merges, so two
      agents appending concurrently both survive;
    * a pane's **scalars** (`title`, the renderer name, the data payload
      passed to `data/5`) are last-write-wins, so two agents setting the
      same one concurrently silently lose one of them.

  So: **the agent that created a pane owns its scalars, and anyone may
  append to its text.** Nothing enforces this. Enforcing it would make the
  thing this document exists for -- three agents reporting different
  numbers for the same measurement, which a reader then weighs -- impossible
  to express.

  What makes that safe to leave unenforced is that a violation is visible
  rather than silent: the document records who last wrote each key, so a
  title that changed hands says so on the pane itself. If you are correcting
  another agent's finding, prefer adding your own pane, or appending to the
  text, over overwriting their title.
  """

  alias IxMcp.Dashboard.Bridge
  alias IxMcp.Session

  # The generated namespace, referenced as an atom so compiling this app
  # never needs the NIF app present (it is loaded at runtime).
  @mod :"Elixir.DashboardEx"
  @app :dashboard_ex
  @env_var "IX_MCP_DASHBOARD_EX"

  @typedoc "A document id, as passed to `open/2`."
  @type doc :: String.t()

  @typedoc "The `%DashboardEx.DashboardError{}` struct (variant + message) or a load failure."
  @type error :: {:error, struct() | String.t()}

  @doc """
  Open `doc` and serve it on loopback; returns the browser URL. Options:
  `port:` (default 0, meaning any free port -- the returned URL names the
  one it got).
  """
  @spec open(doc(), keyword()) :: {:ok, String.t()} | error()
  def open(doc, opts \\ []) do
    call(:open, [doc, Keyword.get(opts, :port, 0)])
  end

  @doc "Stop serving `doc` and forget it; its id stops resolving."
  @spec close(doc()) :: :ok | error()
  def close(doc), do: call(:close, [doc])

  @doc "Ids of every open document in this kernel."
  @spec list() :: [doc()] | {:error, String.t()}
  def list, do: call(:list, [])

  @doc "The browser URL of an open document."
  @spec url(doc()) :: {:ok, String.t()} | error()
  def url(doc), do: call(:url, [doc])

  @doc "Publish (or replace) an HTML pane. The markup is mounted sandboxed."
  @spec html(doc(), String.t(), String.t(), String.t()) :: :ok | error()
  def html(doc, pane, title, markup), do: call(:set_html, [doc, pane, title, markup])

  @doc """
  Publish (or replace) a data pane: `data` is any JSON-encodable term,
  rendered by the named frontend `renderer` (an unknown name falls back to a
  generic tree).
  """
  @spec data(doc(), String.t(), String.t(), String.t(), term()) :: :ok | error()
  def data(doc, pane, title, renderer, data) do
    call(:set_data, [doc, pane, title, renderer, JSON.encode!(data)])
  end

  @doc "Remove a pane this kernel published. Unknown pane ids are a no-op."
  @spec drop(doc(), String.t()) :: :ok | error()
  def drop(doc, pane), do: call(:drop_pane, [doc, pane])

  @doc "Pane ids this kernel has published into `doc`."
  @spec panes(doc()) :: {:ok, [String.t()]} | error()
  def panes(doc), do: call(:panes, [doc])

  @doc """
  The whole document as decoded JSON -- the panes plus whatever containers a
  browser created. This is how a woken agent reads what a human typed.
  """
  @spec value(doc()) :: {:ok, term()} | error()
  def value(doc) do
    with {:ok, json} <- call(:value, [doc]) do
      JSON.decode(json)
    end
  end

  @doc "A Loro snapshot of `doc` as a binary, oplog included, so a peer can replay it."
  @spec snapshot(doc()) :: {:ok, binary()} | error()
  def snapshot(doc), do: call(:snapshot, [doc])

  @doc """
  Merge a peer's Loro update (a binary) into `doc` and fan it out to every
  connected browser. `{:ok, "applied"}` means every op landed;
  `{:ok, "pending"}` means the update depends on history this document does
  not have, so the edit is recorded but invisible until the rest arrives --
  answer with the missing range rather than treating it as done.
  """
  @spec merge(doc(), binary()) :: {:ok, String.t()} | error()
  def merge(doc, update), do: call(:merge, [doc, update])

  @doc """
  Pull the hub's current state forward now instead of waiting for the next
  poll tick. Every read already does this; it is exported so a caller that
  just told a browser to write can read without racing it.
  """
  @spec sync(doc()) :: :ok | error()
  def sync(doc), do: call(:sync, [doc])

  @doc """
  Wake this session whenever `doc` changes. Every viewing session gets its
  own durable notification, and one that is disconnected when the edit lands
  gets it on reconnect.
  """
  @spec view(doc()) :: :ok | {:error, String.t()}
  def view(doc), do: Bridge.view(doc, Session.ids().session_id)

  @doc "Stop waking this session on `doc`."
  @spec unview(doc()) :: :ok
  def unview(doc), do: Bridge.unview(doc, Session.ids().session_id)

  @doc "Session ids currently being woken by `doc`."
  @spec viewers(doc()) :: [integer()]
  def viewers(doc), do: Bridge.viewers(doc)

  defp call(fun, args) do
    with :ok <- IxMcp.NifApp.ensure_loaded(@mod, @app, @env_var) do
      apply(@mod, fun, args)
    end
  end
end
