defmodule IxMcp.Gmail do
  @moduledoc """
  Gmail from a cell -- send, search, and read the signed-in user's mail.
  `Gmail` in the workspace prelude.

      {:ok, sent} = Gmail.send("dev@ix.dev", "subject", "body text")
      {:ok, hits} = Gmail.search("from:github newer_than:7d", limit: 5)
      {:ok, message} = Gmail.show(hd(hits).id)
      Gmail.status()

  The work happens in the `:gmail_ex` NIF app (packages/google/gmail/ex,
  generated by unibind over the Rust `google-gmail` client), loaded at
  runtime from `IX_MCP_GMAIL_EX` by `IxMcp.NifApp` -- the `IX_MCP_TUI_EX`
  pattern. Auth is the shared Google grant (`~/.config/google/token.json`,
  minted once by `gmail auth` on the host) plus the team OAuth client in
  `GOOGLE_OAUTH_CLIENT_ID`/`GOOGLE_OAUTH_CLIENT_SECRET`; tokens stay inside
  the NIF and never appear in a cell.
  """

  # The generated namespace, referenced as an atom so compiling this app
  # never needs the NIF app present (it is loaded at runtime).
  @gmail_ex :"Elixir.GmailEx"
  @app :gmail_ex
  @env_var "IX_MCP_GMAIL_EX"

  @typedoc "The `%GmailEx.GmailError{}` struct (variant + message) or a load failure."
  @type error :: {:error, struct() | String.t()}

  @doc """
  Compose and send a plain-text message; `{:ok, sent}` carries the new
  message's `id` and `thread_id`.

  `to` is one address or a comma-separated list. Options: `cc:` and `bcc:`
  (same shape as `to`), `html:` (an HTML body sent alongside the text),
  `thread:` (reply into an existing thread id; the subject must still
  match the thread's).
  """
  @spec send(String.t(), String.t(), String.t(), keyword()) :: {:ok, struct()} | error()
  def send(to, subject, body_text, opts \\ []) do
    call(:send, [to, subject, body_text, opts[:cc], opts[:bcc], opts[:html], opts[:thread]])
  end

  @doc """
  Search messages with the Gmail query syntax (`from:`, `to:`, `label:`,
  `newer_than:`, ...); `{:ok, summaries}` (id, thread_id, date, from,
  subject, snippet), most recent first. Options: `limit:` (default 10;
  each hit costs one metadata fetch).
  """
  @spec search(String.t(), keyword()) :: {:ok, [struct()]} | error()
  def search(query, opts \\ []) do
    call(:search, [query, Keyword.get(opts, :limit, 10)])
  end

  @doc "One message by id: headers, labels, snippet, and the decoded text body."
  @spec show(String.t()) :: {:ok, struct()} | error()
  def show(id), do: call(:show, [id])

  @doc """
  Whether this kernel can talk to Gmail: client credentials present, a
  grant stored, and which required scopes it covers. Data (a signed-out
  kernel is not an error here), and the tokens themselves never surface.
  """
  @spec status() :: struct() | {:error, String.t()}
  def status, do: call(:status, [])

  defp call(fun, args) do
    with :ok <- IxMcp.NifApp.ensure_loaded(@gmail_ex, @app, @env_var) do
      apply(@gmail_ex, fun, args)
    end
  end
end
