defmodule IxMcp.TuiLocal do
  @moduledoc """
  Drive a local PTY program from a cell -- spawn a real terminal child
  (an editor, a pager, a REPL), send it keystrokes, and read the rendered
  screen. `TuiLocal` in the workspace prelude; the local sibling of
  `Tui.act/2..3`, which drives *federated* resources on other hosts.

      {:ok, term} = TuiLocal.spawn("vim", ["notes.txt"], rows: 30, cols: 100)
      :ok = TuiLocal.send(term, "ihello")
      :ok = TuiLocal.send_key(term, "esc")
      {:ok, screen} = TuiLocal.wait_for(term, "hello")
      :ok = TuiLocal.close(term)

  The work happens in the `:tui_ex` NIF app (packages/tui/ex, generated by
  unibind over the Rust `tui` PTY driver). That app is not a mix dep: the
  release bakes its store path into `IX_MCP_TUI_EX` (the same pattern as
  `IX_MCP_GH`) and this module loads it onto the code path on first use, so
  the kernel release and the binding ship independently. Terminals are
  string ids from `spawn/3`; they stay alive until `close/1`.
  """

  # The generated namespace, referenced as an atom so compiling this app
  # never needs the NIF app present (it is loaded at runtime).
  @tui_ex :"Elixir.TuiEx"
  @app :tui_ex
  @env_var "IX_MCP_TUI_EX"

  @typedoc "A terminal id, as returned by `spawn/3`."
  @type terminal :: String.t()

  @typedoc "The `%TuiEx.TuiError{}` struct (variant + message) or a load failure."
  @type error :: {:error, struct() | String.t()}

  @doc """
  Spawn `command` with `args` on a fresh PTY; returns the terminal id.

  Options: `rows:` (default 24), `cols:` (default 80). The child sees a
  real terminal (`TERM=xterm-256color`).
  """
  @spec spawn(String.t(), [String.t()], keyword()) :: {:ok, terminal()} | error()
  def spawn(command, args \\ [], opts \\ []) do
    call(:spawn, [command, args, Keyword.get(opts, :rows, 24), Keyword.get(opts, :cols, 80)])
  end

  @doc """
  Send literal text (escape sequences included). Arrows are DECCKM-aware in
  the driver, so cursor bytes reach full-screen programs correctly.
  """
  @spec send(terminal(), String.t()) :: :ok | error()
  def send(term, data), do: call(:send, [term, data])

  @doc """
  Send one named key: `enter`, `esc`, `tab`, `backspace`, `delete`, arrows
  (`up`/`down`/`left`/`right`), `home`/`end`, `page_up`/`page_down`,
  `f1`..`f12`, or a `ctrl+<letter>` / `alt+<char>` chord.
  """
  @spec send_key(terminal(), String.t()) :: :ok | error()
  def send_key(term, key), do: call(:send_key, [term, key])

  @doc "The rendered screen as plain text, one line per viewport row."
  @spec snapshot(terminal()) :: {:ok, String.t()} | error()
  def snapshot(term), do: call(:snapshot, [term])

  @doc """
  Poll the screen until `pattern` appears as a substring; returns the
  matching screen text, or a `:timeout`-variant error after `timeout_ms`.
  """
  @spec wait_for(terminal(), String.t(), non_neg_integer()) :: {:ok, String.t()} | error()
  def wait_for(term, pattern, timeout_ms \\ 5_000),
    do: call(:wait_for, [term, pattern, timeout_ms])

  @doc "Whether the child is still running (`{:ok, boolean}`)."
  @spec alive?(terminal()) :: {:ok, boolean()} | error()
  def alive?(term), do: call(:is_alive, [term])

  @doc "The exit code: `{:ok, nil}` while running or after a signal kill."
  @spec exit_code(terminal()) :: {:ok, integer() | nil} | error()
  def exit_code(term), do: call(:exit_code, [term])

  @doc "Block until the child exits; `{:ok, code}` or a `:timeout` error."
  @spec wait(terminal(), non_neg_integer()) :: {:ok, integer() | nil} | error()
  def wait(term, timeout_ms \\ 5_000), do: call(:wait, [term, timeout_ms])

  @doc "Resize the terminal (delivers SIGWINCH to the child)."
  @spec resize(terminal(), pos_integer(), pos_integer()) :: :ok | error()
  def resize(term, rows, cols), do: call(:resize, [term, rows, cols])

  @doc "Force-terminate with SIGKILL; the screen stays readable until `close/1`."
  @spec kill(terminal()) :: :ok | error()
  def kill(term), do: call(:kill, [term])

  @doc "Kill the child and drop the terminal; its id stops resolving."
  @spec close(terminal()) :: :ok | error()
  def close(term), do: call(:close, [term])

  @doc "Ids of every live terminal in this kernel."
  @spec list() :: [terminal()] | error()
  def list, do: call(:list, [])

  # `apply/3` on the atom-referenced module: a direct `TuiEx.spawn(...)`
  # would warn (module unavailable at compile time) and this app compiles
  # warnings-as-errors.
  defp call(fun, args) do
    with :ok <- IxMcp.NifApp.ensure_loaded(@tui_ex, @app, @env_var) do
      apply(@tui_ex, fun, args)
    end
  end
end
