//! Render the `mix.exs` of the package the host modules ship in.
//!
//! Every unibind Elixir binding is the same mix project: one OTP app whose
//! name and namespace the interface already fixes, no hex deps (the whole of
//! `lib/` is generated and the checks build offline), and no application
//! callback module. Hand-writing that per binding produced byte-identical
//! copies in every binding crate that could only drift, so it is derived from
//! the same interface the modules under `lib/` are.

use unibind_core::ir;

use crate::names;

/// Version of every generated mix project.
///
/// Bindings are consumed by path from a nix derivation rather than published
/// to hex, so nothing resolves against this; it exists because `mix` requires
/// the key. Each binding's `default.nix` pins the same string for the
/// derivation it builds.
const VERSION: &str = "0.1.0";

/// The oldest Elixir the generated modules compile on. `~>` rather than an
/// exact pin: which toolchain a binding is built against is the nix
/// expression's choice, and this only rules out a compiler too old for the
/// syntax the generated code uses.
const ELIXIR_REQUIREMENT: &str = "~> 1.18";

/// Render `mix.exs`. The output is `mix format`-clean: the binding suites run
/// `mix format --check-formatted` over the whole package, generated files
/// included.
pub fn render(interface: &ir::Interface) -> String {
    let ns = names::ns_name(interface);
    let app = names::ns_snake(interface);
    format!(
        r#"defmodule {ns}.MixProject do
  use Mix.Project

  # Generated by unibind's ex backend, along with everything under lib/. Zero
  # hex deps on purpose: the checks build offline, so there is no
  # fixed-output deps pin to keep current.
  def project do
    [
      app: :{app},
      version: "{VERSION}",
      elixir: "{ELIXIR_REQUIREMENT}",
      start_permanent: false,
      deps: []
    ]
  end

  def application do
    [extra_applications: []]
  end
end
"#
    )
}
