#!/usr/bin/env python3
"""Run one Nix build against explicitly selected protected builders."""

from __future__ import annotations

import argparse
import contextlib
import json
import os
import signal
import subprocess
import sys
import time
from collections.abc import Sequence
from dataclasses import dataclass
from datetime import UTC, datetime
from pathlib import Path
from types import FrameType
from typing import NoReturn


class AuthorizationError(Exception):
    """The requested protected-builder authorization is invalid."""


class PolicyError(Exception):
    """The installed protected-builder policy is invalid."""


class Interrupted(Exception):
    """A signal interrupted the authorized build."""

    def __init__(self, signum: int) -> None:
        super().__init__(signum)
        self.signum = signum


@dataclass(frozen=True)
class Builder:
    """One named, pre-rendered Nix build-machine record."""

    name: str
    machine: str


@dataclass(frozen=True)
class Policy:
    """Installed policy for protected builder use."""

    max_ttl_seconds: int
    cancel_grace_seconds: int
    verify_timeout_seconds: int
    builders: dict[str, Builder]


@dataclass(frozen=True)
class Arguments:
    """Validated command arguments."""

    policy_path: Path
    nix_path: Path
    logger_path: Path
    builder_names: tuple[str, ...]
    reason: str
    ttl_seconds: int
    build_args: tuple[str, ...]


@dataclass(frozen=True)
class BuildIdentity:
    """Stable fields from one active daemon build status row."""

    drv_path: str | None
    store_path: str | None
    pid: int | None
    start_time: int | None
    uid: int | None


def _mapping(value: object, label: str) -> dict[str, object]:
    if not isinstance(value, dict):
        raise PolicyError(f"{label} must be an object")
    result: dict[str, object] = {}
    for key, item in value.items():
        if not isinstance(key, str):
            raise PolicyError(f"{label} keys must be strings")
        result[key] = item
    return result


def _string(value: object, label: str) -> str:
    if not isinstance(value, str) or not value:
        raise PolicyError(f"{label} must be a nonempty string")
    return value


def _line(value: object, label: str) -> str:
    result = _string(value, label)
    if "\n" in result or "\r" in result:
        raise PolicyError(f"{label} must be a single line")
    return result


def _optional_string(value: object, label: str) -> str | None:
    if value is None:
        return None
    return _string(value, label)


def _positive_int(value: object, label: str) -> int:
    if isinstance(value, bool) or not isinstance(value, int) or value <= 0:
        raise PolicyError(f"{label} must be a positive integer")
    return value


def _optional_int(value: object, label: str) -> int | None:
    if value is None:
        return None
    if isinstance(value, bool) or not isinstance(value, int):
        raise PolicyError(f"{label} must be an integer or null")
    return value


def _builder(value: object, label: str) -> Builder:
    fields = _mapping(value, label)
    return Builder(
        name=_string(fields.get("name"), f"{label}.name"),
        machine=_line(fields.get("machine"), f"{label}.machine"),
    )


def load_policy(path: Path) -> Policy:
    """Load and validate a policy generated by the Darwin module."""
    try:
        with path.open(encoding="utf-8") as handle:
            raw: object = json.load(handle)
    except (OSError, json.JSONDecodeError) as error:
        raise PolicyError(f"cannot read {path}: {error}") from error

    fields = _mapping(raw, "policy")
    if fields.get("version") != 1:
        raise PolicyError("policy.version must be 1")
    raw_builders = _mapping(fields.get("builders"), "policy.builders")
    builders = {
        name: _builder(value, f"policy.builders.{name}")
        for name, value in raw_builders.items()
    }
    for name, builder in builders.items():
        if builder.name != name:
            raise PolicyError(
                f"policy builder key {name!r} does not match record name {builder.name!r}"
            )
    return Policy(
        max_ttl_seconds=_positive_int(
            fields.get("maxTtlSeconds"), "policy.maxTtlSeconds"
        ),
        cancel_grace_seconds=_positive_int(
            fields.get("cancelGraceSeconds"), "policy.cancelGraceSeconds"
        ),
        verify_timeout_seconds=_positive_int(
            fields.get("verifyTimeoutSeconds"), "policy.verifyTimeoutSeconds"
        ),
        builders=builders,
    )


def build_command(
    nix_path: Path, builders: Sequence[Builder], args: Sequence[str]
) -> list[str]:
    """Render argv for a build that cannot fall back to the local machine."""
    machines = "\n".join(builder.machine for builder in builders)
    return [
        str(nix_path),
        "--option",
        "builders",
        machines,
        "--option",
        "max-jobs",
        "0",
        "build",
        *args,
    ]


def _reject_builder_overrides(args: Sequence[str]) -> None:
    forbidden = {"--builders", "--max-jobs", "-j"}
    for index, item in enumerate(args):
        if item in forbidden or any(
            item.startswith(f"{option}=") for option in forbidden
        ):
            raise AuthorizationError(
                f"build arguments must not override {item.split('=', 1)[0]}"
            )
        if (
            item == "--option"
            and index + 1 < len(args)
            and args[index + 1] in {"builders", "max-jobs"}
        ):
            raise AuthorizationError(
                f"build arguments must not override {args[index + 1]}"
            )


def parse_arguments(argv: Sequence[str]) -> Arguments:
    """Parse the injected runtime paths and public authorization flags."""
    if len(argv) < 3:
        raise AuthorizationError("installed command is missing its runtime paths")
    policy_path = Path(argv[0])
    nix_path = Path(argv[1])
    logger_path = Path(argv[2])
    parser = argparse.ArgumentParser(
        prog="protected-nix-build",
        description=(
            "Run `nix build` only on explicitly selected protected builders. "
            "Place build flags after `--`."
        ),
    )
    parser.add_argument("--builder", action="append", required=True)
    parser.add_argument("--reason", required=True)
    parser.add_argument("--ttl-seconds", type=int, required=True)
    parser.add_argument("build_args", nargs=argparse.REMAINDER)
    namespace = parser.parse_args(argv[3:])

    builder_names: list[str] = namespace.builder
    reason: str = namespace.reason.strip()
    ttl_seconds: int = namespace.ttl_seconds
    build_args: list[str] = namespace.build_args

    if not reason:
        raise AuthorizationError("--reason must contain nonwhitespace text")
    if len(reason) > 512:
        raise AuthorizationError("--reason must be at most 512 characters")
    if ttl_seconds <= 0:
        raise AuthorizationError("--ttl-seconds must be positive")
    if len(builder_names) != len(set(builder_names)):
        raise AuthorizationError("--builder values must be unique")
    _reject_builder_overrides(build_args)
    return Arguments(
        policy_path=policy_path,
        nix_path=nix_path,
        logger_path=logger_path,
        builder_names=tuple(builder_names),
        reason=reason,
        ttl_seconds=ttl_seconds,
        build_args=tuple(build_args),
    )


def _audit(
    logger_path: Path, event: str, arguments: Arguments, **extra: object
) -> None:
    record: dict[str, object] = {
        "builders": arguments.builder_names,
        "event": event,
        "reason": arguments.reason,
        "timestamp": datetime.now(UTC).isoformat(),
        "ttlSeconds": arguments.ttl_seconds,
        "uid": os.getuid(),
        **extra,
    }
    message = json.dumps(record, separators=(",", ":"), sort_keys=True)
    try:
        subprocess.run(
            [str(logger_path), "-t", "protected-nix-build", message],
            check=True,
            capture_output=True,
            text=True,
        )
    except (OSError, subprocess.CalledProcessError) as error:
        raise AuthorizationError(
            f"cannot write the authorization audit record: {error}"
        ) from error
    print(message, file=sys.stderr, flush=True)


def active_builds(nix_path: Path) -> set[BuildIdentity]:
    """Read the patched Nix daemon's machine-wide build status."""
    command = [
        str(nix_path),
        "--option",
        "builders",
        "",
        "--option",
        "max-jobs",
        "0",
        "store",
        "builds",
        "--json",
    ]
    try:
        completed = subprocess.run(command, check=True, capture_output=True, text=True)
        raw: object = json.loads(completed.stdout)
    except (OSError, subprocess.CalledProcessError, json.JSONDecodeError) as error:
        raise AuthorizationError(
            f"cannot verify daemon cancellation with `nix store builds --json`: {error}"
        ) from error
    if not isinstance(raw, list):
        raise PolicyError("`nix store builds --json` must return an array")

    builds: set[BuildIdentity] = set()
    for index, value in enumerate(raw):
        row = _mapping(value, f"active build {index}")
        builds.add(
            BuildIdentity(
                drv_path=_optional_string(
                    row.get("drvPath"), f"active build {index}.drvPath"
                ),
                store_path=_optional_string(
                    row.get("storePath"), f"active build {index}.storePath"
                ),
                pid=_optional_int(row.get("pid"), f"active build {index}.pid"),
                start_time=_optional_int(
                    row.get("startTime"), f"active build {index}.startTime"
                ),
                uid=_optional_int(row.get("uid"), f"active build {index}.uid"),
            )
        )
    return builds


def _group_exists(process_group: int) -> bool:
    try:
        os.killpg(process_group, 0)
    except ProcessLookupError:
        return False
    except PermissionError:
        return True
    return True


def terminate_process_group(
    process: subprocess.Popen[bytes], grace_seconds: int
) -> None:
    """Terminate the Nix client and every process it started."""
    process_group = process.pid
    with contextlib.suppress(ProcessLookupError):
        os.killpg(process_group, signal.SIGTERM)

    deadline = time.monotonic() + grace_seconds
    while _group_exists(process_group) and time.monotonic() < deadline:
        process.poll()
        time.sleep(0.05)
    if _group_exists(process_group):
        with contextlib.suppress(ProcessLookupError):
            os.killpg(process_group, signal.SIGKILL)
    try:
        process.wait(timeout=1)
    except subprocess.TimeoutExpired as error:
        raise AuthorizationError("the Nix client survived SIGKILL") from error


def verify_cancelled(
    nix_path: Path,
    baseline: set[BuildIdentity],
    timeout_seconds: int,
) -> None:
    """Require two stable polls with no daemon work added by this authorization."""
    deadline = time.monotonic() + timeout_seconds
    stable_polls = 0
    remaining: set[BuildIdentity] = set()
    while time.monotonic() <= deadline:
        remaining = {
            build
            for build in active_builds(nix_path) - baseline
            if build.uid in {None, os.getuid()}
        }
        stable_polls = stable_polls + 1 if not remaining else 0
        if stable_polls >= 2:
            return
        time.sleep(0.1)
    details = ", ".join(
        sorted(
            build.drv_path or build.store_path or f"pid {build.pid}"
            for build in remaining
        )
    )
    raise AuthorizationError(
        "daemon work remained after cancellation" + (f": {details}" if details else "")
    )


def _raise_interrupted(signum: int, _frame: FrameType | None) -> NoReturn:
    raise Interrupted(signum)


def cancel(
    process: subprocess.Popen[bytes],
    arguments: Arguments,
    policy: Policy,
    baseline: set[BuildIdentity],
    event: str,
    **extra: object,
) -> None:
    """Stop the client, verify daemon cleanup, and record the terminal state."""
    try:
        terminate_process_group(process, policy.cancel_grace_seconds)
        verify_cancelled(arguments.nix_path, baseline, policy.verify_timeout_seconds)
    except (AuthorizationError, PolicyError) as error:
        _audit(
            arguments.logger_path,
            "cancellation_unverified",
            arguments,
            error=str(error),
            **extra,
        )
        raise
    _audit(arguments.logger_path, event, arguments, **extra)


def run(arguments: Arguments, policy: Policy) -> int:
    """Authorize, run, and account for one protected build."""
    if arguments.ttl_seconds > policy.max_ttl_seconds:
        raise AuthorizationError(
            f"--ttl-seconds exceeds the policy maximum of {policy.max_ttl_seconds}"
        )
    unknown = [name for name in arguments.builder_names if name not in policy.builders]
    if unknown:
        raise AuthorizationError(f"unknown protected builder: {', '.join(unknown)}")
    selected = [policy.builders[name] for name in arguments.builder_names]
    baseline = active_builds(arguments.nix_path)
    _audit(arguments.logger_path, "authorized", arguments)

    previous_handlers = {
        signum: signal.signal(signum, _raise_interrupted)
        for signum in (signal.SIGINT, signal.SIGTERM)
    }
    process: subprocess.Popen[bytes] | None = None
    try:
        try:
            process = subprocess.Popen(
                build_command(arguments.nix_path, selected, arguments.build_args),
                start_new_session=True,
            )
        except OSError as error:
            _audit(
                arguments.logger_path,
                "launch_failed",
                arguments,
                error=str(error),
            )
            raise AuthorizationError(f"cannot start Nix: {error}") from error
        try:
            exit_code = process.wait(timeout=arguments.ttl_seconds)
        except subprocess.TimeoutExpired:
            cancel(process, arguments, policy, baseline, "timed_out")
            return 124
        except Interrupted as interrupted:
            cancel(
                process,
                arguments,
                policy,
                baseline,
                "interrupted",
                signal=interrupted.signum,
            )
            return 128 + interrupted.signum
        _audit(arguments.logger_path, "completed", arguments, exitCode=exit_code)
        return exit_code
    finally:
        for signum, handler in previous_handlers.items():
            signal.signal(signum, handler)
        if process is not None and process.poll() is None:
            terminate_process_group(process, policy.cancel_grace_seconds)


def main(argv: Sequence[str] | None = None) -> int:
    """Command entry point."""
    try:
        arguments = parse_arguments(sys.argv[1:] if argv is None else argv)
        return run(arguments, load_policy(arguments.policy_path))
    except (AuthorizationError, PolicyError) as error:
        print(f"protected-nix-build: {error}", file=sys.stderr)
        return 2


if __name__ == "__main__":
    raise SystemExit(main())
