//! The repo lint gate: each stage's implementation (`lint-stage <stage>`)
//! plus the `--json` collector the `lint` front-end uses. The dag spec both
//! paths run is generated by default.nix, so the nix side owns the stage
//! list; `Stage` mirrors it and the `stage-list` passthru test pins the two
//! together.

pub mod spec;
pub mod stage;
pub mod walk;
