suites += {
  'name' : 'local-overlay-store',
  'deps' : [
    register_realisation_tester,
  ],
  'tests' : [
    'check-post-init.sh',
    'redundant-add.sh',
    'build.sh',
    'bad-uris.sh',
    'add-lower.sh',
    'delete-refs.sh',
    'delete-duplicate.sh',
    'gc.sh',
    'verify.sh',
    'optimise.sh',
    'stale-file-handle.sh',
    'lower-gains-output.sh',
    'lower-gains-invisible-path.sh',
    'lower-only-realisation.sh',
  ],
  'workdir' : meson.current_source_dir(),
}
