# The suite plus mix.exs; lib/ is generated by unibind-gen and not formatted.
# mix.exs is generated too, and stays here so the check proves the generator
# emits canonical Elixir.
[
  inputs: ["mix.exs", "test/**/*.exs"]
]
