defmodule Plumb.MixProject do
  use Mix.Project

  # Zero hex deps on purpose: the check builds offline and everything under
  # lib/ is generated by `unibind-gen ex` from the built NIF's embedded IR.
  def project do
    [
      app: :plumb,
      version: "0.1.0",
      elixir: "~> 1.18",
      start_permanent: false,
      deps: []
    ]
  end

  def application do
    [extra_applications: []]
  end
end
