{
  lib,
  pkgs,
  paths,
}:
let
  /**
    Fetch a static artifact (mod jar, plugin, server) by URL + SRI hash.

    Hashes live next to URLs in the consuming catalog rather than in flake
    inputs, so a routine mod bump touches one JSON file and not
    `flake.lock`. Accepts and ignores extra catalog keys.
  */
  mkArtifact = { url, hash, ... }: pkgs.fetchurl { inherit url hash; };

  /**
    Enrich every entry of a `{ slug = { url, hash, ... }; ... }` catalog
    with a `src` attribute pointing at the fetched store path.
  */
  attachArtifactSources = lib.mapAttrs (_: entry: entry // { src = mkArtifact entry; });

  paperServers = {
    "26.1.2" = {
      build = 64;
      src = mkArtifact {
        url = "https://fill-data.papermc.io/v1/objects/830d4eb5c15cbd802a9ec9f2f54eaaaeb9511958339aec983fd0c88bad21d940/paper-26.1.2-64.jar";
        hash = "sha256-gw1OtcFcvYAqnsny9U6qrrlRGVgzmuyYP9DIi60h2UA=";
      };
    };

    "1.21.11" = {
      build = 69;
      src = mkArtifact {
        url = "https://api.papermc.io/v2/projects/paper/versions/1.21.11/builds/69/downloads/paper-1.21.11-69.jar";
        hash = "sha256-zzdPKvnXHfzHU0Pze3IqerywkcV0ExuV47E8b8LLj64=";
      };
    };
  };

  velocityServers = {
    "3.4.0-SNAPSHOT" = {
      build = 559;
      src = mkArtifact {
        url = "https://api.papermc.io/v2/projects/velocity/versions/3.4.0-SNAPSHOT/builds/559/downloads/velocity-3.4.0-SNAPSHOT-559.jar";
        hash = "sha256-zMSfcXUeziZWjTR2OS1hMMi0Py5fOogxMyW5J4pSur0=";
      };
    };
  };

  /**
    Per-version Minecraft artifact catalogs generated by `tools/update-mods.py`
    from a manifest directory such as `<paths.minecraftMods>` or
    `<paths.minecraftPaperPlugins>`.

    The bare-JSON catalog (slug -> `{ url, hash }`) is enriched into
    `{ url, hash, src }` so callers can pass it straight to
    `services.minecraft.modCatalog` or `services.minecraft.pluginCatalog`.
    Presets and examples consume these catalogs by name; to add an artifact,
    edit the relevant manifest and run `nix run .#update-mods`.
  */
  generatedCatalogs =
    root:
    let
      gameVersions = lib.pipe root [
        builtins.readDir
        (lib.filterAttrs (
          name: type: type == "regular" && lib.hasSuffix ".json" name && name != "manifest.json"
        ))
        builtins.attrNames
        (map (lib.removeSuffix ".json"))
      ];
      catalogFor =
        ver: attachArtifactSources (builtins.fromJSON (builtins.readFile (root + "/${ver}.json")));
    in
    lib.genAttrs gameVersions catalogFor;

  modCatalogs = generatedCatalogs paths.minecraftMods;
  paperPluginCatalogs = generatedCatalogs paths.minecraftPaperPlugins;
  velocityPluginCatalogs = generatedCatalogs paths.minecraftVelocityPlugins;

  # Minecraft version of the default variant declared in
  # `images/games/minecraft/versions.nix`. Lets per-loader fallback catalogs
  # follow the image default instead of pinning a literal version that silently
  # rots once the default moves.
  defaultMinecraftVersion =
    let
      versionsModule = import (paths.images + "/games/minecraft/versions.nix") {
        inherit lib;
      };
    in
    versionsModule.${versionsModule.default}.services.minecraft.version;

  # Fabric meta serves every server jar from the same loader+installer pair;
  # only the Minecraft version moves. Keep the pair in one place so a Fabric
  # bump touches one field instead of every URL string.
  fabricLoaderVersion = "0.19.2";
  fabricInstallerVersion = "1.1.1";
  fabricServerUrl =
    mcVer:
    "https://meta.fabricmc.net/v2/versions/loader/${mcVer}/${fabricLoaderVersion}/${fabricInstallerVersion}/server/jar";
  fabricServerHashes = {
    "26.2-snapshot-5" = "sha256-IZctWQu9VH4Z5lU/VcEzvPGLfW8boOAXtCaQlKXyA5k=";
    "26.2-snapshot-6" = "sha256-J4zGg7YlrHmYBsagTr+x2ZcAgOvj5vr/8iVgwMVG/e0=";
    "26.1.2" = "sha256-6RvRm5/w4ExXhD5iTS9U0KPjmgSMr8pejiDrmENEXb0=";
    "1.21.11" = "sha256-xDK1HU7Xwbr0Z7pw7Dtdtob0zvlfq9pZ9J4O32u4jBc=";
  };
  fabricServers = lib.mapAttrs' (mcVer: hash: {
    name = "${mcVer}-fabric";
    value = mkArtifact {
      url = fabricServerUrl mcVer;
      inherit hash;
    };
  }) fabricServerHashes;
in
{
  inherit attachArtifactSources;
  minecraft = {
    inherit
      modCatalogs
      paperPluginCatalogs
      paperServers
      velocityPluginCatalogs
      velocityServers
      ;
    paperPluginCatalog =
      if builtins.hasAttr defaultMinecraftVersion paperPluginCatalogs then
        paperPluginCatalogs.${defaultMinecraftVersion}
      else
        throw "ix.lib.artifacts.minecraft.paperPluginCatalog: no Paper plugin catalog generated for Minecraft ${defaultMinecraftVersion} (the default in images/games/minecraft/versions.nix). Run `nix run .#update-mods -- --manifest images/games/minecraft/plugins/paper/manifest.json --version ${defaultMinecraftVersion}` and commit the result.";
    # Velocity plugins are cross-Minecraft-version: `velocityPluginCatalog`
    # is the unversioned default surfaced to modules. Per-version overrides
    # can still come from `velocityPluginCatalogs.<version>` if added.
    velocityPluginCatalog = velocityPluginCatalogs.common or { };
    servers = fabricServers // {
      "1.21.11-paper" = paperServers."1.21.11".src;
      "26.1.2-paper" = paperServers."26.1.2".src;
    };
  };
}
