import { svelte } from '@sveltejs/vite-plugin-svelte';
import { defineConfig } from 'vite';

// A standalone site: `vite dev` / `vite build` / `vite preview` all run on their
// own. It reads its data from a real SQLite file (public/tasks.sqlite) in the
// browser via sql.js, generated by the `tasks` Python helper.
export default defineConfig({
  plugins: [svelte()],
  // sql.js ships a wasm asset; keep it un-inlined so the browser fetches it.
  assetsInclude: ['**/*.wasm'],
});
