{
  lib,
  pkgs,
  paths,
}:
let
  /**
    Fetch a static artifact (mod jar, plugin, server) by URL + SRI hash.

    Hashes live next to URLs in the consuming catalog rather than in flake
    inputs, so a routine mod bump touches one JSON file and not
    `flake.lock`. Accepts and ignores extra catalog keys.
  */
  mkArtifact = { url, hash, ... }: pkgs.fetchurl { inherit url hash; };

  /**
    Enrich every entry of a `{ slug = { url, hash, ... }; ... }` catalog
    with a `src` attribute pointing at the fetched store path.
  */
  attachArtifactSources = lib.mapAttrs (_: entry: entry // { src = mkArtifact entry; });

  /**
    Per-version Minecraft artifact catalogs generated by `packages/minecraft/tools/update-mods.py`
    from a manifest directory such as `<paths.minecraftMods>` or
    `<paths.minecraftPaperPlugins>`.

    The bare-JSON catalog (slug -> `{ url, hash }`) is enriched into
    `{ url, hash, src }` so callers can pass it straight to
    `services.minecraft.modCatalog` or `services.minecraft.pluginCatalog`.
    Presets and examples consume these catalogs by name; to add an artifact,
    edit the relevant manifest and run `nix run .#update-mods`.
  */
  generatedCatalogs =
    root:
    let
      gameVersions = lib.pipe root [
        builtins.readDir
        (lib.filterAttrs (
          name: type: type == "regular" && lib.hasSuffix ".json" name && name != "manifest.json"
        ))
        builtins.attrNames
        (map (lib.removeSuffix ".json"))
      ];
      catalogFor = ver: attachArtifactSources (lib.importJSON (root + "/${ver}.json"));
    in
    lib.genAttrs gameVersions catalogFor;

  modCatalogs = generatedCatalogs paths.minecraftMods;
  paperPluginCatalogs = generatedCatalogs paths.minecraftPaperPlugins;
  velocityPluginCatalogs = generatedCatalogs paths.minecraftVelocityPlugins;
  loaderLockKeys = [
    "url"
    "hash"
  ];
  projectLoaderManifestKeys = [
    "loader"
    "project"
    "releaseChannel"
    "versions"
  ];

  /**
    Read a loader manifest directory (`manifest.json` + `<ver>.json` locks),
    typecheck inputs, and return the resolved per-version lock map.
    `extraLockKeys` lists optional keys that the per-version JSON may carry
    (e.g. `build` for Paper / Velocity). The schema is the durable handle:
    a malformed manifest fails evaluation with the path that owns the bad
    data, so `nix run .#update-loaders` knows where to look.
  */
  readLoaderManifest =
    {
      root,
      requiredManifestKeys,
      extraLockKeys ? [ ],
    }:
    let
      manifestPath = root + "/manifest.json";
      manifestPathStr = toString manifestPath;
      manifest = lib.importJSON manifestPath;

      missingManifestKeys = lib.filter (key: !(manifest ? ${key})) requiredManifestKeys;
      checkedManifest =
        if missingManifestKeys != [ ] then
          throw "ix.lib.artifacts: ${manifestPathStr} is missing required keys: ${lib.concatStringsSep ", " missingManifestKeys}"
        else if !(builtins.isList manifest.versions) then
          throw "ix.lib.artifacts: ${manifestPathStr} `versions` must be a list of game-version strings"
        else
          manifest;

      lockKeys = loaderLockKeys ++ extraLockKeys;
      readLock =
        ver:
        let
          lockPath = root + "/${ver}.json";
          lockPathStr = toString lockPath;
          exists = builtins.pathExists lockPath;
          lock = if exists then lib.importJSON lockPath else { };
          missingLockKeys = lib.filter (key: !(lock ? ${key})) loaderLockKeys;
        in
        if !exists then
          throw "ix.lib.artifacts: ${lockPathStr} is missing; add it or remove `${ver}` from ${manifestPathStr}"
        else if missingLockKeys != [ ] then
          throw "ix.lib.artifacts: ${lockPathStr} is missing required keys: ${lib.concatStringsSep ", " missingLockKeys}"
        else if !(lib.isString lock.url) || !(lib.hasPrefix "https://" lock.url) then
          throw "ix.lib.artifacts: ${lockPathStr} `url` must be an https:// string"
        else if !(lib.isString lock.hash) || !(lib.hasPrefix "sha256-" lock.hash) then
          throw "ix.lib.artifacts: ${lockPathStr} `hash` must be an `sha256-...` SRI string"
        else
          lib.filterAttrs (key: _: lib.elem key lockKeys) lock;
    in
    {
      manifest = checkedManifest;
      locks = lib.genAttrs checkedManifest.versions readLock;
    };

  paperLoader = readLoaderManifest {
    root = paths.minecraftLoaders.paper;
    requiredManifestKeys = projectLoaderManifestKeys;
    extraLockKeys = [ "build" ];
  };
  velocityLoader = readLoaderManifest {
    root = paths.minecraftLoaders.velocity;
    requiredManifestKeys = projectLoaderManifestKeys;
    extraLockKeys = [ "build" ];
  };
  fabricLoader = readLoaderManifest {
    root = paths.minecraftLoaders.fabric;
    requiredManifestKeys = [
      "loader"
      "loaderVersion"
      "installerVersion"
      "versions"
    ];
  };

  paperServers = attachArtifactSources paperLoader.locks;
  velocityServers = attachArtifactSources velocityLoader.locks;
  fabricServers = lib.mapAttrs' (mcVer: lock: {
    name = "${mcVer}-fabric";
    value = mkArtifact lock;
  }) fabricLoader.locks;
  paperServerSrcs = lib.mapAttrs' (mcVer: entry: {
    name = "${mcVer}-paper";
    value = entry.src;
  }) paperServers;

  # Minecraft version of the default variant declared in the committed
  # catalog. Lets per-loader fallback catalogs follow the default instead of
  # pinning a literal version that silently rots once the default moves.
  defaultMinecraftVersion =
    let
      versionsModule = import (paths.minecraftCatalogs + "/versions.nix") {
        inherit lib;
      };
    in
    versionsModule.${versionsModule.default}.services.minecraft.version;
in
{
  inherit attachArtifactSources;
  minecraft = {
    inherit
      modCatalogs
      paperPluginCatalogs
      paperServers
      velocityPluginCatalogs
      velocityServers
      ;
    # Raw loader-manifest data after schema validation, without the wrapping
    # `fetchurl` derivations. Exposed so the schema check in
    # `lib/per-system.nix` can `deepSeq` the parsed JSON without forcing
    # every transitive derivation graph attached to `paperServers.*.src`.
    loaderManifests = {
      paper = paperLoader;
      velocity = velocityLoader;
      fabric = fabricLoader;
    };
    paperPluginCatalog =
      if builtins.hasAttr defaultMinecraftVersion paperPluginCatalogs then
        paperPluginCatalogs.${defaultMinecraftVersion}
      else
        throw "ix.lib.artifacts.minecraft.paperPluginCatalog: no Paper plugin catalog generated for Minecraft ${defaultMinecraftVersion} (the default in packages/minecraft/catalogs/versions.nix). Run `nix run .#update-mods -- --manifest packages/minecraft/catalogs/plugins/paper/manifest.json --version ${defaultMinecraftVersion}` and commit the result.";
    # Velocity plugins are cross-Minecraft-version: `velocityPluginCatalog`
    # is the unversioned default surfaced to modules. Per-version overrides
    # can still come from `velocityPluginCatalogs.<version>` if added.
    velocityPluginCatalog = velocityPluginCatalogs.common;
    servers = fabricServers // paperServerSrcs;
  };
}
