# Self-tests for lib/util seams (#3898), imported by lib/per-system.nix into
# the per-system check catalog via the shared mkScriptCheck shape.
{
  pkgs,
  mkCheck,
  formatProvenance,
  artifacts,
}: {
  # Pins the formatProvenance seam (lib/util/format-provenance.nix): a
  # wrapped comment-capable generator must emit the `# generated by
  # <file>:<line>` header as line 1 and keep the format's own rendering
  # intact below it, for both an unsafeGetAttrPos-shaped position and
  # an explicit { file, line } pair.
  format-provenance = let
    sample = {greeting = "hello";};
    tomlFile =
      (formatProvenance.withHeader pkgs {
        format = pkgs.formats.toml {};
        position = builtins.unsafeGetAttrPos "greeting" sample;
      }).generate "sample.toml"
      sample;
    kvFile = (formatProvenance.withHeader pkgs {
      format = pkgs.formats.keyValue {};
      position = {
        file = "lib/util/checks.nix";
        line = 1;
      };
    }).generate "sample.env" {GREETING = "hello";};
  in
    mkCheck "format-provenance" {
      script = ''
        head -n1 ${tomlFile} | grep -Eqx '# generated by .+/checks\.nix:[0-9]+'
        grep -qx 'greeting = "hello"' ${tomlFile}
        head -n1 ${kvFile} | grep -qx '# generated by lib/util/checks\.nix:1'
        grep -qx 'GREETING=hello' ${kvFile}
      '';
    };

  # Offline schema gate for the loader manifests. `deepSeq` forces
  # every Paper / Velocity / Fabric per-version lock through
  # `readLoaderManifest` in `lib/artifacts.nix`, so malformed JSON or a
  # missing key fires here before any image starts evaluating. The
  # forced surface is the parsed-and-validated manifest data, not the
  # wrapped `fetchurl` derivations, to keep this check pure eval.
  loader-manifests = let
    forced = builtins.deepSeq artifacts.minecraft.loaderManifests "ok";
  in
    mkCheck "loader-manifests" {
      script = ''
        printf '%s\n' '${forced}'
      '';
    };
}
