# Inline provenance for generated config files: wrap a comment-capable
# `pkgs.formats`-style generator so its output names the Nix expression that
# declared it. See the `withHeader` doc comment for the contract.
{lib}: {
  /**
  Wrap a comment-capable `pkgs.formats`-style generator so every file it
  generates opens with a provenance header naming the Nix expression that
  declared the value:

    # generated by /nix/store/...-source/modules/foo.nix:42

  A config file found on a live machine then answers "where is this managed?"
  by itself. Only formats whose syntax has `#` line comments qualify
  (keyValue, ini, toml, yaml); JSON has no comment syntax, so a JSON format
  cannot ride this seam.

  Arguments:
  - `pkgs`: package set used to build the concatenated output file.
  - `format`: a `pkgs.formats.<name> { }`-style attrset (`type` +
    `generate`). Everything except `generate` passes through unchanged, so
    the result still slots anywhere a `pkgs.formats` value is expected.
  - `position`: `{ file, line }` named in the header, the shape
    `builtins.unsafeGetAttrPos` returns; pass an explicit pair when no
    single attribute is the natural anchor.

  Example:

    settingsFormat = ix.formatProvenance.withHeader pkgs {
      format = pkgs.formats.toml { };
      position = builtins.unsafeGetAttrPos "settings" cfg;
    };
  */
  withHeader = pkgs: {
    format,
    position,
  }:
    if position == null || !(position ? file && position ? line)
    then
      throw ''
        formatProvenance.withHeader: position must be { file, line } (the shape builtins.unsafeGetAttrPos returns); got: ${lib.generators.toPretty {} position}''
    else
      format
      // {
        generate = name: value:
          pkgs.concatText name [
            (builtins.toFile "provenance-header" "# generated by ${toString position.file}:${toString position.line}\n")
            (format.generate name value)
          ];
      };
}
