# Apply an ordered patch series to a source tree. Two callers remain since
# the jj megamerge migration: downstream repos (ix) that still keep in-repo
# `patches/` folders applied `0001..NNNN` on top of a pinned upstream input,
# and index's own forks, whose static series moved into fork-repo commit
# DAGs (the input already IS the patched tree) and which pass `patchDir =
# null` to apply only their `derivedPatches`.
#
# For a static series the patch folder is the single source of truth: the
# series is derived from `builtins.readDir patchDir` (naturally sorted,
# `*.patch` only), never a hand-kept list, so adding a patch is dropping a
# numbered file in the folder and nothing else.
#
# A fork can additionally declare DERIVED patches (`derivedPatches` in
# lib/fork-packages.nix): mechanical output that is generated BY NIX from the
# pinned tree at build time instead of being stored as a line diff. Each entry
# names a generator file evaluating to `{pkgs, src, ...}: drv` whose output is
# a single unified-diff file; the outputs are applied after the static series
# in registry order. Each generator receives the tree as the series left it
# (static patches plus any earlier derived patch applied) -- a derived patch
# is a commit on top of the series, so it sees files the static series
# created, exactly as its stored-diff predecessor did. Because the diff is
# recomputed against whatever that tree is, a derived patch can never conflict
# on rebase -- so
# `rebase-patches`, dag.json, and the commit-body reason check ignore them by
# construction (they are not `*.patch` files; the registry `reason` field is
# their reason of record). The registry is bound into `patchedSrcFor` once and
# matched here by `patchDir`, so the package build and the
# `patched-src-<name>` check can never disagree about the derived series.
#
# `applyPatches` is a nixpkgs trivial builder and opts out of substitution. A
# patched source (e.g. ghostty) enters the darwin cross lane's eval-time IFD
# closure, so a Mac must be able to substitute it: `evalTimeSubstitutable`
# (threaded from lib) flips `allowSubstitutes` back on. See its doc comment.
# The same applies to the derived-patch generator outputs, which are inputs of
# that closure.
{
  lib,
  # Consuming package set the derived-patch generators build against (the
  # static series never needs it; `applyPatches` is threaded separately so the
  # binding stays per-system).
  pkgs,
  applyPatches,
  evalTimeSubstitutable,
  # The repo's fork registry (lib/fork-packages.nix `forkPackages`) and the
  # repo root its repo-relative paths resolve against. Defaulted empty so a
  # downstream consumer without derived patches (e.g. ix's cross-repo
  # `index.lib.patchedSrcFor` use) is unchanged.
  forkPackages ? [],
  patchesRoot ? null,
}:
# Return the patched source derivation. `applyPatches` copies `src` and runs
# `patch` for each entry, so the result is a tiny, seconds-fast derivation that
# doubles as the `checks.<system>.patched-src-<name>` conflict gate: if it
# builds, the series still applies.
{
  name,
  src,
  # Directory holding an ordered static `NNNN-*.patch` series, or null when
  # the fork has no in-repo static series (index's jj megamerge forks: the
  # input already IS the patched tree and only `derivedPatches` remain).
  # Downstream patch-dir forks (ix) pass a real directory, unchanged.
  patchDir ? null,
  # Optional restriction of the applied series to a subset of the discovered
  # patch files (bare `NNNN-*.patch` names, any order). `null`, the default,
  # applies the full discovered series, so every existing caller (including
  # ix's cross-repo `index.lib.patchedSrcFor` use) is unchanged. The subset is
  # validated against the discovered series (an unknown name is an eval error,
  # not a silently shorter series) and applied in NNNN order; the
  # canonical-format assertions below still run on every selected patch. Used
  # by the per-attempt-patch closure build gates (RFC 0010 A3, #2098):
  # `upstream-pr` ships a patch as its dag.json ancestor closure against the
  # bare base, so that closure must build as a standalone series.
  patchNames ? null,
}: let
  # `rebase-patches` exports the series with `git format-patch --zero-commit
  # --no-signature --no-stat -N`, so a conforming file is byte-stable across
  # regenerations: no commit-hash, `[PATCH N/M]` count, diffstat, or
  # git-version churn in the diff. Hand-added patches drift from that shape,
  # so assert it at eval and fail with the regeneration command. Derived
  # patches are exempt by construction: they are generated diffs, not
  # format-patch exports, and never live in the folder.
  zeroFrom = "From 0000000000000000000000000000000000000000 Mon Sep 17 00:00:00 2001";
  assertCanonical = fileName: path: let
    lines = lib.splitString "\n" (builtins.readFile path);
    nonEmpty = lib.filter (l: l != "") lines;
    # Diffstat can only appear in the header, between the `---` separator
    # and the first `diff --git`; scoping the scan there keeps diff content
    # that merely mentions "files changed" from tripping the check.
    firstDiffLine = lib.lists.findFirstIndex (lib.hasPrefix "diff --git ") (lib.length lines) lines;
    header = lib.take firstDiffLine lines;
    fail = why:
      throw ''
        ${name}: ${fileName}: ${why}.
        The series must match its writer, `git format-patch --zero-commit
        --no-signature --no-stat -N`; regenerate it with that command.
      '';
  in
    if builtins.match "[0-9]{4}-.*" fileName == null
    then fail "filename lacks the NNNN- series prefix"
    else if lib.head lines != zeroFrom
    then fail "first line is not the zeroed `From ` header (--zero-commit)"
    else if !(lib.any (lib.hasPrefix "Subject: [PATCH] ") lines)
    then fail "missing unnumbered `Subject: [PATCH] ` header (-N; `[PATCH N/M]` renumbers the whole series on insert)"
    else if lib.any (l: builtins.match " [0-9]+ files? changed.*" l != null) header
    then fail "diffstat block in the header (--no-stat)"
    else if lib.length nonEmpty >= 2 && lib.elemAt nonEmpty (lib.length nonEmpty - 2) == "-- "
    then fail "trailing signature block (--no-signature)"
    else path;
  discovered =
    if patchDir == null
    then []
    else
      lib.pipe (builtins.readDir patchDir) [
        (lib.filterAttrs (f: t: t == "regular" && lib.hasSuffix ".patch" f))
        builtins.attrNames
        lib.naturalSort
      ];
  # Filtering the discovered series (rather than sorting the request) keeps
  # NNNN application order the single ordering owner and dedupes for free.
  selected =
    if patchNames == null
    then discovered
    else let
      unknown = lib.subtractLists discovered patchNames;
    in
      if unknown != []
      then
        throw ''
          ${name}: patchNames not in ${toString patchDir}: ${lib.concatStringsSep ", " unknown}.
          The selection must name existing `NNNN-*.patch` files of the series.
        ''
      else lib.filter (f: lib.elem f patchNames) discovered;
  patchFiles =
    map (fileName: {
      inherit fileName;
      path = assertCanonical fileName (patchDir + "/${fileName}");
    })
    selected;
  # The fork's derived-patch series: registry entries matched by fork `name`
  # (the registry has no patch dirs since the jj megamerge migration). A
  # `patchNames` selection excludes them: repo-local mechanical output has no
  # place in an upstream-shaped static selection.
  derivedDeclared = lib.concatMap (
    fork:
      lib.optionals (fork.name == name)
      (fork.derivedPatches or [])
  ) (lib.optionals (patchesRoot != null) forkPackages);
  derivedSelected =
    if patchNames == null
    then derivedDeclared
    else [];
  # This digest identifies the ordered downstream delta of the STATIC series.
  # Consumers combine it with their pinned upstream revision when they need a
  # full source identity. Derived patches are deliberately not part of it:
  # their content is a build product identified by the derivation itself, and
  # the only patchSet consumer (packages/nix provenance) has none.
  patches =
    map (patch: {
      name = patch.fileName;
      digest = builtins.hashString "sha256" (builtins.readFile patch.path);
    })
    patchFiles;
  patchSet = {
    count = builtins.length patches;
    algorithm = "sha256";
    digest = builtins.hashString "sha256" (builtins.toJSON patches);
    inherit patches;
  };
  staticPatched = evalTimeSubstitutable (applyPatches {
    # When derived patches follow, this is an intermediate tree; the final
    # step below owns the plain `-patched` name every consumer sees.
    name =
      if derivedSelected == []
      then "${name}-patched"
      else "${name}-static-patched";
    inherit src;
    patches = map (patch: patch.path) patchFiles;
  });
  # Apply the derived series one generator at a time: each generator is
  # imported and handed the consuming package set plus the tree with
  # everything before it applied (the static series and earlier derived
  # patches), so its diff regenerates against exactly the tree it patches. The
  # generator output joins the eval-time IFD closure of the patched source, so
  # it must be substitutable on the darwin cross lane like the patched source
  # itself.
  applyDerived = tree: remaining:
    if remaining == []
    then tree
    else let
      d = lib.head remaining;
      rest = lib.tail remaining;
      next = evalTimeSubstitutable (applyPatches {
        name =
          if rest == []
          then "${name}-patched"
          else "${name}-patched+${d.name}";
        src = tree;
        patches = [
          (evalTimeSubstitutable (
            import (patchesRoot + "/${d.generator}") {
              inherit pkgs;
              src = tree;
            }
          ))
        ];
      });
    in
      applyDerived next rest;
  patched = applyDerived staticPatched derivedSelected;
in
  patched.overrideAttrs (old: {
    passthru =
      (old.passthru or {})
      // {
        inherit patchSet;
        derivedPatches = derivedSelected;
      };
  })
