[
  "*.rs merge=ast-merge"
  "*.ts merge=ast-merge"
  "*.tsx merge=ast-merge"
  "*.mts merge=ast-merge"
  "*.cts merge=ast-merge"
  "*.js merge=ast-merge"
  "*.jsx merge=ast-merge"
  "*.mjs merge=ast-merge"
  "*.cjs merge=ast-merge"
  "*.py merge=ast-merge"
  "*.pyi merge=ast-merge"
  "*.go merge=ast-merge"
  "*.json merge=ast-merge"
  "*.jsonc merge=ast-merge"
  "*.toml merge=ast-merge"
  "*.yaml merge=ast-merge"
  "*.yml merge=ast-merge"
]
