<script lang="ts">
  import TaskGraph from './lib/TaskGraph.svelte';
  import { loadTasks } from './lib/db';
  import {
    statusOf,
    STATUS_META,
    CATEGORY_COLORS,
    type Task,
    type Status,
  } from './lib/types';

  // Data comes from a real SQLite file (public/tasks.sqlite), read in the browser
  // via sql.js. Generated by the `tasks` Python helper.
  let tasks = $state<Task[]>([]);
  let error = $state<string | null>(null);
  let loaded = $state(false);
  const byId = $derived(new Map(tasks.map((t) => [t.id, t])));

  loadTasks()
    .then((rows) => {
      tasks = rows;
      loaded = true;
    })
    .catch((e) => {
      error = e instanceof Error ? e.message : String(e);
      loaded = true;
    });

  let colorMode = $state<'status' | 'category'>('status');
  let dagOn = $state(true);
  let query = $state('');
  let selected = $state<Task | null>(null);
  let graph = $state<TaskGraph>();

  const counts = $derived.by(() => {
    const c: Record<Status, number> = {
      done: 0,
      'in-progress': 0,
      ready: 0,
      blocked: 0,
    };
    for (const t of tasks) c[statusOf(t, byId)]++;
    return c;
  });

  const pctDone = $derived(
    tasks.length ? Math.round((counts.done / tasks.length) * 100) : 0,
  );

  const results = $derived.by(() => {
    const q = query.trim().toLowerCase();
    if (!q) return [];
    return tasks
      .filter(
        (t) =>
          t.title.toLowerCase().includes(q) ||
          t.id.toLowerCase().includes(q) ||
          t.category.toLowerCase().includes(q),
      )
      .slice(0, 8);
  });

  const dependents = $derived(
    selected
      ? tasks.filter((t) => t.deps.includes(selected!.id))
      : [],
  );

  function selectTask(t: Task) {
    query = '';
    graph?.focus(t);
  }
</script>

<main>
  <aside>
    <header>
      <h1>Task Graph</h1>
      <p class="sub">{tasks.length} tasks · {tasks.reduce((n, t) => n + t.deps.length, 0)} dependencies</p>
    </header>

    <section class="progress">
      <div class="bar"><div class="fill" style:width="{pctDone}%"></div></div>
      <span>{pctDone}% complete</span>
    </section>

    <section class="search">
      <input placeholder="Search tasks…" bind:value={query} />
      {#if results.length}
        <ul class="results">
          {#each results as t (t.id)}
            <li>
              <button onclick={() => selectTask(t)}>
                <span class="dot" style:background={STATUS_META[statusOf(t, byId)].color}></span>
                <span class="rid">{t.id}</span>
                {t.title}
              </button>
            </li>
          {/each}
        </ul>
      {/if}
    </section>

    <section class="controls">
      <div class="seg">
        <button class:active={colorMode === 'status'} onclick={() => (colorMode = 'status')}>Status</button>
        <button class:active={colorMode === 'category'} onclick={() => (colorMode = 'category')}>Category</button>
      </div>
      <label class="toggle">
        <input type="checkbox" bind:checked={dagOn} />
        Layered (DAG) layout
      </label>
      <button class="reset" onclick={() => graph?.resetView()}>Reset view</button>
    </section>

    <section class="legend">
      <h2>{colorMode === 'status' ? 'Status' : 'Category'}</h2>
      {#if colorMode === 'status'}
        {#each Object.entries(STATUS_META) as [key, meta] (key)}
          <div class="row">
            <span class="dot" style:background={meta.color}></span>
            {meta.label}
            <span class="num">{counts[key as Status]}</span>
          </div>
        {/each}
      {:else}
        {#each Object.entries(CATEGORY_COLORS) as [cat, color] (cat)}
          <div class="row">
            <span class="dot" style:background={color}></span>
            {cat}
            <span class="num">{tasks.filter((t) => t.category === cat).length}</span>
          </div>
        {/each}
      {/if}
    </section>

    {#if selected}
      {@const s = statusOf(selected, byId)}
      <section class="detail">
        <h2>{selected.id}</h2>
        <p class="title">{selected.title}</p>
        <div class="meta">
          <span class="tag" style:background={CATEGORY_COLORS[selected.category]}>{selected.category}</span>
          <span class="tag" style:background={STATUS_META[s].color}>{STATUS_META[s].label}</span>
          <span class="tag ghost">{selected.estimate}d</span>
        </div>

        <h3>Depends on ({selected.deps.length})</h3>
        {#if selected.deps.length}
          <ul class="links">
            {#each selected.deps as id (id)}
              {@const dep = byId.get(id)!}
              <li>
                <button onclick={() => graph?.focus(dep)}>
                  <span class="dot" style:background={STATUS_META[statusOf(dep, byId)].color}></span>
                  <span class="rid">{dep.id}</span> {dep.title}
                </button>
              </li>
            {/each}
          </ul>
        {:else}
          <p class="empty">No dependencies — a root task.</p>
        {/if}

        <h3>Blocks ({dependents.length})</h3>
        {#if dependents.length}
          <ul class="links">
            {#each dependents as dep (dep.id)}
              <li>
                <button onclick={() => graph?.focus(dep)}>
                  <span class="dot" style:background={STATUS_META[statusOf(dep, byId)].color}></span>
                  <span class="rid">{dep.id}</span> {dep.title}
                </button>
              </li>
            {/each}
          </ul>
        {:else}
          <p class="empty">Nothing depends on this task.</p>
        {/if}
      </section>
    {:else}
      <section class="hint">
        <p>Click a node to inspect a task, its dependencies, and what it blocks. Arrows point from a dependency to the task that needs it.</p>
      </section>
    {/if}
  </aside>

  <div class="canvas">
    {#if error}
      <div class="status err">Could not load tasks.sqlite<br /><code>{error}</code></div>
    {:else if !loaded}
      <div class="status">Loading task graph…</div>
    {:else if tasks.length}
      <TaskGraph
        bind:this={graph}
        {tasks}
        {colorMode}
        dagMode={dagOn ? 'td' : null}
        bind:selected
      />
    {:else}
      <div class="status">No tasks in database.</div>
    {/if}
  </div>
</main>

<style>
  main {
    display: grid;
    grid-template-columns: 320px 1fr;
    height: 100vh;
    width: 100vw;
  }
  aside {
    border-right: 1px solid #21262d;
    background: #0d1117;
    overflow-y: auto;
    padding: 18px 16px;
    display: flex;
    flex-direction: column;
    gap: 18px;
  }
  header h1 {
    margin: 0;
    font-size: 18px;
    letter-spacing: -0.01em;
  }
  .sub {
    margin: 4px 0 0;
    color: #8b949e;
    font-size: 12px;
  }
  .progress .bar {
    height: 6px;
    background: #21262d;
    border-radius: 999px;
    overflow: hidden;
  }
  .progress .fill {
    height: 100%;
    background: linear-gradient(90deg, #3fb950, #58a6ff);
    transition: width 0.4s ease;
  }
  .progress span {
    display: block;
    margin-top: 6px;
    font-size: 12px;
    color: #8b949e;
  }
  input {
    width: 100%;
    box-sizing: border-box;
    background: #161b22;
    border: 1px solid #30363d;
    border-radius: 8px;
    padding: 8px 10px;
    color: #e6edf3;
    font-size: 13px;
  }
  input:focus {
    outline: none;
    border-color: #58a6ff;
  }
  .results {
    list-style: none;
    margin: 6px 0 0;
    padding: 0;
    border: 1px solid #30363d;
    border-radius: 8px;
    overflow: hidden;
  }
  .results button,
  .links button {
    width: 100%;
    text-align: left;
    background: none;
    border: none;
    color: #e6edf3;
    padding: 7px 9px;
    font-size: 12px;
    cursor: pointer;
    display: flex;
    align-items: center;
    gap: 6px;
  }
  .results button:hover,
  .links button:hover {
    background: #161b22;
  }
  .seg {
    display: flex;
    background: #161b22;
    border: 1px solid #30363d;
    border-radius: 8px;
    padding: 3px;
    gap: 3px;
  }
  .seg button {
    flex: 1;
    background: none;
    border: none;
    color: #8b949e;
    padding: 6px;
    border-radius: 6px;
    font-size: 12px;
    cursor: pointer;
  }
  .seg button.active {
    background: #21262d;
    color: #e6edf3;
  }
  .controls {
    display: flex;
    flex-direction: column;
    gap: 10px;
  }
  .toggle {
    display: flex;
    align-items: center;
    gap: 8px;
    font-size: 12px;
    color: #c9d1d9;
  }
  .toggle input {
    width: auto;
  }
  .reset {
    background: #161b22;
    border: 1px solid #30363d;
    color: #c9d1d9;
    border-radius: 8px;
    padding: 7px;
    font-size: 12px;
    cursor: pointer;
  }
  .reset:hover {
    border-color: #58a6ff;
  }
  h2 {
    font-size: 11px;
    text-transform: uppercase;
    letter-spacing: 0.06em;
    color: #8b949e;
    margin: 0 0 8px;
  }
  h3 {
    font-size: 11px;
    text-transform: uppercase;
    letter-spacing: 0.06em;
    color: #8b949e;
    margin: 14px 0 6px;
  }
  .row {
    display: flex;
    align-items: center;
    gap: 8px;
    font-size: 12px;
    padding: 3px 0;
    color: #c9d1d9;
  }
  .num,
  .rid {
    color: #6e7681;
  }
  .num {
    margin-left: auto;
  }
  .rid {
    font-variant-numeric: tabular-nums;
    font-size: 11px;
  }
  .dot {
    width: 9px;
    height: 9px;
    border-radius: 50%;
    flex: none;
  }
  .detail .title {
    margin: 2px 0 10px;
    font-size: 14px;
    font-weight: 600;
  }
  .meta {
    display: flex;
    flex-wrap: wrap;
    gap: 6px;
  }
  .tag {
    font-size: 11px;
    padding: 2px 8px;
    border-radius: 999px;
    color: #0d1117;
    font-weight: 600;
  }
  .tag.ghost {
    background: #21262d;
    color: #c9d1d9;
  }
  .links {
    list-style: none;
    margin: 0;
    padding: 0;
  }
  .empty {
    font-size: 12px;
    color: #6e7681;
    margin: 0;
  }
  .hint p {
    font-size: 12px;
    color: #8b949e;
    line-height: 1.5;
    margin: 0;
  }
  .canvas {
    position: relative;
    overflow: hidden;
  }
  .status {
    position: absolute;
    inset: 0;
    display: flex;
    align-items: center;
    justify-content: center;
    text-align: center;
    color: #8b949e;
    font-size: 14px;
    padding: 24px;
  }
  .status.err {
    color: #f85149;
  }
  .status code {
    color: #8b949e;
    font-size: 12px;
  }
</style>
