#!/usr/bin/env bash
# Regenerate src/bindings.rs from the libghostty-vt C headers.
#
# The bindings are checked in so the crate builds without a bindgen toolchain
# and so review can see the FFI surface diff. Run this after the libghostty-vt
# headers change in the Ghostty view, then commit the result.
#
# Usage (from the repo root):
#   nix shell nixpkgs#rust-bindgen nixpkgs#clang nixpkgs#rustfmt \
#     -c packages/tui/vt/ix-vt-sys/regen-bindings.sh
#
# It builds libghostty-vt through the flake to locate the view's headers.
set -euo pipefail

script_dir="$(cd "$(dirname "${BASH_SOURCE[0]}")" && pwd)"
repo_root="$(cd "$script_dir/../../.." && pwd)"

lib="$(nix build "$repo_root#libghostty-vt" --no-link --print-out-paths)"

# `--no-layout-tests` keeps the bindings portable across the Unix targets we
# support (the C ABI is identical; bindgen's size/offset asserts are generated
# for the host that ran bindgen). `--no-doc-comments` drops the Doxygen blocks
# so the file stays a compact symbol map; the safe API in ix-vt is the
# documented surface.
bindgen "$lib/include/ghostty/vt.h" \
  --allowlist-function 'ghostty_.*' \
  --allowlist-type 'Ghostty.*' \
  --allowlist-var 'GHOSTTY_.*' \
  --default-enum-style rust \
  --no-layout-tests \
  --no-doc-comments \
  --raw-line '/* Generated by rust-bindgen from ghostty/vt.h. Do not edit by hand.' \
  --raw-line ' * Regenerate with packages/tui/vt/ix-vt-sys/regen-bindings.sh after a' \
  --raw-line ' * libghostty-vt header change (see that script for the exact flags). */' \
  --raw-line '#![allow(' \
  --raw-line '    non_upper_case_globals,' \
  --raw-line '    non_camel_case_types,' \
  --raw-line '    non_snake_case,' \
  --raw-line '    reason = "bindgen reproduces the C identifiers verbatim so the FFI symbols match the header; renaming them would break the linkage this file exists to declare"' \
  --raw-line ')]' \
  --raw-line '#![allow(' \
  --raw-line '    clippy::all,' \
  --raw-line '    clippy::pedantic,' \
  --raw-line '    clippy::nursery,' \
  --raw-line '    reason = "generated by rust-bindgen; regen-bindings.sh overwrites this file wholesale, so any lint fix here is lost on the next ghostty header bump"' \
  --raw-line ')]' \
  -- -I"$lib/include" \
  >"$script_dir/src/bindings.rs"

echo "wrote $script_dir/src/bindings.rs"
