# Nushell Environment Config File
#
# version = "0.106.1"

# plugin add /Users/andrewgazelka/.cargo/bin/nu_plugin_dns
# plugin use dns

# Set environment variables first (needed for PATH construction)
# home-manager session variables (generated from home.sessionVariables)
source ~/.config/nushell-hm-session-vars.nu

# Machine-local credentials are provisioned by the private host config and
# never enter this repository or the Nix store.
let secrets_file = ("~/.config/nushell-secrets.nuon" | path expand)
if ($secrets_file | path exists) {
    load-env (open $secrets_file)
}

# $env.NU_EXPERIMENTAL_OPTIONS = 'all'  # DISABLED: may cause tilde expansion issues
$env.NEXTEST_EXPERIMENTAL_LIBTEST_JSON = 1

$env.CLAUDE_CODE_DISABLE_GIT_INSTRUCTIONS = 1
# Auto-promote nu-mcp evaluations to a background job after this duration
# (default 10s is too aggressive for `cargo clippy` / `cargo build`).
$env.NU_MCP_PROMOTE_AFTER = 2min

$env.IX_DEBUG = 1
$env.CLAUDE_CODE_ENABLE_OPUS_4_7_FAST_MODE = 1
$env.CLAUDE_CODE_NO_FLICKER = 1

$env.CLAUDE_USE_SUBSCRIPTION = 1


# Editor configuration
$env.EDITOR = "nvim"
# Force git's editor too: a parent process (e.g. Claude Code) can export
# GIT_EDITOR=true, which makes `git commit` abort with an empty message
# instead of opening an editor. GIT_EDITOR wins over core.editor, so set it
# here to guarantee an interactive nushell always opens nvim.
$env.GIT_EDITOR = "nvim"
$env.RUST_BACKTRACE = "full"

# Load plugins (must be in env.nu before config.nu)
# plugin add /Users/andrewgazelka/.cargo/bin/nu_plugin_bson
# plugin add /Users/andrewgazelka/.cargo/bin/nu_plugin_dns
# plugin add /Users/andrewgazelka/.cargo/bin/nu_plugin_file
# plugin add /Users/andrewgazelka/.cargo/bin/nu_plugin_formats
# plugin add /Users/andrewgazelka/.cargo/bin/nu_plugin_gstat
# plugin add /Users/andrewgazelka/.cargo/bin/nu_plugin_kdl
# plugin add /Users/andrewgazelka/.cargo/bin/nu_plugin_polars
# plugin add /Users/andrewgazelka/Projects/sdk/target/release/nu_plugin_base


# Buck2 sets XDG_STATE_HOME under $TMPDIR when invoking the watchman CLI.
# On macOS the resulting socket path exceeds the 104-byte sun_path limit.
$env.WATCHMAN_SOCK = $"($env.HOME)/.local/state/watchman/($env.USER)-state/sock"

$env.HOMEBREW_NO_ENV_HINTS = 1

$env._ZO_FZF_OPTS = "+i"

# Detect platform
let is_macos = ($nu.os-info.name == "macos")

# Set up PATH - prepend custom paths to existing system PATH
$env.PATH = ($env.PATH | split row (char esep))

# Cross-platform paths
$env.PATH = ($env.PATH | prepend [
    $'($env.HOME)/.local/bin'
    $'($env.HOME)/.cargo/bin'
    $'($env.HOME)/.nix-profile/bin'
    $'/etc/profiles/per-user/($env.USER)/bin'  # NixOS home-manager-as-module installs user pkgs here (useUserPackages = true)
    '/run/wrappers/bin'  # NixOS setuid wrappers (sudo, etc) - must come before /run/current-system/sw/bin
    '/run/current-system/sw/bin'
    '/nix/var/nix/profiles/default/bin'
    $'($env.HOME)/.bun/bin'
    $'($env.HOME)/.local/share/npm/bin'
])

# macOS-specific paths
if $is_macos {
    $env.PATH = ($env.PATH | prepend [
        $'($env.HOME)/Library/Application Support/JetBrains/Toolbox/scripts'
        '/opt/homebrew/bin'
        '/usr/local/bin'
        '/opt/homebrew/sbin'
        $'($env.HOME)/Projects/tools/target/release'
        $'($env.HOME)/Projects/loaf/zig-out/bin'
        $'($env.HOME)/.ghcup/bin'
    ])
}

# macOS-specific: Nix and Homebrew config
if $is_macos {
    $env.NIX_PATH = $'darwin-config=($env.HOME)/.config/nix/flake.nix:nixpkgs=flake:nixpkgs'
    $env.HOMEBREW_PREFIX = '/opt/homebrew'
    $env.HOMEBREW_CELLAR = '/opt/homebrew/Cellar'
    $env.HOMEBREW_REPOSITORY = '/opt/homebrew'
    $env.MANPATH = $'/opt/homebrew/share/man:($env.MANPATH? | default "")'
    $env.INFOPATH = $'/opt/homebrew/share/info:($env.INFOPATH? | default "")'
}

# Initialize zoxide (now that we have PATH set up)
# Generated by home-manager into ~/.config/nushell-zoxide.nu
# Sourced in config.nu

# Add nix-profile pkgconfig to PKG_CONFIG_PATH (for fuse3.dev, etc.)
$env.PKG_CONFIG_PATH = $"($env.HOME)/.nix-profile/lib/pkgconfig:($env.PKG_CONFIG_PATH? | default "")"
$env.LIBRARY_PATH = $"($env.HOME)/.nix-profile/lib:($env.LIBRARY_PATH? | default "")"
$env.DYLD_FALLBACK_LIBRARY_PATH = $"($env.HOME)/.nix-profile/lib:($env.DYLD_FALLBACK_LIBRARY_PATH? | default "")"

# Starship prompt initialization
# if (which starship | is-not-empty) {
#     mkdir ~/.cache/starship
#     starship init nu | save -f ~/.cache/starship/init.nu
# }

# Common environment variables
$env.PAGER = 'less'
$env.LESS = '-RF --mouse'
$env.DELTA_PAGER = 'less -RF --mouse'

# LS_COLORS will be set dynamically in config.nu based on macOS theme
# Enable bridge mode to use Fish/Bash/Zsh completions as fallback
# $env.CARAPACE_BRIDGES = 'zsh,fish,bash,inshellisense'
# mkdir ~/.cache/carapace
# carapace _carapace nushell | save --force ~/.cache/carapace/init.nu

$env.OPENAI_API_BASE_URL = "https://openrouter.ai/api/v1"

$env.FZF_DEFAULT_COMMAND = 'fd --type f'

# AWS S3 configuration (non-secret)
$env.AWS_DEFAULT_REGION = 'us-east-1'
$env.AWS_OUTPUT = 'json'
$env.DRAFTED_S3_BUCKET = 'drafted-home-plans'
$env.MGREP_MAX_FILE_COUNT = 200_000

# Default LS_COLORS (can be updated with setup_theme command)
$env.LS_COLORS = 'di=34:ln=35:so=32:pi=33:ex=31:bd=34;46:cd=34;43:su=30;41:sg=30;46:tw=30;42:ow=30;43'

# Load secrets from cache immediately, refresh in background if stale (>24h)
source ($nu.default-config-dir | path join "functions" "secrets.nu")
let secrets_cache = "~/.cache/nushell/secrets.nuon" | path expand
if ($secrets_cache | path exists) {
    open $secrets_cache | load-env
    let age = (date now) - (ls $secrets_cache | get 0.modified)
    if $age > 24hr {
        job spawn { generate-secrets-cache }
    }
} else {
    generate-secrets-cache
    if ($secrets_cache | path exists) { open $secrets_cache | load-env }
}

# $env.IX_DEBUG = true
