defmodule IxMcp.ImageTest do
  # Image.read/1 and mixed MCP content: a cell whose result carries images
  # answers with real image blocks (base64 + mime), not a byte dump.
  use ExUnit.Case, async: false

  alias IxMcp.Image
  alias IxMcp.MCP.Server
  alias IxMcp.MCP.Tools

  # Magic bytes are all sniffing needs; the payload past them is arbitrary.
  @png <<0x89, "PNG", 0x0D, 0x0A, 0x1A, 0x0A, 0, 0, 0, 13, "IHDR", 1, 2, 3>>
  @jpeg <<0xFF, 0xD8, 0xFF, 0xE0, "JFIF">>

  setup do
    IxMcp.Workspace.reset()
    :ok
  end

  defp tmp_image!(bytes, ext) do
    path =
      Path.join(System.tmp_dir!(), "ix-image-test-#{System.unique_integer([:positive])}.#{ext}")

    File.write!(path, bytes)
    on_exit(fn -> File.rm(path) end)
    path
  end

  test "read/1 sniffs the format from bytes, never the extension" do
    path = tmp_image!(@png, "jpg")
    image = Image.read(path)
    assert image.mime == "image/png"
    assert image.data == @png
  end

  test "read/1 refuses non-image bytes with the supported list in hand" do
    path = tmp_image!("just text", "png")

    assert_raise ArgumentError, ~r/not a supported image \(PNG, JPEG, GIF, WebP\)/, fn ->
      Image.read(path)
    end
  end

  test "from_binary/2 wraps generated bytes, sniffing or trusting mime:" do
    assert Image.from_binary(@jpeg).mime == "image/jpeg"
    assert Image.from_binary("<svg/>", mime: "image/svg+xml").mime == "image/svg+xml"

    assert_raise ArgumentError, ~r/pass mime:/, fn -> Image.from_binary("???") end
  end

  test "collect/1 finds images nested in lists, maps and tuples, bounded" do
    image = Image.from_binary(@png)
    value = %{results: [{:ok, image}, :other], note: "text"}
    assert [^image] = Image.collect(value)
    assert Image.collect(%{plain: [1, 2, 3]}) == []
  end

  test "inspect renders a placeholder, not the bytes" do
    rendered = inspect(Image.read(tmp_image!(@png, "png")))
    assert rendered =~ "#IxMcp.Image<image/png"
    refute rendered =~ "IHDR"
  end

  test "an exec whose result is an image answers with text + image blocks" do
    path = tmp_image!(@png, "png")

    response =
      Server.handle(%{
        "jsonrpc" => "2.0",
        "id" => 1,
        "method" => "tools/call",
        "params" => %{
          "name" => "exec",
          "arguments" => %{
            "code" => ~s|Image.read("#{path}")|,
            "intent" => "read an image"
          }
        }
      })

    refute response["result"]["isError"]
    [text_block, image_block] = response["result"]["content"]

    assert text_block["type"] == "text"
    assert text_block["text"] =~ ~s("status":"done")
    assert text_block["text"] =~ "#IxMcp.Image<image/png"

    assert image_block["type"] == "image"
    assert image_block["mimeType"] == "image/png"
    assert Base.decode64!(image_block["data"]) == @png
  end

  test "an exec whose result nests images in a map still carries the blocks" do
    a = tmp_image!(@png, "png")
    b = tmp_image!(@jpeg, "jpeg")

    {:ok, content} =
      Tools.call("exec", %{
        "code" => ~s|%{a: Image.read("#{a}"), b: Image.read("#{b}")}|,
        "intent" => "two images"
      })

    assert [%{"type" => "text"} | images] = content
    assert Enum.map(images, & &1["mimeType"]) |> Enum.sort() == ["image/jpeg", "image/png"]
  end

  test "a plain result stays a plain string reply (no content array)" do
    {:ok, content} = Tools.call("exec", %{"code" => "1 + 1", "intent" => "plain"})
    assert is_binary(content)
  end
end
