//! The patch-dependency DAG: derivation, invariant verification, and the
//! serialized `dag.json` document.
//!
//! One owner for the scratch-repo apply-test logic. The rebase path
//! (src/rebase.rs) regenerates `dag.json` at the end of a rebase; the
//! `patch-dag-<name>` flake check (src/check.rs) verifies a committed DAG is
//! honest and in sync. Both operate purely on patch text against a base tree
//! (no builds), so they stay seconds-fast.
//!
//! The DAG model: nodes are the `*.patch` files, an edge P -> Q means "P needs
//! Q applied first to apply cleanly". The linear `NNNN` names imply every
//! patch depends on all before it; in truth most are independent (e.g. six of
//! the fourteen clippy patches are roots). We derive the true, sparse edge set
//! by apply-tests, never by hand.

use std::collections::{BTreeMap, BTreeSet, VecDeque};
use std::fs;
use std::os::unix::fs::PermissionsExt;
use std::path::{Path, PathBuf};

use anyhow::{Context, Result};
use lazy_regex::{regex_captures, regex_is_match};
use serde::{Deserialize, Serialize};

use crate::git;

/// A patch file in NNNN order: bare file name plus absolute path.
#[derive(Debug, Clone)]
pub struct Patch {
    pub name: String,
    pub file: PathBuf,
}

/// A patch dir listed as [`Patch`] records in NNNN (byte) order.
pub fn patches_in(patch_dir: &Path) -> Result<Vec<Patch>> {
    let mut patches = Vec::new();
    for entry in
        fs::read_dir(patch_dir).with_context(|| format!("read patch dir {}", patch_dir.display()))?
    {
        let file = entry?.path();
        if !(file.is_file() && file.extension().is_some_and(|ext| ext == "patch")) {
            continue;
        }
        let name = file
            .file_name()
            .and_then(|n| n.to_str())
            .with_context(|| format!("non-UTF-8 patch file name {}", file.display()))?
            .to_owned();
        patches.push(Patch { name, file });
    }
    patches.sort_by(|a, b| a.name.cmp(&b.name));
    Ok(patches)
}

/// One node of the serialized DAG: a patch and its DIRECT dependencies.
#[derive(Debug, Clone, PartialEq, Eq, Serialize, Deserialize)]
pub struct Node {
    pub patch: String,
    pub deps: Vec<String>,
}

/// The committed `dag.json` document. Field order is stable (comment, base,
/// nodes) so regeneration is byte-deterministic.
#[derive(Debug, Clone, Serialize, Deserialize)]
pub struct Document {
    pub comment: String,
    /// The upstream rev the DAG was derived against, so a stale committed DAG
    /// is obvious.
    pub base: String,
    pub nodes: Vec<Node>,
}

/// Committed as data next to the patches; regenerated automatically by
/// `rebase-patches` and verified in sync by the `patch-dag-<name>` check.
const COMMENT: &str = "Auto-generated by `nix run .#rebase-patches`; do not edit by hand. Nodes are patch files, deps are the minimal set of ancestors each patch needs to apply. See patch-dag-design.";

/// The `dag.json` document for a derived edge set.
pub fn document(base: &str, nodes: Vec<Node>) -> Document {
    Document {
        comment: COMMENT.to_owned(),
        base: base.to_owned(),
        nodes,
    }
}

/// Serialize the DAG document to the exact bytes we commit: pretty JSON,
/// two-space indent, trailing newline. Both the writer and the in-sync check
/// must agree on these bytes, so this is the single formatting owner.
pub fn to_json(doc: &Document) -> Result<String> {
    Ok(serde_json::to_string_pretty(doc).context("serialize dag.json")? + "\n")
}

/// Neutralize ambient git config that would make apply-tests
/// non-deterministic. The DAG must be a pure function of the patch text and
/// base, so a scratch repo used for apply-tests MUST call this once at init:
/// rerere (recording/replaying a resolution mid-run silently rewrites hunks
/// and corrupts later apply-tests), gpg signing (would prompt or fail with no
/// key), and autocrlf (would renormalize line endings) are all forced off in
/// the repo-LOCAL config, which overrides the user global config without
/// mutating it. The rebase scratch repos call this too (minus rerere, which
/// they deliberately enable) so a developer global `rerere.enabled=true`
/// cannot perturb the derived DAG.
pub fn neutralize_config(scratch: &Path) -> Result<()> {
    for (key, value) in [
        ("rerere.enabled", "false"),
        ("rerere.autoupdate", "false"),
        ("commit.gpgsign", "false"),
        ("core.autocrlf", "false"),
    ] {
        git::run(scratch, &["config", key, value])?;
    }
    Ok(())
}

/// Repo-local committer identity for scratch repos. The apply-tests `git am`
/// throwaway commits, which git refuses without an identity; setting it
/// locally keeps the tests working where no global config exists (the nix
/// sandbox) without touching the user config. The commits never leave the
/// scratch repo, so the content is irrelevant.
pub fn identity(repo: &Path) -> Result<()> {
    git::run(repo, &["config", "user.email", "check@indexable.dev"])?;
    git::run(repo, &["config", "user.name", "patch-dag check"])?;
    Ok(())
}

/// Seed a fresh git repo at `dest` from the read-only `src_dir` tree and
/// commit it as a single base commit; returns the base rev. Used by the
/// `patch-dag-<name>` check, whose base is the flake already-fetched
/// `flake = false` src (a store path with no `.git`), not a network fetch.
pub fn seed_base_repo(src_dir: &Path, dest: &Path) -> Result<String> {
    for entry in
        fs::read_dir(src_dir).with_context(|| format!("read src dir {}", src_dir.display()))?
    {
        let entry = entry?;
        copy_tree(&entry.path(), &dest.join(entry.file_name()))?;
    }
    git::run(dest, &["init", "--quiet"])?;
    identity(dest)?;
    neutralize_config(dest)?;
    git::run(dest, &["add", "--all"])?;
    git::run(dest, &["commit", "--quiet", "--no-gpg-sign", "-m", "base"])?;
    git::stdout(dest, &["rev-parse", "HEAD"])
}

/// Copy a tree, making the copy user-writable: store paths are read-only
/// (0444) and a preserved mode would make `git am` fail with "unable to write
/// file ... Permission denied" mid-apply and be misread as a non-applying
/// patch. Symlinks are copied as symlinks, never followed (store trees may
/// hold links pointing outside the copied subtree).
pub fn copy_tree(src: &Path, dest: &Path) -> Result<()> {
    let meta = fs::symlink_metadata(src).with_context(|| format!("stat {}", src.display()))?;
    let copied = if meta.file_type().is_symlink() {
        let target = fs::read_link(src)?;
        std::os::unix::fs::symlink(target, dest)
    } else if meta.is_dir() {
        fs::create_dir(dest)?;
        for entry in fs::read_dir(src)? {
            let entry = entry?;
            copy_tree(&entry.path(), &dest.join(entry.file_name()))?;
        }
        make_user_writable(dest, &meta)
    } else {
        fs::copy(src, dest)?;
        make_user_writable(dest, &meta)
    };
    copied.with_context(|| format!("copy {} -> {}", src.display(), dest.display()))
}

fn make_user_writable(path: &Path, source_meta: &fs::Metadata) -> std::io::Result<()> {
    let mode = source_meta.permissions().mode() | 0o200;
    fs::set_permissions(path, fs::Permissions::from_mode(mode))
}

/// Reset `scratch` to a pristine `base` before every trial so apply-tests
/// never see a dirty tree.
pub fn reset_to_base(scratch: &Path, base: &str) -> Result<()> {
    // Abort any half-finished `am` from a prior trial. `git am --abort` is the
    // normal path, but a `git am` that fails on the FIRST patch of a fresh run
    // can leave a `.git/rebase-apply` dir that `--abort` refuses to clear
    // ("Resolve operation not in progress"); a stale `rebase-apply` then makes
    // the next `git am` think a session is still open and misbehave. So we
    // also remove it directly. Then hard-reset the tree and index.
    git::output(scratch, &["am", "--abort"])?;
    let rebase_apply = scratch.join(".git/rebase-apply");
    if rebase_apply.exists() {
        fs::remove_dir_all(&rebase_apply)
            .with_context(|| format!("clear stale {}", rebase_apply.display()))?;
    }
    git::run(scratch, &["checkout", "--quiet", "--force", "--detach", base])?;
    git::run(scratch, &["reset", "--quiet", "--hard", base])?;
    git::run(scratch, &["clean", "--quiet", "-fdx"])?;
    Ok(())
}

/// Apply an ordered list of patch files onto a pristine base via `git am`.
/// Returns the resulting tree hash on success, or `None` if any patch failed
/// to apply (the failure is the signal, so we swallow it and abort cleanly).
/// Ordering is the caller NNNN order restricted to the subset; `git am` is
/// exact-only here (no 3-way), because a DAG edge is precisely "this text does
/// not apply without that ancestor".
pub fn apply_order(scratch: &Path, base: &str, patch_files: &[&Path]) -> Result<Option<String>> {
    if !am_stack(scratch, base, patch_files)? {
        return Ok(None);
    }
    git::stdout(scratch, &["rev-parse", "HEAD^{tree}"]).map(Some)
}

/// Does `patch` apply cleanly given ONLY the ordered `ancestors`, applied to
/// base? Builds the ancestor stack with `git am`, then `git apply --check` for
/// the candidate. Returns false if the ancestor stack itself fails to build
/// (an unapplicable subset can never be a valid ancestor set), matching the
/// semantics the DAG derivation needs: "applies given exactly these
/// ancestors".
pub fn applies_with(scratch: &Path, base: &str, ancestors: &[&Path], patch: &Path) -> Result<bool> {
    if !am_stack(scratch, base, ancestors)? {
        return Ok(false);
    }
    let checked = git::output(scratch, &["apply", "--check", git::utf8(patch)?])?;
    Ok(checked.status.success())
}

/// Reset to base and `git am` the ordered stack; false when any patch in the
/// stack fails to apply.
fn am_stack(scratch: &Path, base: &str, patch_files: &[&Path]) -> Result<bool> {
    reset_to_base(scratch, base)?;
    for file in patch_files {
        let applied = git::output(scratch, &["am", git::utf8(file)?])?;
        if !applied.status.success() {
            git::output(scratch, &["am", "--abort"])?;
            return Ok(false);
        }
    }
    Ok(true)
}

/// Derive the sparse dependency DAG for an ordered `*.patch` list against
/// `base`. Returns nodes in NNNN order, deps transitively reduced (only DIRECT
/// edges).
///
/// Algorithm (n is tiny, so O(n^2) apply-checks are milliseconds; exhaustive
/// is fine): for each patch i, start from its full predecessor set (which must
/// apply, since that is the committed serialization) and greedily drop the
/// lowest-index ancestor whose removal keeps patch i applying. This yields a
/// locally-minimal SUFFICIENT ancestor set (it stays downward-closed by
/// construction, because dropping an ancestor that another retained ancestor
/// still needs would break the stack and be rejected). Then reduce to direct
/// edges: an ancestor already implied by another dep closure is not a direct
/// edge. Prefers the sparsest DAG on ties, per the design.
pub fn derive(scratch: &Path, base: &str, patches: &[Patch]) -> Result<Vec<Node>> {
    let files: Vec<&Path> = patches.iter().map(|p| p.file.as_path()).collect();

    // full_anc[i] = minimal sufficient ancestor set (a sorted index list) for
    // patch i.
    let mut full_anc: Vec<Vec<usize>> = Vec::with_capacity(patches.len());
    for (i, file) in files.iter().enumerate() {
        let mut keep: Vec<usize> = (0..i).collect();
        // Greedy reduction: repeatedly try to drop the lowest kept ancestor;
        // if the patch still applies without it, drop it and restart the pass,
        // until no single drop preserves applicability.
        'reduce: loop {
            for q in keep.clone() {
                let trial: Vec<usize> = keep.iter().copied().filter(|&x| x != q).collect();
                let trial_files: Vec<&Path> = trial.iter().map(|&j| files[j]).collect();
                if applies_with(scratch, base, &trial_files, file)? {
                    keep = trial;
                    continue 'reduce;
                }
            }
            break;
        }
        full_anc.push(keep);
    }

    // Transitive reduction to direct edges: q is a direct dep of i iff no
    // retained ancestor of i already pulls q in through its own minimal set.
    Ok((0..patches.len())
        .map(|i| {
            let anc = &full_anc[i];
            let implied: BTreeSet<usize> =
                anc.iter().flat_map(|&r| full_anc[r].iter().copied()).collect();
            Node {
                patch: patches[i].name.clone(),
                deps: anc
                    .iter()
                    .copied()
                    .filter(|q| !implied.contains(q))
                    .map(|j| patches[j].name.clone())
                    .collect(),
            }
        })
        .collect())
}

/// Transitive closure of a patch ancestors (all patches it transitively
/// depends on), from a `patch -> deps` map, in discovery order. Excludes the
/// patch itself.
pub fn closure(deps_of: &BTreeMap<String, Vec<String>>, patch: &str) -> Result<Vec<String>> {
    let roots = deps_of
        .get(patch)
        .with_context(|| format!("no dag node for patch {patch}"))?;
    let mut seen: Vec<String> = Vec::new();
    let mut stack: VecDeque<String> = roots.iter().cloned().collect();
    while let Some(cur) = stack.pop_front() {
        if seen.contains(&cur) {
            continue;
        }
        if let Some(deps) = deps_of.get(&cur) {
            stack.extend(deps.iter().cloned());
        }
        seen.push(cur);
    }
    Ok(seen)
}

/// The set of repo-relative file paths a patch touches (its hunk footprint),
/// read from the patch `diff --git a/<path> b/<path>` headers. Used by the
/// commute fast path to skip disjoint pairs.
pub fn footprint(patch_file: &Path) -> Result<Vec<String>> {
    let text = read_lossy(patch_file)?;
    let mut paths: Vec<String> = Vec::new();
    for line in text.lines() {
        let Some((_, path)) = regex_captures!(r"^diff --git a/(.*?) b/", line) else {
            continue;
        };
        if !path.is_empty() && !paths.iter().any(|p| p == path) {
            paths.push(path.to_owned());
        }
    }
    Ok(paths)
}

/// A patch file as text. Lossy: the diff payload may hold non-UTF-8 bytes; the
/// headers and message we parse are always UTF-8.
fn read_lossy(file: &Path) -> Result<String> {
    let bytes = fs::read(file).with_context(|| format!("read {}", file.display()))?;
    Ok(String::from_utf8_lossy(&bytes).into_owned())
}

/// The commit-message body of a format-patch file: the lines between the
/// header block (ended by the first blank line; folded Subject continuations
/// are indented, never blank) and the diff payload (`---` separator, or
/// `diff --git` directly in this repo canonical `--no-stat` serialization).
/// Blank-only lines are dropped.
pub fn body_lines(file: &Path) -> Result<Vec<String>> {
    let text = read_lossy(file)?;
    let lines: Vec<&str> = text.lines().collect();
    let Some(blank) = lines.iter().position(|l| l.is_empty()) else {
        return Ok(Vec::new());
    };
    Ok(lines[blank + 1..]
        .iter()
        .take_while(|l| **l != "---" && !l.starts_with("diff --git "))
        .filter(|l| !l.trim().is_empty())
        .map(|l| (*l).to_owned())
        .collect())
}

/// Does the patch state WHY it exists in its commit-message body? The body is
/// the reason of record for every fork patch: it rides the `git am` / rebase /
/// `format-patch` round-trip, so it reaches upstream reviewers, and for
/// attempt-marked patches it becomes the upstream PR description verbatim
/// (packages/upstream-pr). Attribution trailers and bare issue references are
/// not substance: `Refs #123` points at a reason without stating it, and a
/// `*-by:` trailer states no rationale at all.
pub fn body_has_reason(file: &Path) -> Result<bool> {
    Ok(body_lines(file)?.iter().any(|line| {
        let t = line.trim();
        let trailer = regex_is_match!(r"(?i)^[a-z][a-z-]*-by:", t)
            || regex_is_match!(r"(?i)^(cc|change-id):", t);
        let bare_ref = regex_is_match!(r"(?i)^(refs?|fixes|closes|resolves|see|see-also):?[ \t]+\S+$", t);
        !(trailer || bare_ref)
    }))
}

/// The outcome of [`verify`]; the caller decides how to report and exit.
pub struct VerifyReport {
    pub errors: Vec<String>,
}

impl VerifyReport {
    pub const fn ok(&self) -> bool {
        self.errors.is_empty()
    }
}

/// Verify the DAG invariants against a committed `dag.json`: node set and base
/// match (0), NNNN is a topological order with known deps (c-topo), every
/// patch applies given only its declared ancestors (a), and DAG-independent
/// pairs commute byte-for-byte (b). Pure text work on `base` in `scratch`.
pub fn verify(scratch: &Path, base: &str, patches: &[Patch], doc: &Document) -> Result<VerifyReport> {
    let names: Vec<&str> = patches.iter().map(|p| p.name.as_str()).collect();
    let dag_names: Vec<&str> = doc.nodes.iter().map(|n| n.patch.as_str()).collect();
    let mut errors = Vec::new();

    // (0) node set matches the patch files exactly.
    let missing: Vec<&str> = names.iter().copied().filter(|nm| !dag_names.contains(nm)).collect();
    let extra: Vec<&str> = dag_names.iter().copied().filter(|nm| !names.contains(nm)).collect();
    if !missing.is_empty() {
        errors.push(format!("dag.json is missing nodes for patches: {}", missing.join(", ")));
    }
    if !extra.is_empty() {
        errors.push(format!("dag.json has nodes for nonexistent patches: {}", extra.join(", ")));
    }
    // (0b) declared base matches the base we are checking against.
    if doc.base != base {
        errors.push(format!(
            "dag.json base {} does not match the pinned base {base}",
            doc.base
        ));
    }

    // Only run structural checks when the node set is coherent.
    if missing.is_empty() && extra.is_empty() {
        let series = Series {
            scratch,
            base,
            patches,
            deps_of: doc.nodes.iter().map(|n| (n.patch.clone(), n.deps.clone())).collect(),
            pos: names.iter().enumerate().map(|(i, nm)| ((*nm).to_owned(), i)).collect(),
        };
        errors.extend(series.topo_errors());
        errors.extend(series.ancestor_errors()?);
        errors.extend(series.commute_errors()?);
    }

    Ok(VerifyReport { errors })
}

/// The parsed series plus the committed edge set, indexed for the structural
/// invariant checks.
struct Series<'a> {
    scratch: &'a Path,
    base: &'a str,
    patches: &'a [Patch],
    deps_of: BTreeMap<String, Vec<String>>,
    pos: BTreeMap<String, usize>,
}

impl Series<'_> {
    /// (c-topo) NNNN order is a valid topological order of the DAG: every dep
    /// of a patch appears earlier in the NNNN sequence. Also rejects unknown
    /// dep names.
    fn topo_errors(&self) -> Vec<String> {
        let mut errors = Vec::new();
        for patch in self.patches {
            for dep in &self.deps_of[&patch.name] {
                match self.pos.get(dep) {
                    None => errors.push(format!(
                        "patch {} declares unknown dependency {dep}",
                        patch.name
                    )),
                    Some(&at) if at >= self.pos[&patch.name] => errors.push(format!(
                        "NNNN order is not topological: {} depends on later patch {dep}",
                        patch.name
                    )),
                    Some(_) => {}
                }
            }
        }
        errors
    }

    /// (a) every patch applies given ONLY its declared DAG ancestors
    /// (transitive closure of deps), applied in NNNN order. Catches undeclared
    /// dependencies.
    fn ancestor_errors(&self) -> Result<Vec<String>> {
        let mut errors = Vec::new();
        for patch in self.patches {
            let anc = closure(&self.deps_of, &patch.name)?;
            let anc_files = self.ordered_files(&anc);
            if !applies_with(self.scratch, self.base, &anc_files, &patch.file)? {
                errors.push(format!(
                    "patch {} does NOT apply given only its declared ancestors [{}]: undeclared dependency",
                    patch.name,
                    anc.join(", ")
                ));
            }
        }
        Ok(errors)
    }

    /// (b) every pair of DAG-INDEPENDENT patches commutes: A-then-B and
    /// B-then-A both apply and yield byte-identical trees. Fast path: if the
    /// two patches touch disjoint file sets they trivially commute, so only
    /// overlapping-file pairs pay the two-order apply. Independence = neither
    /// is in the other transitive closure.
    fn commute_errors(&self) -> Result<Vec<String>> {
        let mut errors = Vec::new();
        let footprints: Vec<Vec<String>> =
            self.patches.iter().map(|p| footprint(&p.file)).collect::<Result<_>>()?;
        for (i, a) in self.patches.iter().enumerate() {
            for (j, b) in self.patches.iter().enumerate().skip(i + 1) {
                let a_anc = closure(&self.deps_of, &a.name)?;
                let b_anc = closure(&self.deps_of, &b.name)?;
                if a_anc.contains(&b.name) || b_anc.contains(&a.name) {
                    continue;
                }
                // Disjoint footprints trivially commute.
                let overlap: Vec<&str> = footprints[i]
                    .iter()
                    .filter(|f| footprints[j].contains(f))
                    .map(String::as_str)
                    .collect();
                if overlap.is_empty() {
                    continue;
                }
                // Overlapping files: prove both orders succeed and agree
                // byte-for-byte. Apply against each patch shared ancestor
                // closure first so the pair applies in isolation, then the two
                // orders.
                let mut shared = a_anc.clone();
                shared.extend(b_anc.iter().filter(|x| !a_anc.contains(x)).cloned());
                let shared_files = self.ordered_files(&shared);
                let ordered_pair = |first: &Patch, second: &Patch| {
                    let mut files = shared_files.clone();
                    files.push(first.file.as_path());
                    files.push(second.file.as_path());
                    apply_order(self.scratch, self.base, &files)
                };
                let overlap_joined = overlap.join(", ");
                match (ordered_pair(a, b)?, ordered_pair(b, a)?) {
                    (Some(ab), Some(ba)) if ab == ba => {}
                    (Some(_), Some(_)) => errors.push(format!(
                        "DAG-independent patches {} and {} overwrite each other: applying A-then-B and B-then-A give different trees; overlapping files [{overlap_joined}].",
                        a.name, b.name
                    )),
                    _ => errors.push(format!(
                        "DAG-independent patches {} and {} do not both apply in either order; overlapping files [{overlap_joined}]. They are not independent.",
                        a.name, b.name
                    )),
                }
            }
        }
        Ok(errors)
    }

    /// The given patch names filtered to known ones, as files in NNNN order.
    fn ordered_files(&self, names: &[String]) -> Vec<&Path> {
        let mut known: Vec<&str> = names
            .iter()
            .map(String::as_str)
            .filter(|nm| self.pos.contains_key(*nm))
            .collect();
        known.sort_by_key(|nm| self.pos[*nm]);
        known.into_iter().map(|nm| self.file(nm)).collect()
    }

    fn file(&self, name: &str) -> &Path {
        self.patches
            .iter()
            .find(|p| p.name == name)
            .expect("name checked against the series")
            .file
            .as_path()
    }
}

#[cfg(test)]
mod tests {
    use super::*;

    /// A real git repo with a base commit and a `format-patch` series, so the
    /// tests exercise the same `git am` / `format-patch` round-trip the
    /// production paths use. The repo doubles as the apply-test scratch:
    /// `reset_to_base` restores it before every trial.
    struct Fixture {
        dir: tempfile::TempDir,
        base: String,
    }

    impl Fixture {
        fn repo(&self) -> PathBuf {
            self.dir.path().join("repo")
        }

        fn patch_dir(&self) -> PathBuf {
            self.dir.path().join("patches")
        }

        fn new(base_files: &[(&str, &str)]) -> Self {
            let dir = tempfile::TempDir::new().unwrap();
            let repo = dir.path().join("repo");
            fs::create_dir_all(&repo).unwrap();
            fs::create_dir_all(dir.path().join("patches")).unwrap();
            git::run(&repo, &["init", "--quiet"]).unwrap();
            identity(&repo).unwrap();
            neutralize_config(&repo).unwrap();
            let fixture = Self { dir, base: String::new() };
            for (file, content) in base_files {
                fs::write(repo.join(file), content).unwrap();
            }
            fixture.commit("base");
            Self { base: git::stdout(&repo, &["rev-parse", "HEAD"]).unwrap(), ..fixture }
        }

        fn commit(&self, message: &str) {
            git::run(&self.repo(), &["add", "--all"]).unwrap();
            git::run(&self.repo(), &["commit", "--quiet", "-m", message]).unwrap();
        }

        fn write(&self, file: &str, content: &str) {
            fs::write(self.repo().join(file), content).unwrap();
        }

        /// Serialize `base..HEAD` into the patch dir, exactly as the publish
        /// path does, and return the series.
        fn export_series(&self) -> Vec<Patch> {
            let out = git::utf8(&self.patch_dir()).unwrap().to_owned();
            let range = format!("{}..HEAD", self.base);
            git::run(
                &self.repo(),
                &["format-patch", "--zero-commit", "--no-signature", "--no-stat", "-N", "-o", &out, &range],
            )
            .unwrap();
            patches_in(&self.patch_dir()).unwrap()
        }
    }

    /// Three commits and their exported series: A and B touch different files
    /// (independent), C touches the file A changed with the line A wrote in
    /// its context (depends on A).
    struct SparseSeries {
        fixture: Fixture,
        patches: Vec<Patch>,
    }

    fn sparse_fixture() -> SparseSeries {
        let fixture = Fixture::new(&[("alpha", "a1\na2\na3\n"), ("beta", "b1\nb2\nb3\n")]);
        fixture.write("alpha", "A\na2\na3\n");
        fixture.commit("alpha head\n\nReason: exercises the derive path.");
        fixture.write("beta", "B\nb2\nb3\n");
        fixture.commit("beta head\n\nReason: independent of alpha.");
        fixture.write("alpha", "A\na2\nC\n");
        fixture.commit("alpha tail\n\nReason: depends on alpha head via context.");
        let patches = fixture.export_series();
        SparseSeries { fixture, patches }
    }

    #[test]
    fn derives_sparse_edges_and_verifies() {
        let SparseSeries { fixture, patches } = sparse_fixture();
        assert_eq!(patches.len(), 3);

        let nodes = derive(&fixture.repo(), &fixture.base, &patches).unwrap();
        assert_eq!(nodes[0].deps, Vec::<String>::new());
        assert_eq!(nodes[1].deps, Vec::<String>::new());
        assert_eq!(nodes[2].deps, vec![nodes[0].patch.clone()]);

        // The derived DAG satisfies its own invariants.
        let doc = document(&fixture.base, nodes);
        let report = verify(&fixture.repo(), &fixture.base, &patches, &doc).unwrap();
        assert!(report.ok(), "unexpected violations: {:?}", report.errors);
    }

    #[test]
    fn verify_flags_undeclared_dependency() {
        let SparseSeries { fixture, patches } = sparse_fixture();
        let mut nodes = derive(&fixture.repo(), &fixture.base, &patches).unwrap();
        // Claim the dependent tail patch is a root: invariant (a) must fire.
        nodes[2].deps.clear();
        let doc = document(&fixture.base, nodes);
        let report = verify(&fixture.repo(), &fixture.base, &patches, &doc).unwrap();
        assert!(
            report.errors.iter().any(|e| e.contains("undeclared dependency")),
            "expected an undeclared-dependency violation, got {:?}",
            report.errors
        );
    }

    #[test]
    fn verify_flags_node_set_base_topo_and_unknown_deps() {
        let SparseSeries { fixture, patches } = sparse_fixture();
        let nodes = derive(&fixture.repo(), &fixture.base, &patches).unwrap();

        let mut doc = document("someotherbase", nodes);
        doc.nodes[0].deps = vec!["zzzz-not-a-patch.patch".to_owned()];
        doc.nodes[1].deps = vec![doc.nodes[2].patch.clone()];
        let extra_name = "9999-extra.patch".to_owned();
        doc.nodes.push(Node { patch: extra_name, deps: Vec::new() });

        let report = verify(&fixture.repo(), &fixture.base, &patches, &doc).unwrap();
        let all = report.errors.join("\n");
        assert!(all.contains("does not match the pinned base"), "{all}");
        assert!(all.contains("nodes for nonexistent patches"), "{all}");
        // Structural checks are gated on a coherent node set, so the bad deps
        // stay unreported until the extra node is removed.
        doc.nodes.pop();
        doc.base = fixture.base.clone();
        let report = verify(&fixture.repo(), &fixture.base, &patches, &doc).unwrap();
        let all = report.errors.join("\n");
        assert!(all.contains("declares unknown dependency"), "{all}");
        assert!(all.contains("NNNN order is not topological"), "{all}");
    }

    #[test]
    fn verify_flags_falsely_independent_pair() {
        // Two patches from the SAME base line, exported as one NNNN series:
        // each applies alone, but not stacked, so a DAG claiming both are
        // roots violates the commute invariant.
        let fixture = Fixture::new(&[("shared", "s1\ns2\ns3\n")]);
        fixture.write("shared", "first\ns2\ns3\n");
        fixture.commit("first edit\n\nReason: conflicts with the second edit.");
        let out = git::utf8(&fixture.patch_dir()).unwrap().to_owned();
        git::run(&fixture.repo(), &["format-patch", "--zero-commit", "--no-signature", "--no-stat", "-N", "-o", &out, "-1"]).unwrap();
        reset_to_base(&fixture.repo(), &fixture.base).unwrap();
        fixture.write("shared", "second\ns2\ns3\n");
        fixture.commit("second edit\n\nReason: conflicts with the first edit.");
        git::run(&fixture.repo(), &["format-patch", "--zero-commit", "--no-signature", "--no-stat", "-N", "--start-number", "2", "-o", &out, "-1"]).unwrap();

        let patches = patches_in(&fixture.patch_dir()).unwrap();
        assert_eq!(patches.len(), 2);
        let doc = document(
            &fixture.base,
            patches.iter().map(|p| Node { patch: p.name.clone(), deps: Vec::new() }).collect(),
        );
        let report = verify(&fixture.repo(), &fixture.base, &patches, &doc).unwrap();
        assert!(
            report.errors.iter().any(|e| e.contains("do not both apply in either order")),
            "expected a commute violation, got {:?}",
            report.errors
        );
    }

    #[test]
    fn closure_is_transitive_and_excludes_self() {
        let deps_of: BTreeMap<String, Vec<String>> = [
            ("a", vec![]),
            ("b", vec!["a"]),
            ("c", vec!["b"]),
            ("d", vec![]),
        ]
        .into_iter()
        .map(|(k, v)| (k.to_owned(), v.into_iter().map(str::to_owned).collect()))
        .collect();
        assert_eq!(closure(&deps_of, "c").unwrap(), vec!["b".to_owned(), "a".to_owned()]);
        assert_eq!(closure(&deps_of, "d").unwrap(), Vec::<String>::new());
        assert!(closure(&deps_of, "nope").is_err());
    }

    #[test]
    fn to_json_matches_committed_byte_format() {
        // The exact bytes `nu to json --indent 2` produced for the committed
        // dag.json files; regeneration must stay byte-identical or every
        // in-sync check would demand a rewrite.
        let doc = document(
            "0123abc",
            vec![
                Node { patch: "0001-a.patch".to_owned(), deps: vec![] },
                Node { patch: "0002-b.patch".to_owned(), deps: vec!["0001-a.patch".to_owned()] },
            ],
        );
        let expected = format!(
            "{{\n  \"comment\": \"{COMMENT}\",\n  \"base\": \"0123abc\",\n  \"nodes\": [\n    {{\n      \"patch\": \"0001-a.patch\",\n      \"deps\": []\n    }},\n    {{\n      \"patch\": \"0002-b.patch\",\n      \"deps\": [\n        \"0001-a.patch\"\n      ]\n    }}\n  ]\n}}\n"
        );
        assert_eq!(to_json(&doc).unwrap(), expected);
    }

    fn patch_with_body(dir: &Path, body: &str) -> PathBuf {
        let file = dir.join("0001-test.patch");
        let text = format!(
            "From 0000000000000000000000000000000000000000 Mon Sep 17 00:00:00 2001\nFrom: T <t@example.com>\nDate: Thu, 1 Jan 1970 00:00:00 +0000\nSubject: [PATCH] subject line\n\n{body}---\ndiff --git a/f b/f\nindex 0000000..1111111 100644\n--- a/f\n+++ b/f\n@@ -1 +1 @@\n-x\n+y\n"
        );
        fs::write(&file, text).unwrap();
        file
    }

    #[test]
    fn body_reason_ignores_trailers_and_bare_refs() {
        let dir = tempfile::TempDir::new().unwrap();
        let mute = patch_with_body(
            dir.path(),
            "Refs #123\n\nSigned-off-by: Someone <s@example.com>\nCo-authored-by: Bot <b@example.com>\n\n",
        );
        assert!(!body_has_reason(&mute).unwrap());

        let empty = patch_with_body(dir.path(), "");
        assert!(!body_has_reason(&empty).unwrap());

        let reasoned = patch_with_body(
            dir.path(),
            "The frobnicator misparses multi-line flags; pin the parser.\n\nRefs #123\n",
        );
        assert!(body_has_reason(&reasoned).unwrap());
    }

    #[test]
    fn footprint_reads_diff_headers() {
        let dir = tempfile::TempDir::new().unwrap();
        let file = dir.path().join("0001-fp.patch");
        fs::write(
            &file,
            "Subject: x\n\nbody\ndiff --git a/src/lib.rs b/src/lib.rs\n--- a/src/lib.rs\ndiff --git a/docs/a b/docs/a\ndiff --git a/src/lib.rs b/src/lib.rs\n",
        )
        .unwrap();
        assert_eq!(footprint(&file).unwrap(), vec!["src/lib.rs".to_owned(), "docs/a".to_owned()]);
    }

    #[test]
    fn patches_in_sorts_and_filters() {
        let dir = tempfile::TempDir::new().unwrap();
        fs::write(dir.path().join("0002-b.patch"), "x").unwrap();
        fs::write(dir.path().join("0001-a.patch"), "x").unwrap();
        fs::write(dir.path().join("dag.json"), "{}").unwrap();
        let names: Vec<String> = patches_in(dir.path()).unwrap().into_iter().map(|p| p.name).collect();
        assert_eq!(names, vec!["0001-a.patch".to_owned(), "0002-b.patch".to_owned()]);
    }
}
