#!/usr/bin/env bash
# Regenerate src/bindings.rs from the libghostty-vt C headers.
#
# The bindings are checked in so the crate builds without a bindgen toolchain
# and so review can see the FFI surface diff. Run this after the libghostty-vt
# headers change (a ghostty input bump), then commit the result.
#
# Usage (from the repo root):
#   nix shell nixpkgs#rust-bindgen nixpkgs#clang nixpkgs#rustfmt \
#     -c packages/vt/ix-vt-sys/regen-bindings.sh
#
# It builds libghostty-vt through the flake to locate the headers, so it needs a
# working Nix and the `ghostty` flake input.
set -euo pipefail

script_dir="$(cd "$(dirname "${BASH_SOURCE[0]}")" && pwd)"
repo_root="$(cd "$script_dir/../../.." && pwd)"

lib="$(nix build "$repo_root#libghostty-vt" --no-link --print-out-paths)"

# `--no-layout-tests` keeps the bindings portable across the Unix targets we
# support (the C ABI is identical; bindgen's size/offset asserts are generated
# for the host that ran bindgen). `--no-doc-comments` drops the Doxygen blocks
# so the file stays a compact symbol map; the safe API in ix-vt is the
# documented surface.
bindgen "$lib/include/ghostty/vt.h" \
  --allowlist-function 'ghostty_.*' \
  --allowlist-type 'Ghostty.*' \
  --allowlist-var 'GHOSTTY_.*' \
  --default-enum-style rust \
  --no-layout-tests \
  --no-doc-comments \
  --raw-line '/* Generated by rust-bindgen from ghostty/vt.h. Do not edit by hand.' \
  --raw-line ' * Regenerate with packages/vt/ix-vt-sys/regen-bindings.sh after a' \
  --raw-line ' * libghostty-vt header change (see that script for the exact flags). */' \
  --raw-line '#![allow(non_upper_case_globals, non_camel_case_types, non_snake_case)]' \
  --raw-line '#![allow(clippy::all, clippy::pedantic, clippy::nursery)]' \
  -- -I"$lib/include" \
  >"$script_dir/src/bindings.rs"

echo "wrote $script_dir/src/bindings.rs"
