"""Human-readable facts markdown per (user, project)."""

from __future__ import annotations

from datetime import datetime, timezone, UTC
from pathlib import Path

from .types import Item


def _date(ts: float | None) -> str:
    if not ts:
        return "?"
    return datetime.fromtimestamp(ts, tz=UTC).strftime("%Y-%m-%d")


def render(project: str, user: str, items: list[Item]) -> str:
    lines = [
        f"# Distilled facts — {project}",
        "",
        f"user: {user} · items: {len(items)} · generated by ix-distiller",
        "",
    ]
    for item in sorted(items, key=lambda i: i.last_updated, reverse=True):
        scope = f"user:{user}" if item.scope == "user" else "shared"
        lines += [
            f"## {item.title}",
            "",
            item.body,
            "",
            f"- id: `{item.id}` · outcome: {item.outcome} · scope: {scope}",
            f"- evidence: sessions {', '.join(item.sessions[:6]) or 'n/a'}"
            f" ({_date(item.evidence_from)} → {_date(item.evidence_to)})",
            "",
        ]
    return "\n".join(lines)


def write(out_dir: Path, user: str, slug: str, project: str, items: list[Item]) -> Path:
    path = out_dir / "facts" / user / f"{slug}.md"
    path.parent.mkdir(parents=True, exist_ok=True)
    path.write_text(render(project, user, items))
    return path
