"""Human-readable facts markdown per (user, project)."""

from __future__ import annotations

from datetime import datetime, timezone
from pathlib import Path


def _date(ts: float | None) -> str:
    if not ts:
        return "?"
    return datetime.fromtimestamp(ts, tz=timezone.utc).strftime("%Y-%m-%d")


def render(project: str, user: str, items: list[dict]) -> str:
    lines = [
        f"# Distilled facts — {project}",
        "",
        f"user: {user} · items: {len(items)} · generated by ix-distiller",
        "",
    ]
    for item in sorted(items, key=lambda i: i.get("last_updated", 0), reverse=True):
        scope = f"user:{user}" if item.get("scope") == "user" else "shared"
        lines += [
            f"## {item['title']}",
            "",
            item["body"],
            "",
            f"- id: `{item['id']}` · outcome: {item.get('outcome', 'mixed')} · scope: {scope}",
            f"- evidence: sessions {', '.join(item.get('sessions', [])[:6]) or 'n/a'}"
            f" ({_date(item.get('evidence_from'))} → {_date(item.get('evidence_to'))})",
            "",
        ]
    return "\n".join(lines)


def write(out_dir: Path, user: str, slug: str, project: str, items: list[dict]) -> Path:
    path = out_dir / "facts" / user / f"{slug}.md"
    path.parent.mkdir(parents=True, exist_ok=True)
    path.write_text(render(project, user, items))
    return path
