//! The team-notification block on an upstream PR.
//!
//! A PR this tool opens lives on someone else's repo, so nobody here is
//! watching it: GitHub notifies the author and the upstream maintainers, and
//! that is all. The nushell PR we opened on 2026-07-08 sat with two red
//! checks and no reply for weeks, which is what a PR nobody is subscribed to
//! looks like. An `@` mention is the only mechanism that subscribes a person
//! to a thread on a repo they do not own; there is no API to subscribe
//! someone else.
//!
//! So every PR carries a delimited block naming the org's humans. It is
//! delimited rather than appended so it can be RE-rendered: the roster
//! changes when people join or leave, and a PR opened last month should end
//! up with the same block as one opened today. Reconciliation is
//! change-gated on the rendered bytes, so a PR that already carries the
//! right block is never edited (see [`reconcile`]).
//!
//! The roster itself is generated, never hand-written: `upstream-sync
//! members --write` reads the org from GitHub into
//! `packages/upstream-sync/org-members.json`, committed like a lock file,
//! and the Nix wrapper bakes that path in as `UPSTREAM_SYNC_ORG_MEMBERS`.
//! Nix eval stays pure and a PR body never depends on a live API call.

use std::env;
use std::fs;
use std::path::{Path, PathBuf};

use color_eyre::eyre::{Result, WrapErr, eyre};
use serde::{Deserialize, Serialize};

use crate::cmd;
use crate::mapping::Slug;

/// Environment variable the Nix wrapper points at the generated roster.
pub const ORG_MEMBERS_ENV: &str = "UPSTREAM_SYNC_ORG_MEMBERS";

/// Fences around the rendered block. HTML comments so they are invisible in
/// the rendered PR body, and stable so the block can be found and replaced
/// rather than duplicated.
pub const BEGIN: &str = "<!-- ix:notify -->";
/// Closing fence; see [`BEGIN`].
pub const END: &str = "<!-- /ix:notify -->";

/// The generated org roster.
#[derive(Debug, Clone, Serialize, Deserialize)]
pub struct Roster {
    pub comment: String,
    pub org: String,
    #[serde(rename = "generatedAt")]
    pub generated_at: String,
    pub members: Vec<Member>,
}

/// One org member. `bot` is recorded at generation time so the reason a
/// login is skipped is visible in the committed file rather than recomputed
/// from a rule the reader cannot see.
#[derive(Debug, Clone, Serialize, Deserialize)]
pub struct Member {
    pub login: String,
    pub id: u64,
    pub bot: bool,
}

const SKELETON_COMMENT: &str = "Generated by `nix run .#upstream-sync -- members --write`, committed like a lock file. Do not hand-edit. Drives the @-mention block on upstream PRs (packages/upstream-sync/src/notify.rs).";

/// Is this login a machine account?
///
/// A mention of a bot notifies nobody, so bots are dropped from the block.
/// GitHub's member list cannot answer this: an App's login carries the
/// `[bot]` suffix, but a plain user account created for automation does not,
/// and this org has exactly that in `ix-ci-bot`. Hence the `-bot` suffix
/// rule, which is what excludes it. The first three cases mirror the bot
/// guard in `.github/actions/triggering-actor`.
#[must_use]
pub fn is_bot(login: &str) -> bool {
    let lower = login.to_lowercase();
    lower.ends_with("[bot]")
        || lower == "github-actions"
        || lower == "dependabot"
        || lower.ends_with("-bot")
}

/// Path to the roster: the caller override, else the wrapper environment.
///
/// # Errors
/// Fails when neither is set.
pub fn path(override_path: Option<&Path>) -> Result<PathBuf> {
    if let Some(p) = override_path {
        return Ok(p.to_path_buf());
    }
    env::var_os(ORG_MEMBERS_ENV).map(PathBuf::from).ok_or_else(|| {
        eyre!("no --members given and {ORG_MEMBERS_ENV} is unset; run via the Nix wrapper or pass --members")
    })
}

impl Roster {
    /// Load the roster from `p`.
    ///
    /// # Errors
    /// Fails when the file is unreadable or not the expected shape.
    pub fn load(p: &Path) -> Result<Self> {
        let raw = fs::read_to_string(p)
            .wrap_err_with(|| format!("cannot read roster {}", p.display()))?;
        serde_json::from_str(&raw).wrap_err_with(|| format!("cannot parse roster {}", p.display()))
    }

    /// Read the live org membership from GitHub.
    ///
    /// # Errors
    /// Fails when `gh` cannot be spawned or the org cannot be read. Unlike
    /// the drift report's degrading reads this one is strict: a partial
    /// roster would silently drop a person from every future PR.
    pub fn fetch(org: &str, stamp: String) -> Result<Self> {
        #[derive(Deserialize)]
        struct ApiMember {
            login: String,
            id: u64,
        }

        let res = cmd::complete(
            "gh",
            &[
                "api",
                "--paginate",
                &format!("orgs/{org}/members?per_page=100"),
            ],
        )?;
        if !res.ok() {
            return Err(eyre!(
                "upstream-sync: members: cannot read orgs/{org}/members: {}",
                res.stderr.trim()
            ));
        }
        // `gh api --paginate` concatenates one JSON array per page; parse
        // each so a second page is not silently dropped.
        let mut members: Vec<Member> = Vec::new();
        for page in res.stdout.replace("][", "]\u{1}[").split('\u{1}') {
            let parsed: Vec<ApiMember> = serde_json::from_str(page.trim())
                .wrap_err("cannot parse the org member list returned by gh")?;
            members.extend(parsed.into_iter().map(|m| Member {
                bot: is_bot(&m.login),
                login: m.login,
                id: m.id,
            }));
        }
        members.sort_by_key(|m| m.login.to_lowercase());
        if members.is_empty() {
            return Err(eyre!(
                "upstream-sync: members: orgs/{org}/members returned nobody; refusing to write an empty roster (a token without org scope reads as an empty org)"
            ));
        }
        Ok(Self {
            comment: SKELETON_COMMENT.to_owned(),
            org: org.to_owned(),
            generated_at: stamp,
            members,
        })
    }

    /// Serialize to the exact bytes we commit: pretty JSON, trailing newline.
    ///
    /// # Errors
    /// Fails only on a serializer error.
    pub fn to_bytes(&self) -> Result<String> {
        Ok(serde_json::to_string_pretty(self)? + "\n")
    }

    /// The logins that get mentioned: humans, in roster order.
    #[must_use]
    pub fn humans(&self) -> Vec<&str> {
        self.members
            .iter()
            .filter(|m| !m.bot)
            .map(|m| m.login.as_str())
            .collect()
    }

    /// The rendered block, or `None` when the roster has no humans (an
    /// all-bot org gets no block rather than an empty `/cc` line).
    #[must_use]
    pub fn block(&self) -> Option<String> {
        let humans = self.humans();
        if humans.is_empty() {
            return None;
        }
        let mentions = humans
            .iter()
            .map(|l| format!("@{l}"))
            .collect::<Vec<_>>()
            .join(" ");
        Some(format!(
            "{BEGIN}\n/cc {mentions} ({}), who maintain the fork this patch is carried in, so review comments reach someone who can act on them.\n{END}",
            self.org
        ))
    }
}

/// The block currently in `body`, if any.
#[must_use]
pub fn current(body: &str) -> Option<&str> {
    let start = body.find(BEGIN)?;
    let end = body[start..].find(END)? + start + END.len();
    Some(&body[start..end])
}

/// `body` with `block` present exactly once.
///
/// The existing block is replaced in place, or appended when there is none.
/// Replacing in place keeps the block where the author put it, which is what
/// makes re-rendering idempotent rather than additive.
#[must_use]
pub fn splice(body: &str, block: &str) -> String {
    current(body).map_or_else(
        || format!("{}\n\n{block}", body.trim_end()),
        |existing| body.replacen(existing, block, 1),
    )
}

/// What [`reconcile`] did to one PR.
#[derive(Debug, Clone, Copy, PartialEq, Eq)]
pub enum Outcome {
    /// The body already carried exactly this block; nothing was written.
    Unchanged,
    /// The body had no block; one was appended.
    Added,
    /// The body had a stale block; it was replaced.
    Updated,
}

impl Outcome {
    /// The word used in logs and the plan table.
    #[must_use]
    pub const fn word(self) -> &'static str {
        match self {
            Self::Unchanged => "unchanged",
            Self::Added => "added",
            Self::Updated => "updated",
        }
    }
}

/// Bring one PR's body in line with `block`.
///
/// Change-gated on the rendered bytes: an unchanged body costs one read and
/// no write, so this is safe to run against every tracked PR on every
/// scheduled run. `apply = false` computes the outcome and writes nothing.
///
/// # Errors
/// Fails when `gh` cannot be spawned, or when the PR cannot be read or
/// written.
pub fn reconcile(slug: &Slug, number: u64, block: &str, apply: bool) -> Result<Outcome> {
    #[derive(Deserialize)]
    struct View {
        body: String,
    }

    let repo = format!("{}/{}", slug.owner, slug.repo);
    let res = cmd::complete(
        "gh",
        &[
            "pr",
            "view",
            &number.to_string(),
            "--repo",
            &repo,
            "--json",
            "body",
        ],
    )?;
    if !res.ok() {
        return Err(eyre!(
            "upstream-sync: notify: cannot read {repo}#{number}: {}",
            res.stderr.trim()
        ));
    }
    let view: View = serde_json::from_str(&res.stdout)
        .wrap_err_with(|| format!("cannot parse the body of {repo}#{number}"))?;

    let outcome = match current(&view.body) {
        Some(existing) if existing == block => Outcome::Unchanged,
        Some(_) => Outcome::Updated,
        None => Outcome::Added,
    };
    if outcome == Outcome::Unchanged || !apply {
        return Ok(outcome);
    }

    let body = splice(&view.body, block);
    let res = cmd::complete(
        "gh",
        &[
            "pr",
            "edit",
            &number.to_string(),
            "--repo",
            &repo,
            "--body",
            &body,
        ],
    )?;
    if !res.ok() {
        return Err(eyre!(
            "upstream-sync: notify: cannot edit {repo}#{number}: {}",
            res.stderr.trim()
        ));
    }
    Ok(outcome)
}

#[cfg(test)]
mod tests {
    use super::*;

    fn roster(logins: &[&str]) -> Roster {
        Roster {
            comment: SKELETON_COMMENT.to_owned(),
            org: "indexable-inc".to_owned(),
            generated_at: "2026-01-01T00:00:00Z".to_owned(),
            members: logins
                .iter()
                .enumerate()
                .map(|(i, l)| Member {
                    login: (*l).to_owned(),
                    id: i as u64,
                    bot: is_bot(l),
                })
                .collect(),
        }
    }

    #[test]
    fn bots_are_dropped_including_the_suffix_only_one() {
        let r = roster(&["andrewgazelka", "ix-ci-bot", "dependabot", "renovate[bot]"]);
        assert_eq!(r.humans(), vec!["andrewgazelka"]);
    }

    #[test]
    fn an_all_bot_roster_renders_no_block() {
        assert!(roster(&["ix-ci-bot"]).block().is_none());
    }

    #[test]
    fn splice_appends_then_re_splices_in_place() {
        let block = roster(&["a", "b"]).block().unwrap();
        let once = splice("PR body.", &block);
        assert!(once.starts_with("PR body."));
        assert_eq!(current(&once), Some(block.as_str()));

        // Idempotent: re-splicing the same block is a no-op.
        assert_eq!(splice(&once, &block), once);

        // A roster change rewrites in place rather than appending a second
        // block, and leaves the trailing prose alone.
        let with_tail = format!("{once}\n\ntrailer line");
        let grown = roster(&["a", "b", "c"]).block().unwrap();
        let after = splice(&with_tail, &grown);
        assert_eq!(after.matches(BEGIN).count(), 1);
        assert!(after.ends_with("trailer line"));
        assert!(after.contains("@c"));
    }

    #[test]
    fn current_needs_both_fences() {
        assert!(current("no block here").is_none());
        assert!(current(&format!("{BEGIN}\nunterminated")).is_none());
    }
}
