//! `upstream-status.json`: tool-owned GENERATED live state, committed like a
//! lock file next to each series' `dag.json`.
//!
//! The series directory is the mapping's natural per-repo owner, so live
//! state is colocated with the patches and the DAG it tracks. Never
//! hand-written: per patch the tracked PR url + state + last-checked,
//! detected duplicate upstream PRs, and retirement status, plus an
//! append-only human-readable transition `log`.

use std::fs;
use std::path::{Path, PathBuf};

use anstream::println;
use chrono::Utc;
use color_eyre::eyre::{Result, WrapErr};
use indexmap::IndexMap;
use serde::{Deserialize, Serialize};

use crate::mapping::Fork;
use crate::style::{CYAN, GREEN, YELLOW, paint};

const SKELETON_COMMENT: &str = "Tool-owned live upstreaming state; generated by `nix run .#upstream-sync`, committed like a lock file. Do not hand-edit. Declarative intent (attempt/hold/never) lives in lib/fork-packages.nix.";

/// The status document. `patches` is keyed by patch file name and keeps
/// insertion order (the committed bytes must be stable across re-runs);
/// `log` is append-only.
#[derive(Debug, Serialize, Deserialize)]
pub struct Doc {
    pub comment: String,
    #[serde(rename = "lastChecked")]
    pub last_checked: Option<String>,
    pub patches: IndexMap<String, Entry>,
    pub log: Vec<String>,
}

/// One patch's live state.
#[derive(Debug, Clone, Serialize, Deserialize)]
pub struct Entry {
    pub upstream: String,
    pub pr: Option<Pr>,
    pub retired: bool,
    pub duplicates: Vec<Duplicate>,
}

/// A tracked PR's last-known state: open|draft|merged|closed.
#[derive(Debug, Clone, Serialize, Deserialize)]
pub struct Pr {
    pub url: String,
    pub number: u64,
    pub state: String,
    #[serde(rename = "checkedAt")]
    pub checked_at: String,
}

/// A detected possibly-duplicate upstream PR (field order matches gh's
/// alphabetical `--json` output, which the nu predecessor committed as-is).
#[derive(Debug, Clone, Serialize, Deserialize)]
pub struct Duplicate {
    pub number: u64,
    pub title: String,
    pub url: String,
}

/// The `%Y-%m-%dT%H:%M:%SZ` UTC stamp used everywhere in the status file.
#[must_use]
pub fn utc_stamp() -> String {
    Utc::now().format("%Y-%m-%dT%H:%M:%SZ").to_string()
}

/// Path to a fork's upstream-status.json: next to its dag.json.
#[must_use]
pub fn path(fork: &Fork) -> PathBuf {
    fork.patch_dir_abs().join("upstream-status.json")
}

impl Doc {
    /// Load a fork's status doc from `p`, or an empty skeleton if none
    /// exists yet.
    ///
    /// # Errors
    /// Fails when an existing file is unreadable or not the expected shape.
    pub fn load(p: &Path) -> Result<Self> {
        if !p.exists() {
            return Ok(Self {
                comment: SKELETON_COMMENT.to_owned(),
                last_checked: None,
                patches: IndexMap::new(),
                log: Vec::new(),
            });
        }
        let raw = fs::read_to_string(p).wrap_err_with(|| format!("cannot read {}", p.display()))?;
        serde_json::from_str(&raw).wrap_err_with(|| format!("cannot parse {}", p.display()))
    }

    /// Serialize to the exact bytes we commit: pretty JSON, two-space
    /// indent, trailing newline (matches dag.json's format owner).
    ///
    /// # Errors
    /// Fails only on a serializer error (never expected for this shape).
    pub fn to_bytes(&self) -> Result<String> {
        Ok(serde_json::to_string_pretty(self)? + "\n")
    }

    /// Append a timestamped transition line to the log (human-readable).
    pub fn append_log(&mut self, line: &str) {
        println!("  {}", paint(YELLOW, &format!("\u{2022} {line}")));
        self.log.push(format!("{} {line}", utc_stamp()));
    }

    /// Save unless dry-run, in which case just report the intent. Writing is
    /// idempotent: re-running with no upstream change reproduces the same
    /// bytes (only lastChecked + any new transitions move).
    ///
    /// # Errors
    /// Fails when the file cannot be written.
    pub fn save(&self, fork_name: &str, p: &Path, dry_run: bool) -> Result<()> {
        if dry_run {
            println!(
                "{}",
                paint(
                    CYAN,
                    &format!(
                        "upstream-sync: --dry-run: would write {fork_name} status to {}",
                        p.display()
                    )
                )
            );
            return Ok(());
        }
        fs::write(p, self.to_bytes()?).wrap_err_with(|| format!("cannot write {}", p.display()))?;
        println!(
            "{}",
            paint(
                GREEN,
                &format!("upstream-sync: {fork_name}: wrote {}", p.display())
            )
        );
        Ok(())
    }
}

#[cfg(test)]
mod tests {
    use super::*;

    #[test]
    fn skeleton_round_trips_to_committed_bytes() {
        let mut doc = Doc {
            comment: SKELETON_COMMENT.to_owned(),
            last_checked: Some("2026-01-01T00:00:00Z".to_owned()),
            patches: IndexMap::new(),
            log: Vec::new(),
        };
        doc.patches.insert(
            "0001-x.patch".to_owned(),
            Entry {
                upstream: "hold".to_owned(),
                pr: None,
                retired: false,
                duplicates: Vec::new(),
            },
        );
        let bytes = doc.to_bytes().unwrap();
        assert!(bytes.ends_with("}\n"));
        assert!(bytes.contains("\"lastChecked\": \"2026-01-01T00:00:00Z\""));
        // The nu predecessor committed exactly this per-entry shape.
        assert!(bytes.contains(
            "    \"0001-x.patch\": {\n      \"upstream\": \"hold\",\n      \"pr\": null,\n      \"retired\": false,\n      \"duplicates\": []\n    }"
        ));

        let reparsed: Doc = serde_json::from_str(&bytes).unwrap();
        assert_eq!(reparsed.to_bytes().unwrap(), bytes);
    }
}
