defmodule UnibindConformance.MixProject do
  use Mix.Project

  # Zero hex deps on purpose: the check builds offline (no fetchMixDeps
  # fixed-output pin to maintain) and everything under lib/ is generated by
  # `unibind-gen ex` from the built NIF's embedded IR.
  def project do
    [
      app: :unibind_conformance,
      version: "0.1.0",
      elixir: "~> 1.18",
      start_permanent: false,
      deps: []
    ]
  end

  def application do
    [extra_applications: []]
  end
end
