//! Render the ergonomic Swift overlay: records as Swift structs, errors as
//! thrown Swift enums, functions as lowerCamelCase free functions with
//! default arguments and documentation comments.

use std::fmt::Write as _;

use unibind_core::ir;

use crate::error;
use crate::function;
use crate::names;
use crate::repr::BoxShape;
use crate::swift_convert as convert;

/// The complete overlay source for one interface.
pub fn render(interface: &ir::Interface) -> String {
    let mut blocks = vec![header(interface)];
    for err in &interface.errors {
        blocks.push(error_enum(err));
    }
    for record in &interface.records {
        blocks.push(record_struct(record));
        blocks.push(record_bridging(record));
    }
    for func in &interface.functions {
        blocks.push(function_def(interface, func));
    }
    let mut out = blocks.join("\n\n");
    out.push('\n');
    out
}

fn header(interface: &ir::Interface) -> String {
    let mut out = String::from("// Generated by unibind's swift backend. Do not edit.");
    if !interface.docs.is_empty() {
        out.push_str("\n//");
        for line in &interface.docs {
            if line.is_empty() {
                out.push_str("\n//");
            } else {
                let _ = write!(out, "\n// {line}");
            }
        }
    }
    out
}

/// `/// ...` documentation comment lines at `indent` levels of four spaces.
fn doc_comment(lines: &[String], indent: usize) -> String {
    let pad = "    ".repeat(indent);
    let mut out = String::new();
    for line in lines {
        if line.is_empty() {
            let _ = writeln!(out, "{pad}///");
        } else {
            let _ = writeln!(out, "{pad}/// {line}");
        }
    }
    out
}

/// The public error enum, the `Error` conformance for the bridge-level
/// enum (swift-bridge generates the enum without one), and the converting
/// initializer the wrappers use when rethrowing.
fn error_enum(err: &ir::ErrorType) -> String {
    let name = &err.name;
    let bridge = error::bridge_ident(err).to_string();
    let mut out = doc_comment(&err.docs, 0);
    let _ = writeln!(out, "public enum {name}: Error {{");
    for variant in &err.variants {
        out.push_str(&doc_comment(&variant.docs, 1));
        let case = names::swift_name(&variant.name);
        let _ = writeln!(out, "    case {case}(message: String)");
    }
    out.push_str("}\n\n");
    let _ = writeln!(out, "extension {bridge}: Error {{}}\n");
    let _ = writeln!(out, "extension {name} {{");
    let _ = writeln!(out, "    init(__error: {bridge}) {{");
    let _ = writeln!(out, "        switch __error {{");
    for variant in &err.variants {
        let case = names::swift_name(&variant.name);
        let raw = &variant.name;
        let _ = writeln!(out, "        case .{raw}(let message):");
        let _ = writeln!(
            out,
            "            self = .{case}(message: message.toString())"
        );
    }
    out.push_str("        }\n    }\n}");
    out
}

fn record_struct(record: &ir::Record) -> String {
    let mut out = doc_comment(&record.docs, 0);
    let _ = writeln!(out, "public struct {} {{", record.name);
    let mut params = Vec::new();
    let mut assigns = Vec::new();
    for field in &record.fields {
        out.push_str(&doc_comment(&field.docs, 1));
        let name = names::swift_name(&field.name);
        let ty = convert::swift_type(&field.ty);
        let _ = writeln!(out, "    public var {name}: {ty}");
        params.push(format!("{name}: {ty}"));
        assigns.push(format!("        self.{name} = {name}"));
    }
    out.push('\n');
    let _ = writeln!(out, "    public init({}) {{", params.join(", "));
    for assign in &assigns {
        let _ = writeln!(out, "{assign}");
    }
    out.push_str("    }\n}");
    out
}

/// The conversions between the native struct and its bridge handle.
fn record_bridging(record: &ir::Record) -> String {
    let handle = BoxShape::Record(record.name.clone()).ident().to_string();
    let ctor = format!("__unibind_new_{}", names::to_snake(&record.name));
    let mut out = String::new();
    let _ = writeln!(out, "extension {} {{", record.name);
    let _ = writeln!(out, "    init(__handle: {handle}) {{");
    for field in &record.fields {
        let name = names::swift_name(&field.name);
        let getter = format!("__handle.{}()", field.name);
        let value = convert::from_bridge(&field.ty, &getter);
        let _ = writeln!(out, "        self.{name} = {value}");
    }
    out.push_str("    }\n\n");
    let _ = writeln!(out, "    func __unibindHandle() -> {handle} {{");
    let mut args = Vec::new();
    for field in &record.fields {
        let name = names::swift_name(&field.name);
        let conversion = convert::to_bridge(
            &field.ty,
            &format!("self.{name}"),
            &format!("__field_{}", field.name),
            2,
        );
        for line in conversion.lines {
            let _ = writeln!(out, "{line}");
        }
        args.push(conversion.expr);
    }
    let _ = writeln!(out, "        return {ctor}({})", args.join(", "));
    out.push_str("    }\n}");
    out
}

fn function_def(interface: &ir::Interface, func: &ir::Function) -> String {
    let name = names::swift_name(&func.name);
    let wrapper = function::wrapper_ident(func).to_string();

    let mut doc_lines = func.docs.clone();
    if let Some(throws) = &func.throws {
        if !doc_lines.is_empty() {
            doc_lines.push(String::new());
        }
        doc_lines.push(format!("- Throws: `{throws}`."));
    }
    let mut out = doc_comment(&doc_lines, 0);

    let params: Vec<String> = func.args.iter().map(parameter).collect();
    let throws_kw = if func.throws.is_some() { " throws" } else { "" };
    let ret = func
        .ret
        .as_ref()
        .map(|ty| format!(" -> {}", convert::swift_type(ty)))
        .unwrap_or_default();
    let _ = writeln!(
        out,
        "public func {name}({}){throws_kw}{ret} {{",
        params.join(", ")
    );

    let indent = if func.throws.is_some() { 2 } else { 1 };
    let pad = "    ".repeat(indent);
    let mut body = Vec::new();
    let mut args = Vec::new();
    for arg in &func.args {
        let native = names::swift_name(&arg.name);
        let conversion =
            convert::to_bridge(&arg.ty, &native, &format!("__arg_{}", arg.name), indent);
        body.extend(conversion.lines);
        args.push(conversion.expr);
    }
    let try_kw = if func.throws.is_some() { "try " } else { "" };
    let call = format!("{try_kw}{wrapper}({})", args.join(", "));
    // A throwing Ok type the bridge cannot name rides an opaque carrier box
    // (see `repr::throws_ok_box`); drain it before converting.
    let boxed_ok = func.throws.is_some()
        && func
            .ret
            .as_ref()
            .is_some_and(|ty| crate::repr::throws_ok_box(ty).is_some());
    match &func.ret {
        None => body.push(format!("{pad}{call}")),
        Some(ty) => {
            body.push(format!("{pad}let __result = {call}"));
            let source = if boxed_ok { "__result.value()" } else { "__result" };
            let value = convert::from_bridge(ty, source);
            body.push(format!("{pad}return {value}"));
        }
    }

    if let Some(throws) = &func.throws {
        let bridge_err = bridge_error_name(interface, throws);
        out.push_str("    do {\n");
        for line in &body {
            let _ = writeln!(out, "{line}");
        }
        out.push_str("    ");
        let _ = writeln!(out, "}} catch let __error as {bridge_err} {{");
        let _ = writeln!(out, "        throw {throws}(__error: __error)");
        out.push_str("    }\n}");
    } else {
        for line in &body {
            let _ = writeln!(out, "{line}");
        }
        out.push('}');
    }
    out
}

fn parameter(arg: &ir::Arg) -> String {
    let name = names::swift_name(&arg.name);
    let ty = convert::swift_type(&arg.ty);
    if let Some(default) = &arg.default {
        return format!("{name}: {ty} = {}", convert::literal(default));
    }
    // `Option` arguments without an explicit default get `nil`, mirroring
    // the Python backend's `= None`.
    if matches!(arg.ty, ir::Type::Option(_)) {
        return format!("{name}: {ty} = nil");
    }
    format!("{name}: {ty}")
}

/// The bridge-level enum name a `throws` maps to.
fn bridge_error_name(interface: &ir::Interface, throws: &str) -> String {
    interface
        .errors
        .iter()
        .find(|err| err.name == throws)
        .map_or_else(
            || format!("__Unibind{throws}"),
            |err| error::bridge_ident(err).to_string(),
        )
}
