// Generated by unibind; do not edit.
package com.example.sample;

import java.lang.foreign.Arena;
import java.lang.foreign.FunctionDescriptor;
import java.lang.foreign.Linker;
import java.lang.foreign.MemorySegment;
import java.lang.foreign.SymbolLookup;
import java.lang.foreign.ValueLayout;
import java.lang.invoke.MethodHandle;
import java.nio.charset.StandardCharsets;
import java.nio.file.Path;
import java.util.ArrayList;
import java.util.Arrays;
import java.util.HashMap;
import java.util.List;
import java.util.Map;
import java.util.function.BiConsumer;
import java.util.function.Function;

/**
 * A sample boundary exercising the jvm surface.
 *
 * <p>Generated by unibind from the Rust module {@code _sample}. Values cross a
 * C ABI in unibind's length-prefixed little-endian wire format; unsigned Rust
 * integers reinterpret as the signed Java type of the same width.
 *
 * <p>The native library resolves through the {@code unibind.library.sample} system
 * property (an explicit path) when set, else through {@code System.mapLibraryName("sample")}
 * on the library search path. The JVM needs
 * {@code --enable-native-access=ALL-UNNAMED} to bind the symbols.
 */
public final class Sample {
    private Sample() {}

    /**
     * Fetch rows.
     *
     * Docs become javadoc.
     *
     * @throws SampleException on the failure the native side reports
     */
    public static List<Line> rows(String store, long limit, String root) throws SampleException {
        UnibindWire args = new UnibindWire();
        args.writeString(store);
        args.writeLong(limit);
        if (root == null) {
            args.writeBool(false);
        } else {
            args.writeBool(true);
            args.writeString(root);
        }
        UnibindReader reply = call(H_ROWS, args);
        int status = Byte.toUnsignedInt(reply.readByte());
        if (status == 1) {
            int variant = reply.readInt();
            String message = reply.readString();
            reply.finish();
            throw sampleException(variant, message);
        }
        expectOk(status, reply);
        List<Line> result = readList(reply, w0 -> readLine(w0));
        reply.finish();
        return result;
    }

    /**
     * Calls {@link #rows(String, long, String)} with {@code root} defaulted.
     */
    public static List<Line> rows(String store, long limit) throws SampleException {
        return rows(store, limit, null);
    }

    /**
     * Calls {@link #rows(String, long, String)} with {@code limit}, {@code root} defaulted.
     */
    public static List<Line> rows(String store) throws SampleException {
        return rows(store, 10L, null);
    }

    /**
     * Persist a row under a path, returning the bytes written.
     */
    public static long store(Path home, Line row, byte[] payload) {
        UnibindWire args = new UnibindWire();
        args.writeString(home.toString());
        writeLine(args, row);
        args.writeBytes(payload);
        UnibindReader reply = call(H_STORE, args);
        int status = Byte.toUnsignedInt(reply.readByte());
        expectOk(status, reply);
        long result = reply.readLong();
        reply.finish();
        return result;
    }

    /**
     * Resolve a label.
     */
    public static String labelOf(long key, String prefix, boolean trim) {
        UnibindWire args = new UnibindWire();
        args.writeLong(key);
        args.writeString(prefix);
        args.writeBool(trim);
        UnibindReader reply = call(H_LABEL, args);
        int status = Byte.toUnsignedInt(reply.readByte());
        expectOk(status, reply);
        String result = reply.readString();
        reply.finish();
        return result;
    }

    /**
     * Calls {@link #labelOf(long, String, boolean)} with {@code trim} defaulted.
     */
    public static String labelOf(long key, String prefix) {
        return labelOf(key, prefix, true);
    }

    /**
     * Calls {@link #labelOf(long, String, boolean)} with {@code prefix}, {@code trim} defaulted.
     */
    public static String labelOf(long key) {
        return labelOf(key, "row-", true);
    }

    /**
     * Drop everything.
     *
     * @throws SampleException on the failure the native side reports
     */
    public static void clear() throws SampleException {
        UnibindWire args = new UnibindWire();
        UnibindReader reply = call(H_CLEAR, args);
        int status = Byte.toUnsignedInt(reply.readByte());
        if (status == 1) {
            int variant = reply.readInt();
            String message = reply.readString();
            reply.finish();
            throw sampleException(variant, message);
        }
        expectOk(status, reply);
        reply.finish();
    }

    /**
     * A row.
     *
     * @param id Identifier.
     */
    public record Line(long id, String name, Map<String, Double> weights, Path home) {}

    private static Line readLine(UnibindReader reader) {
        return new Line(
            reader.readLong(),
            reader.readString(),
            readMap(reader, w0 -> w0.readString(), w0 -> w0.readDouble()),
            (reader.readBool() ? Path.of(reader.readString()) : null));
    }

    private static void writeLine(UnibindWire wire, Line value) {
        wire.writeLong(value.id());
        wire.writeString(value.name());
        writeMap(wire, value.weights(), (w0, k0) -> {
            w0.writeString(k0);
        }, (w0, v0) -> {
            w0.writeDouble(v0);
        });
        if (value.home() == null) {
            wire.writeBool(false);
        } else {
            wire.writeBool(true);
            wire.writeString(value.home().toString());
        }
    }

    /**
     * Boundary failures.
     */
    public static class SampleException extends IllegalStateException {
        SampleException(String message) {
            super(message);
        }

        /**
         * The store is gone.
         */
        public static final class MissingStoreException extends SampleException {
            MissingStoreException(String message) {
                super(message);
            }
        }

        /**
         * Bad input.
         */
        public static final class InvalidException extends SampleException {
            InvalidException(String message) {
                super(message);
            }
        }
    }

    private static SampleException sampleException(int variant, String message) {
        return switch (variant) {
            case 0 -> new SampleException.MissingStoreException(message);
            case 1 -> new SampleException.InvalidException(message);
            default -> new SampleException(message);
        };
    }

    /**
     * A panic crossing from the native side; the message carries the
     * panic text. Always a bug in the native library, never an API
     * error.
     */
    public static final class PanicException extends RuntimeException {
        PanicException(String message) {
            super(message);
        }
    }

    private static final Linker LINKER = Linker.nativeLinker();
    private static final FunctionDescriptor CALL_DESC =
        FunctionDescriptor.ofVoid(ValueLayout.ADDRESS, ValueLayout.JAVA_LONG, ValueLayout.ADDRESS);
    private static final FunctionDescriptor FREE_DESC =
        FunctionDescriptor.ofVoid(ValueLayout.ADDRESS, ValueLayout.JAVA_LONG, ValueLayout.JAVA_LONG);
    private static final SymbolLookup LIBRARY = library();
    private static final MethodHandle H_FREE =
        handle("unibind_jvm__sample_free", FREE_DESC);
    private static final MethodHandle H_ROWS =
        handle("unibind_jvm__sample_rows", CALL_DESC);
    private static final MethodHandle H_STORE =
        handle("unibind_jvm__sample_store", CALL_DESC);
    private static final MethodHandle H_LABEL =
        handle("unibind_jvm__sample_label", CALL_DESC);
    private static final MethodHandle H_CLEAR =
        handle("unibind_jvm__sample_clear", CALL_DESC);

    private static SymbolLookup library() {
        String explicit = System.getProperty("unibind.library.sample");
        String name = explicit != null ? explicit : System.mapLibraryName("sample");
        return SymbolLookup.libraryLookup(name, Arena.global());
    }

    private static MethodHandle handle(String symbol, FunctionDescriptor descriptor) {
        MemorySegment address = LIBRARY.find(symbol)
            .orElseThrow(() -> new IllegalStateException("unibind: missing symbol " + symbol));
        return LINKER.downcallHandle(address, descriptor);
    }

    private static UnibindReader call(MethodHandle handle, UnibindWire args) {
        try (Arena arena = Arena.ofConfined()) {
            MemorySegment argsSegment;
            if (args.length() == 0) {
                argsSegment = MemorySegment.NULL;
            } else {
                argsSegment = arena.allocate(args.length());
                MemorySegment.copy(args.bytes(), 0, argsSegment, ValueLayout.JAVA_BYTE, 0, args.length());
            }
            MemorySegment out = arena.allocate(24, 8);
            handle.invokeExact(argsSegment, (long) args.length(), out);
            long ptr = out.get(ValueLayout.JAVA_LONG, 0);
            long len = out.get(ValueLayout.JAVA_LONG, 8);
            long cap = out.get(ValueLayout.JAVA_LONG, 16);
            byte[] reply;
            try {
                reply = len == 0
                    ? new byte[0]
                    : MemorySegment.ofAddress(ptr).reinterpret(len).toArray(ValueLayout.JAVA_BYTE);
            } finally {
                H_FREE.invokeExact(MemorySegment.ofAddress(ptr), len, cap);
            }
            return new UnibindReader(reply);
        } catch (RuntimeException | Error e) {
            throw e;
        } catch (Throwable t) {
            throw new IllegalStateException("unibind: native call failed", t);
        }
    }

    private static void expectOk(int status, UnibindReader reply) {
        if (status == 0) {
            return;
        }
        if (status == 255) {
            String message = reply.readString();
            reply.finish();
            throw new PanicException(message);
        }
        throw new IllegalStateException("unibind: unexpected reply status " + status);
    }

    private static <T> List<T> readList(UnibindReader reader, Function<UnibindReader, T> element) {
        int count = reader.readCount();
        List<T> items = new ArrayList<>(count);
        for (int i = 0; i < count; i++) {
            items.add(element.apply(reader));
        }
        return items;
    }

    private static <T> void writeList(UnibindWire wire, List<T> items, BiConsumer<UnibindWire, T> element) {
        wire.writeInt(items.size());
        for (T item : items) {
            element.accept(wire, item);
        }
    }

    private static <K, V> Map<K, V> readMap(
            UnibindReader reader, Function<UnibindReader, K> key, Function<UnibindReader, V> value) {
        int count = reader.readCount();
        Map<K, V> entries = new HashMap<>(count);
        for (int i = 0; i < count; i++) {
            K decodedKey = key.apply(reader);
            entries.put(decodedKey, value.apply(reader));
        }
        return entries;
    }

    private static <K, V> void writeMap(
            UnibindWire wire, Map<K, V> entries, BiConsumer<UnibindWire, K> key, BiConsumer<UnibindWire, V> value) {
        wire.writeInt(entries.size());
        for (Map.Entry<K, V> entry : entries.entrySet()) {
            key.accept(wire, entry.getKey());
            value.accept(wire, entry.getValue());
        }
    }

    private static final class UnibindWire {
        private byte[] buffer = new byte[32];
        private int length;

        int length() {
            return length;
        }

        byte[] bytes() {
            return buffer;
        }

        private void ensure(int extra) {
            int needed = length + extra;
            if (needed > buffer.length) {
                buffer = Arrays.copyOf(buffer, Math.max(needed, buffer.length * 2));
            }
        }

        void writeBool(boolean value) {
            writeByte(value ? (byte) 1 : (byte) 0);
        }

        void writeByte(byte value) {
            ensure(1);
            buffer[length] = value;
            length += 1;
        }

        void writeShort(short value) {
            ensure(2);
            buffer[length] = (byte) value;
            buffer[length + 1] = (byte) (value >>> 8);
            length += 2;
        }

        void writeInt(int value) {
            ensure(4);
            buffer[length] = (byte) value;
            buffer[length + 1] = (byte) (value >>> 8);
            buffer[length + 2] = (byte) (value >>> 16);
            buffer[length + 3] = (byte) (value >>> 24);
            length += 4;
        }

        void writeLong(long value) {
            writeInt((int) value);
            writeInt((int) (value >>> 32));
        }

        void writeFloat(float value) {
            writeInt(Float.floatToRawIntBits(value));
        }

        void writeDouble(double value) {
            writeLong(Double.doubleToRawLongBits(value));
        }

        void writeString(String value) {
            writeBytes(value.getBytes(StandardCharsets.UTF_8));
        }

        void writeBytes(byte[] value) {
            writeInt(value.length);
            ensure(value.length);
            System.arraycopy(value, 0, buffer, length, value.length);
            length += value.length;
        }
    }

    private static final class UnibindReader {
        private final byte[] buffer;
        private int position;

        UnibindReader(byte[] buffer) {
            this.buffer = buffer;
        }

        private void need(int count) {
            if (count > buffer.length - position) {
                throw new IllegalStateException("unibind: truncated reply");
            }
        }

        boolean readBool() {
            byte value = readByte();
            if (value == 0) {
                return false;
            }
            if (value == 1) {
                return true;
            }
            throw new IllegalStateException("unibind: malformed bool " + value);
        }

        byte readByte() {
            need(1);
            byte value = buffer[position];
            position += 1;
            return value;
        }

        short readShort() {
            need(2);
            short value = (short) ((buffer[position] & 0xFF) | ((buffer[position + 1] & 0xFF) << 8));
            position += 2;
            return value;
        }

        int readInt() {
            need(4);
            int value = (buffer[position] & 0xFF)
                | ((buffer[position + 1] & 0xFF) << 8)
                | ((buffer[position + 2] & 0xFF) << 16)
                | ((buffer[position + 3] & 0xFF) << 24);
            position += 4;
            return value;
        }

        long readLong() {
            long low = readInt() & 0xFFFF_FFFFL;
            long high = readInt();
            return low | (high << 32);
        }

        float readFloat() {
            return Float.intBitsToFloat(readInt());
        }

        double readDouble() {
            return Double.longBitsToDouble(readLong());
        }

        int readCount() {
            int count = readInt();
            if (count < 0) {
                throw new IllegalStateException(
                    "unibind: count overflows int: " + Integer.toUnsignedString(count));
            }
            return count;
        }

        String readString() {
            return new String(readBytes(), StandardCharsets.UTF_8);
        }

        byte[] readBytes() {
            int count = readCount();
            need(count);
            byte[] value = Arrays.copyOfRange(buffer, position, position + count);
            position += count;
            return value;
        }

        void finish() {
            if (position != buffer.length) {
                throw new IllegalStateException(
                    "unibind: " + (buffer.length - position) + " unread reply bytes");
            }
        }
    }
}

