/* automatically generated by rust-bindgen 0.72.1 */

/* Generated by rust-bindgen from ghostty/vt.h. Do not edit by hand.
 * Regenerate with packages/vt/ix-vt-sys/regen-bindings.sh after a
 * libghostty-vt header change (see that script for the exact flags). */
#![allow(non_upper_case_globals, non_camel_case_types, non_snake_case)]
#![allow(clippy::all, clippy::pedantic, clippy::nursery)]

pub const GHOSTTY_COLOR_NAMED_BLACK: u32 = 0;
pub const GHOSTTY_COLOR_NAMED_RED: u32 = 1;
pub const GHOSTTY_COLOR_NAMED_GREEN: u32 = 2;
pub const GHOSTTY_COLOR_NAMED_YELLOW: u32 = 3;
pub const GHOSTTY_COLOR_NAMED_BLUE: u32 = 4;
pub const GHOSTTY_COLOR_NAMED_MAGENTA: u32 = 5;
pub const GHOSTTY_COLOR_NAMED_CYAN: u32 = 6;
pub const GHOSTTY_COLOR_NAMED_WHITE: u32 = 7;
pub const GHOSTTY_COLOR_NAMED_BRIGHT_BLACK: u32 = 8;
pub const GHOSTTY_COLOR_NAMED_BRIGHT_RED: u32 = 9;
pub const GHOSTTY_COLOR_NAMED_BRIGHT_GREEN: u32 = 10;
pub const GHOSTTY_COLOR_NAMED_BRIGHT_YELLOW: u32 = 11;
pub const GHOSTTY_COLOR_NAMED_BRIGHT_BLUE: u32 = 12;
pub const GHOSTTY_COLOR_NAMED_BRIGHT_MAGENTA: u32 = 13;
pub const GHOSTTY_COLOR_NAMED_BRIGHT_CYAN: u32 = 14;
pub const GHOSTTY_COLOR_NAMED_BRIGHT_WHITE: u32 = 15;
pub const GHOSTTY_MODS_SHIFT: u32 = 1;
pub const GHOSTTY_MODS_CTRL: u32 = 2;
pub const GHOSTTY_MODS_ALT: u32 = 4;
pub const GHOSTTY_MODS_SUPER: u32 = 8;
pub const GHOSTTY_MODS_CAPS_LOCK: u32 = 16;
pub const GHOSTTY_MODS_NUM_LOCK: u32 = 32;
pub const GHOSTTY_MODS_SHIFT_SIDE: u32 = 64;
pub const GHOSTTY_MODS_CTRL_SIDE: u32 = 128;
pub const GHOSTTY_MODS_ALT_SIDE: u32 = 256;
pub const GHOSTTY_MODS_SUPER_SIDE: u32 = 512;
pub const GHOSTTY_KITTY_KEY_DISABLED: u32 = 0;
pub const GHOSTTY_KITTY_KEY_DISAMBIGUATE: u32 = 1;
pub const GHOSTTY_KITTY_KEY_REPORT_EVENTS: u32 = 2;
pub const GHOSTTY_KITTY_KEY_REPORT_ALTERNATES: u32 = 4;
pub const GHOSTTY_KITTY_KEY_REPORT_ALL: u32 = 8;
pub const GHOSTTY_KITTY_KEY_REPORT_ASSOCIATED: u32 = 16;
pub const GHOSTTY_KITTY_KEY_ALL: u32 = 31;
#[repr(i32)]
#[derive(Debug, Copy, Clone, Hash, PartialEq, Eq)]
pub enum GhosttyResult {
    GHOSTTY_SUCCESS = 0,
    GHOSTTY_OUT_OF_MEMORY = -1,
    GHOSTTY_INVALID_VALUE = -2,
    GHOSTTY_OUT_OF_SPACE = -3,
}
#[repr(C)]
#[derive(Debug, Copy, Clone)]
pub struct GhosttyAllocatorVtable {
    pub alloc: ::std::option::Option<
        unsafe extern "C" fn(
            ctx: *mut ::std::os::raw::c_void,
            len: usize,
            alignment: u8,
            ret_addr: usize,
        ) -> *mut ::std::os::raw::c_void,
    >,
    pub resize: ::std::option::Option<
        unsafe extern "C" fn(
            ctx: *mut ::std::os::raw::c_void,
            memory: *mut ::std::os::raw::c_void,
            memory_len: usize,
            alignment: u8,
            new_len: usize,
            ret_addr: usize,
        ) -> bool,
    >,
    pub remap: ::std::option::Option<
        unsafe extern "C" fn(
            ctx: *mut ::std::os::raw::c_void,
            memory: *mut ::std::os::raw::c_void,
            memory_len: usize,
            alignment: u8,
            new_len: usize,
            ret_addr: usize,
        ) -> *mut ::std::os::raw::c_void,
    >,
    pub free: ::std::option::Option<
        unsafe extern "C" fn(
            ctx: *mut ::std::os::raw::c_void,
            memory: *mut ::std::os::raw::c_void,
            memory_len: usize,
            alignment: u8,
            ret_addr: usize,
        ),
    >,
}
#[repr(C)]
#[derive(Debug, Copy, Clone)]
pub struct GhosttyAllocator {
    pub ctx: *mut ::std::os::raw::c_void,
    pub vtable: *const GhosttyAllocatorVtable,
}
#[repr(u32)]
#[derive(Debug, Copy, Clone, Hash, PartialEq, Eq)]
pub enum GhosttyOptimizeMode {
    GHOSTTY_OPTIMIZE_DEBUG = 0,
    GHOSTTY_OPTIMIZE_RELEASE_SAFE = 1,
    GHOSTTY_OPTIMIZE_RELEASE_SMALL = 2,
    GHOSTTY_OPTIMIZE_RELEASE_FAST = 3,
}
#[repr(u32)]
#[derive(Debug, Copy, Clone, Hash, PartialEq, Eq)]
pub enum GhosttyBuildInfo {
    GHOSTTY_BUILD_INFO_INVALID = 0,
    GHOSTTY_BUILD_INFO_SIMD = 1,
    GHOSTTY_BUILD_INFO_KITTY_GRAPHICS = 2,
    GHOSTTY_BUILD_INFO_TMUX_CONTROL_MODE = 3,
    GHOSTTY_BUILD_INFO_OPTIMIZE = 4,
}
unsafe extern "C" {
    pub fn ghostty_build_info(
        data: GhosttyBuildInfo,
        out: *mut ::std::os::raw::c_void,
    ) -> GhosttyResult;
}
#[repr(C)]
#[derive(Debug, Copy, Clone)]
pub struct GhosttyColorRgb {
    pub r: u8,
    pub g: u8,
    pub b: u8,
}
pub type GhosttyColorPaletteIndex = u8;
unsafe extern "C" {
    pub fn ghostty_color_rgb_get(color: GhosttyColorRgb, r: *mut u8, g: *mut u8, b: *mut u8);
}
#[repr(u32)]
#[derive(Debug, Copy, Clone, Hash, PartialEq, Eq)]
pub enum GhosttyFocusEvent {
    GHOSTTY_FOCUS_GAINED = 0,
    GHOSTTY_FOCUS_LOST = 1,
}
unsafe extern "C" {
    pub fn ghostty_focus_encode(
        event: GhosttyFocusEvent,
        buf: *mut ::std::os::raw::c_char,
        buf_len: usize,
        out_written: *mut usize,
    ) -> GhosttyResult;
}
pub type GhosttyMode = u16;
#[repr(u32)]
#[derive(Debug, Copy, Clone, Hash, PartialEq, Eq)]
pub enum GhosttyModeReportState {
    GHOSTTY_MODE_REPORT_NOT_RECOGNIZED = 0,
    GHOSTTY_MODE_REPORT_SET = 1,
    GHOSTTY_MODE_REPORT_RESET = 2,
    GHOSTTY_MODE_REPORT_PERMANENTLY_SET = 3,
    GHOSTTY_MODE_REPORT_PERMANENTLY_RESET = 4,
}
unsafe extern "C" {
    pub fn ghostty_mode_report_encode(
        mode: GhosttyMode,
        state: GhosttyModeReportState,
        buf: *mut ::std::os::raw::c_char,
        buf_len: usize,
        out_written: *mut usize,
    ) -> GhosttyResult;
}
pub type GhosttyCell = u64;
pub type GhosttyRow = u64;
#[repr(u32)]
#[derive(Debug, Copy, Clone, Hash, PartialEq, Eq)]
pub enum GhosttyCellContentTag {
    GHOSTTY_CELL_CONTENT_CODEPOINT = 0,
    GHOSTTY_CELL_CONTENT_CODEPOINT_GRAPHEME = 1,
    GHOSTTY_CELL_CONTENT_BG_COLOR_PALETTE = 2,
    GHOSTTY_CELL_CONTENT_BG_COLOR_RGB = 3,
}
#[repr(u32)]
#[derive(Debug, Copy, Clone, Hash, PartialEq, Eq)]
pub enum GhosttyCellWide {
    GHOSTTY_CELL_WIDE_NARROW = 0,
    GHOSTTY_CELL_WIDE_WIDE = 1,
    GHOSTTY_CELL_WIDE_SPACER_TAIL = 2,
    GHOSTTY_CELL_WIDE_SPACER_HEAD = 3,
}
#[repr(u32)]
#[derive(Debug, Copy, Clone, Hash, PartialEq, Eq)]
pub enum GhosttyCellSemanticContent {
    GHOSTTY_CELL_SEMANTIC_OUTPUT = 0,
    GHOSTTY_CELL_SEMANTIC_INPUT = 1,
    GHOSTTY_CELL_SEMANTIC_PROMPT = 2,
}
#[repr(u32)]
#[derive(Debug, Copy, Clone, Hash, PartialEq, Eq)]
pub enum GhosttyCellData {
    GHOSTTY_CELL_DATA_INVALID = 0,
    GHOSTTY_CELL_DATA_CODEPOINT = 1,
    GHOSTTY_CELL_DATA_CONTENT_TAG = 2,
    GHOSTTY_CELL_DATA_WIDE = 3,
    GHOSTTY_CELL_DATA_HAS_TEXT = 4,
    GHOSTTY_CELL_DATA_HAS_STYLING = 5,
    GHOSTTY_CELL_DATA_STYLE_ID = 6,
    GHOSTTY_CELL_DATA_HAS_HYPERLINK = 7,
    GHOSTTY_CELL_DATA_PROTECTED = 8,
    GHOSTTY_CELL_DATA_SEMANTIC_CONTENT = 9,
    GHOSTTY_CELL_DATA_COLOR_PALETTE = 10,
    GHOSTTY_CELL_DATA_COLOR_RGB = 11,
}
#[repr(u32)]
#[derive(Debug, Copy, Clone, Hash, PartialEq, Eq)]
pub enum GhosttyRowSemanticPrompt {
    GHOSTTY_ROW_SEMANTIC_NONE = 0,
    GHOSTTY_ROW_SEMANTIC_PROMPT = 1,
    GHOSTTY_ROW_SEMANTIC_PROMPT_CONTINUATION = 2,
}
#[repr(u32)]
#[derive(Debug, Copy, Clone, Hash, PartialEq, Eq)]
pub enum GhosttyRowData {
    GHOSTTY_ROW_DATA_INVALID = 0,
    GHOSTTY_ROW_DATA_WRAP = 1,
    GHOSTTY_ROW_DATA_WRAP_CONTINUATION = 2,
    GHOSTTY_ROW_DATA_GRAPHEME = 3,
    GHOSTTY_ROW_DATA_STYLED = 4,
    GHOSTTY_ROW_DATA_HYPERLINK = 5,
    GHOSTTY_ROW_DATA_SEMANTIC_PROMPT = 6,
    GHOSTTY_ROW_DATA_KITTY_VIRTUAL_PLACEHOLDER = 7,
    GHOSTTY_ROW_DATA_DIRTY = 8,
}
unsafe extern "C" {
    pub fn ghostty_cell_get(
        cell: GhosttyCell,
        data: GhosttyCellData,
        out: *mut ::std::os::raw::c_void,
    ) -> GhosttyResult;
}
unsafe extern "C" {
    pub fn ghostty_row_get(
        row: GhosttyRow,
        data: GhosttyRowData,
        out: *mut ::std::os::raw::c_void,
    ) -> GhosttyResult;
}
pub type GhosttyStyleId = u16;
#[repr(u32)]
#[derive(Debug, Copy, Clone, Hash, PartialEq, Eq)]
pub enum GhosttyStyleColorTag {
    GHOSTTY_STYLE_COLOR_NONE = 0,
    GHOSTTY_STYLE_COLOR_PALETTE = 1,
    GHOSTTY_STYLE_COLOR_RGB = 2,
}
#[repr(C)]
#[derive(Copy, Clone)]
pub union GhosttyStyleColorValue {
    pub palette: GhosttyColorPaletteIndex,
    pub rgb: GhosttyColorRgb,
    pub _padding: u64,
}
#[repr(C)]
#[derive(Copy, Clone)]
pub struct GhosttyStyleColor {
    pub tag: GhosttyStyleColorTag,
    pub value: GhosttyStyleColorValue,
}
#[repr(C)]
#[derive(Copy, Clone)]
pub struct GhosttyStyle {
    pub size: usize,
    pub fg_color: GhosttyStyleColor,
    pub bg_color: GhosttyStyleColor,
    pub underline_color: GhosttyStyleColor,
    pub bold: bool,
    pub italic: bool,
    pub faint: bool,
    pub blink: bool,
    pub inverse: bool,
    pub invisible: bool,
    pub strikethrough: bool,
    pub overline: bool,
    pub underline: ::std::os::raw::c_int,
}
unsafe extern "C" {
    pub fn ghostty_style_default(style: *mut GhosttyStyle);
}
unsafe extern "C" {
    pub fn ghostty_style_is_default(style: *const GhosttyStyle) -> bool;
}
#[repr(C)]
#[derive(Debug, Copy, Clone)]
pub struct GhosttyGridRef {
    pub size: usize,
    pub node: *mut ::std::os::raw::c_void,
    pub x: u16,
    pub y: u16,
}
unsafe extern "C" {
    pub fn ghostty_grid_ref_cell(
        ref_: *const GhosttyGridRef,
        out_cell: *mut GhosttyCell,
    ) -> GhosttyResult;
}
unsafe extern "C" {
    pub fn ghostty_grid_ref_row(
        ref_: *const GhosttyGridRef,
        out_row: *mut GhosttyRow,
    ) -> GhosttyResult;
}
unsafe extern "C" {
    pub fn ghostty_grid_ref_graphemes(
        ref_: *const GhosttyGridRef,
        buf: *mut u32,
        buf_len: usize,
        out_len: *mut usize,
    ) -> GhosttyResult;
}
unsafe extern "C" {
    pub fn ghostty_grid_ref_style(
        ref_: *const GhosttyGridRef,
        out_style: *mut GhosttyStyle,
    ) -> GhosttyResult;
}
#[repr(C)]
#[derive(Debug, Copy, Clone)]
pub struct GhosttyPointCoordinate {
    pub x: u16,
    pub y: u32,
}
#[repr(u32)]
#[derive(Debug, Copy, Clone, Hash, PartialEq, Eq)]
pub enum GhosttyPointTag {
    GHOSTTY_POINT_TAG_ACTIVE = 0,
    GHOSTTY_POINT_TAG_VIEWPORT = 1,
    GHOSTTY_POINT_TAG_SCREEN = 2,
    GHOSTTY_POINT_TAG_HISTORY = 3,
}
#[repr(C)]
#[derive(Copy, Clone)]
pub union GhosttyPointValue {
    pub coordinate: GhosttyPointCoordinate,
    pub _padding: [u64; 2usize],
}
#[repr(C)]
#[derive(Copy, Clone)]
pub struct GhosttyPoint {
    pub tag: GhosttyPointTag,
    pub value: GhosttyPointValue,
}
#[repr(C)]
#[derive(Debug, Copy, Clone)]
pub struct GhosttyTerminal {
    _unused: [u8; 0],
}
pub type GhosttyTerminal_ptr = *mut GhosttyTerminal;
#[repr(C)]
#[derive(Debug, Copy, Clone)]
pub struct GhosttyTerminalOptions {
    pub cols: u16,
    pub rows: u16,
    pub max_scrollback: usize,
}
#[repr(u32)]
#[derive(Debug, Copy, Clone, Hash, PartialEq, Eq)]
pub enum GhosttyTerminalScrollViewportTag {
    GHOSTTY_SCROLL_VIEWPORT_TOP = 0,
    GHOSTTY_SCROLL_VIEWPORT_BOTTOM = 1,
    GHOSTTY_SCROLL_VIEWPORT_DELTA = 2,
}
#[repr(C)]
#[derive(Copy, Clone)]
pub union GhosttyTerminalScrollViewportValue {
    pub delta: isize,
    pub _padding: [u64; 2usize],
}
#[repr(C)]
#[derive(Copy, Clone)]
pub struct GhosttyTerminalScrollViewport {
    pub tag: GhosttyTerminalScrollViewportTag,
    pub value: GhosttyTerminalScrollViewportValue,
}
#[repr(u32)]
#[derive(Debug, Copy, Clone, Hash, PartialEq, Eq)]
pub enum GhosttyTerminalScreen {
    GHOSTTY_TERMINAL_SCREEN_PRIMARY = 0,
    GHOSTTY_TERMINAL_SCREEN_ALTERNATE = 1,
}
#[repr(C)]
#[derive(Debug, Copy, Clone)]
pub struct GhosttyTerminalScrollbar {
    pub total: u64,
    pub offset: u64,
    pub len: u64,
}
#[repr(u32)]
#[derive(Debug, Copy, Clone, Hash, PartialEq, Eq)]
pub enum GhosttyTerminalData {
    GHOSTTY_TERMINAL_DATA_INVALID = 0,
    GHOSTTY_TERMINAL_DATA_COLS = 1,
    GHOSTTY_TERMINAL_DATA_ROWS = 2,
    GHOSTTY_TERMINAL_DATA_CURSOR_X = 3,
    GHOSTTY_TERMINAL_DATA_CURSOR_Y = 4,
    GHOSTTY_TERMINAL_DATA_CURSOR_PENDING_WRAP = 5,
    GHOSTTY_TERMINAL_DATA_ACTIVE_SCREEN = 6,
    GHOSTTY_TERMINAL_DATA_CURSOR_VISIBLE = 7,
    GHOSTTY_TERMINAL_DATA_KITTY_KEYBOARD_FLAGS = 8,
    GHOSTTY_TERMINAL_DATA_SCROLLBAR = 9,
    GHOSTTY_TERMINAL_DATA_CURSOR_STYLE = 10,
    GHOSTTY_TERMINAL_DATA_MOUSE_TRACKING = 11,
}
unsafe extern "C" {
    pub fn ghostty_terminal_new(
        allocator: *const GhosttyAllocator,
        terminal: *mut GhosttyTerminal_ptr,
        options: GhosttyTerminalOptions,
    ) -> GhosttyResult;
}
unsafe extern "C" {
    pub fn ghostty_terminal_free(terminal: GhosttyTerminal_ptr);
}
unsafe extern "C" {
    pub fn ghostty_terminal_reset(terminal: GhosttyTerminal_ptr);
}
unsafe extern "C" {
    pub fn ghostty_terminal_resize(
        terminal: GhosttyTerminal_ptr,
        cols: u16,
        rows: u16,
    ) -> GhosttyResult;
}
unsafe extern "C" {
    pub fn ghostty_terminal_vt_write(terminal: GhosttyTerminal_ptr, data: *const u8, len: usize);
}
unsafe extern "C" {
    pub fn ghostty_terminal_scroll_viewport(
        terminal: GhosttyTerminal_ptr,
        behavior: GhosttyTerminalScrollViewport,
    );
}
unsafe extern "C" {
    pub fn ghostty_terminal_mode_get(
        terminal: GhosttyTerminal_ptr,
        mode: GhosttyMode,
        out_value: *mut bool,
    ) -> GhosttyResult;
}
unsafe extern "C" {
    pub fn ghostty_terminal_mode_set(
        terminal: GhosttyTerminal_ptr,
        mode: GhosttyMode,
        value: bool,
    ) -> GhosttyResult;
}
unsafe extern "C" {
    pub fn ghostty_terminal_get(
        terminal: GhosttyTerminal_ptr,
        data: GhosttyTerminalData,
        out: *mut ::std::os::raw::c_void,
    ) -> GhosttyResult;
}
unsafe extern "C" {
    pub fn ghostty_terminal_grid_ref(
        terminal: GhosttyTerminal_ptr,
        point: GhosttyPoint,
        out_ref: *mut GhosttyGridRef,
    ) -> GhosttyResult;
}
#[repr(u32)]
#[derive(Debug, Copy, Clone, Hash, PartialEq, Eq)]
pub enum GhosttyFormatterFormat {
    GHOSTTY_FORMATTER_FORMAT_PLAIN = 0,
    GHOSTTY_FORMATTER_FORMAT_VT = 1,
    GHOSTTY_FORMATTER_FORMAT_HTML = 2,
}
#[repr(C)]
#[derive(Debug, Copy, Clone)]
pub struct GhosttyFormatterScreenExtra {
    pub size: usize,
    pub cursor: bool,
    pub style: bool,
    pub hyperlink: bool,
    pub protection: bool,
    pub kitty_keyboard: bool,
    pub charsets: bool,
}
#[repr(C)]
#[derive(Debug, Copy, Clone)]
pub struct GhosttyFormatterTerminalExtra {
    pub size: usize,
    pub palette: bool,
    pub modes: bool,
    pub scrolling_region: bool,
    pub tabstops: bool,
    pub pwd: bool,
    pub keyboard: bool,
    pub screen: GhosttyFormatterScreenExtra,
}
#[repr(C)]
#[derive(Debug, Copy, Clone)]
pub struct GhosttyFormatter {
    _unused: [u8; 0],
}
pub type GhosttyFormatter_ptr = *mut GhosttyFormatter;
#[repr(C)]
#[derive(Debug, Copy, Clone)]
pub struct GhosttyFormatterTerminalOptions {
    pub size: usize,
    pub emit: GhosttyFormatterFormat,
    pub unwrap: bool,
    pub trim: bool,
    pub extra: GhosttyFormatterTerminalExtra,
}
unsafe extern "C" {
    pub fn ghostty_formatter_terminal_new(
        allocator: *const GhosttyAllocator,
        formatter: *mut GhosttyFormatter_ptr,
        terminal: GhosttyTerminal_ptr,
        options: GhosttyFormatterTerminalOptions,
    ) -> GhosttyResult;
}
unsafe extern "C" {
    pub fn ghostty_formatter_format_buf(
        formatter: GhosttyFormatter_ptr,
        buf: *mut u8,
        buf_len: usize,
        out_written: *mut usize,
    ) -> GhosttyResult;
}
unsafe extern "C" {
    pub fn ghostty_formatter_format_alloc(
        formatter: GhosttyFormatter_ptr,
        allocator: *const GhosttyAllocator,
        out_ptr: *mut *mut u8,
        out_len: *mut usize,
    ) -> GhosttyResult;
}
unsafe extern "C" {
    pub fn ghostty_formatter_free(formatter: GhosttyFormatter_ptr);
}
#[repr(C)]
#[derive(Debug, Copy, Clone)]
pub struct GhosttyRenderState {
    _unused: [u8; 0],
}
pub type GhosttyRenderState_ptr = *mut GhosttyRenderState;
#[repr(C)]
#[derive(Debug, Copy, Clone)]
pub struct GhosttyRenderStateRowIterator {
    _unused: [u8; 0],
}
pub type GhosttyRenderStateRowIterator_ptr = *mut GhosttyRenderStateRowIterator;
#[repr(C)]
#[derive(Debug, Copy, Clone)]
pub struct GhosttyRenderStateRowCells {
    _unused: [u8; 0],
}
pub type GhosttyRenderStateRowCells_ptr = *mut GhosttyRenderStateRowCells;
#[repr(u32)]
#[derive(Debug, Copy, Clone, Hash, PartialEq, Eq)]
pub enum GhosttyRenderStateDirty {
    GHOSTTY_RENDER_STATE_DIRTY_FALSE = 0,
    GHOSTTY_RENDER_STATE_DIRTY_PARTIAL = 1,
    GHOSTTY_RENDER_STATE_DIRTY_FULL = 2,
}
#[repr(u32)]
#[derive(Debug, Copy, Clone, Hash, PartialEq, Eq)]
pub enum GhosttyRenderStateCursorVisualStyle {
    GHOSTTY_RENDER_STATE_CURSOR_VISUAL_STYLE_BAR = 0,
    GHOSTTY_RENDER_STATE_CURSOR_VISUAL_STYLE_BLOCK = 1,
    GHOSTTY_RENDER_STATE_CURSOR_VISUAL_STYLE_UNDERLINE = 2,
    GHOSTTY_RENDER_STATE_CURSOR_VISUAL_STYLE_BLOCK_HOLLOW = 3,
}
#[repr(u32)]
#[derive(Debug, Copy, Clone, Hash, PartialEq, Eq)]
pub enum GhosttyRenderStateData {
    GHOSTTY_RENDER_STATE_DATA_INVALID = 0,
    GHOSTTY_RENDER_STATE_DATA_COLS = 1,
    GHOSTTY_RENDER_STATE_DATA_ROWS = 2,
    GHOSTTY_RENDER_STATE_DATA_DIRTY = 3,
    GHOSTTY_RENDER_STATE_DATA_ROW_ITERATOR = 4,
    GHOSTTY_RENDER_STATE_DATA_COLOR_BACKGROUND = 5,
    GHOSTTY_RENDER_STATE_DATA_COLOR_FOREGROUND = 6,
    GHOSTTY_RENDER_STATE_DATA_COLOR_CURSOR = 7,
    GHOSTTY_RENDER_STATE_DATA_COLOR_CURSOR_HAS_VALUE = 8,
    GHOSTTY_RENDER_STATE_DATA_COLOR_PALETTE = 9,
    GHOSTTY_RENDER_STATE_DATA_CURSOR_VISUAL_STYLE = 10,
    GHOSTTY_RENDER_STATE_DATA_CURSOR_VISIBLE = 11,
    GHOSTTY_RENDER_STATE_DATA_CURSOR_BLINKING = 12,
    GHOSTTY_RENDER_STATE_DATA_CURSOR_PASSWORD_INPUT = 13,
    GHOSTTY_RENDER_STATE_DATA_CURSOR_VIEWPORT_HAS_VALUE = 14,
    GHOSTTY_RENDER_STATE_DATA_CURSOR_VIEWPORT_X = 15,
    GHOSTTY_RENDER_STATE_DATA_CURSOR_VIEWPORT_Y = 16,
    GHOSTTY_RENDER_STATE_DATA_CURSOR_VIEWPORT_WIDE_TAIL = 17,
}
#[repr(u32)]
#[derive(Debug, Copy, Clone, Hash, PartialEq, Eq)]
pub enum GhosttyRenderStateOption {
    GHOSTTY_RENDER_STATE_OPTION_DIRTY = 0,
}
#[repr(u32)]
#[derive(Debug, Copy, Clone, Hash, PartialEq, Eq)]
pub enum GhosttyRenderStateRowData {
    GHOSTTY_RENDER_STATE_ROW_DATA_INVALID = 0,
    GHOSTTY_RENDER_STATE_ROW_DATA_DIRTY = 1,
    GHOSTTY_RENDER_STATE_ROW_DATA_RAW = 2,
    GHOSTTY_RENDER_STATE_ROW_DATA_CELLS = 3,
}
#[repr(u32)]
#[derive(Debug, Copy, Clone, Hash, PartialEq, Eq)]
pub enum GhosttyRenderStateRowOption {
    GHOSTTY_RENDER_STATE_ROW_OPTION_DIRTY = 0,
}
#[repr(C)]
#[derive(Debug, Copy, Clone)]
pub struct GhosttyRenderStateColors {
    pub size: usize,
    pub background: GhosttyColorRgb,
    pub foreground: GhosttyColorRgb,
    pub cursor: GhosttyColorRgb,
    pub cursor_has_value: bool,
    pub palette: [GhosttyColorRgb; 256usize],
}
unsafe extern "C" {
    pub fn ghostty_render_state_new(
        allocator: *const GhosttyAllocator,
        state: *mut GhosttyRenderState_ptr,
    ) -> GhosttyResult;
}
unsafe extern "C" {
    pub fn ghostty_render_state_free(state: GhosttyRenderState_ptr);
}
unsafe extern "C" {
    pub fn ghostty_render_state_update(
        state: GhosttyRenderState_ptr,
        terminal: GhosttyTerminal_ptr,
    ) -> GhosttyResult;
}
unsafe extern "C" {
    pub fn ghostty_render_state_get(
        state: GhosttyRenderState_ptr,
        data: GhosttyRenderStateData,
        out: *mut ::std::os::raw::c_void,
    ) -> GhosttyResult;
}
unsafe extern "C" {
    pub fn ghostty_render_state_set(
        state: GhosttyRenderState_ptr,
        option: GhosttyRenderStateOption,
        value: *const ::std::os::raw::c_void,
    ) -> GhosttyResult;
}
unsafe extern "C" {
    pub fn ghostty_render_state_colors_get(
        state: GhosttyRenderState_ptr,
        out_colors: *mut GhosttyRenderStateColors,
    ) -> GhosttyResult;
}
unsafe extern "C" {
    pub fn ghostty_render_state_row_iterator_new(
        allocator: *const GhosttyAllocator,
        out_iterator: *mut GhosttyRenderStateRowIterator_ptr,
    ) -> GhosttyResult;
}
unsafe extern "C" {
    pub fn ghostty_render_state_row_iterator_free(iterator: GhosttyRenderStateRowIterator_ptr);
}
unsafe extern "C" {
    pub fn ghostty_render_state_row_iterator_next(
        iterator: GhosttyRenderStateRowIterator_ptr,
    ) -> bool;
}
unsafe extern "C" {
    pub fn ghostty_render_state_row_get(
        iterator: GhosttyRenderStateRowIterator_ptr,
        data: GhosttyRenderStateRowData,
        out: *mut ::std::os::raw::c_void,
    ) -> GhosttyResult;
}
unsafe extern "C" {
    pub fn ghostty_render_state_row_set(
        iterator: GhosttyRenderStateRowIterator_ptr,
        option: GhosttyRenderStateRowOption,
        value: *const ::std::os::raw::c_void,
    ) -> GhosttyResult;
}
unsafe extern "C" {
    pub fn ghostty_render_state_row_cells_new(
        allocator: *const GhosttyAllocator,
        out_cells: *mut GhosttyRenderStateRowCells_ptr,
    ) -> GhosttyResult;
}
#[repr(u32)]
#[derive(Debug, Copy, Clone, Hash, PartialEq, Eq)]
pub enum GhosttyRenderStateRowCellsData {
    GHOSTTY_RENDER_STATE_ROW_CELLS_DATA_INVALID = 0,
    GHOSTTY_RENDER_STATE_ROW_CELLS_DATA_RAW = 1,
    GHOSTTY_RENDER_STATE_ROW_CELLS_DATA_STYLE = 2,
    GHOSTTY_RENDER_STATE_ROW_CELLS_DATA_GRAPHEMES_LEN = 3,
    GHOSTTY_RENDER_STATE_ROW_CELLS_DATA_GRAPHEMES_BUF = 4,
    GHOSTTY_RENDER_STATE_ROW_CELLS_DATA_BG_COLOR = 5,
    GHOSTTY_RENDER_STATE_ROW_CELLS_DATA_FG_COLOR = 6,
}
unsafe extern "C" {
    pub fn ghostty_render_state_row_cells_next(cells: GhosttyRenderStateRowCells_ptr) -> bool;
}
unsafe extern "C" {
    pub fn ghostty_render_state_row_cells_select(
        cells: GhosttyRenderStateRowCells_ptr,
        x: u16,
    ) -> GhosttyResult;
}
unsafe extern "C" {
    pub fn ghostty_render_state_row_cells_get(
        cells: GhosttyRenderStateRowCells_ptr,
        data: GhosttyRenderStateRowCellsData,
        out: *mut ::std::os::raw::c_void,
    ) -> GhosttyResult;
}
unsafe extern "C" {
    pub fn ghostty_render_state_row_cells_free(cells: GhosttyRenderStateRowCells_ptr);
}
#[repr(C)]
#[derive(Debug, Copy, Clone)]
pub struct GhosttyOscParser {
    _unused: [u8; 0],
}
pub type GhosttyOscParser_ptr = *mut GhosttyOscParser;
#[repr(C)]
#[derive(Debug, Copy, Clone)]
pub struct GhosttyOscCommand {
    _unused: [u8; 0],
}
pub type GhosttyOscCommand_ptr = *mut GhosttyOscCommand;
#[repr(u32)]
#[derive(Debug, Copy, Clone, Hash, PartialEq, Eq)]
pub enum GhosttyOscCommandType {
    GHOSTTY_OSC_COMMAND_INVALID = 0,
    GHOSTTY_OSC_COMMAND_CHANGE_WINDOW_TITLE = 1,
    GHOSTTY_OSC_COMMAND_CHANGE_WINDOW_ICON = 2,
    GHOSTTY_OSC_COMMAND_SEMANTIC_PROMPT = 3,
    GHOSTTY_OSC_COMMAND_CLIPBOARD_CONTENTS = 4,
    GHOSTTY_OSC_COMMAND_REPORT_PWD = 5,
    GHOSTTY_OSC_COMMAND_MOUSE_SHAPE = 6,
    GHOSTTY_OSC_COMMAND_COLOR_OPERATION = 7,
    GHOSTTY_OSC_COMMAND_KITTY_COLOR_PROTOCOL = 8,
    GHOSTTY_OSC_COMMAND_SHOW_DESKTOP_NOTIFICATION = 9,
    GHOSTTY_OSC_COMMAND_HYPERLINK_START = 10,
    GHOSTTY_OSC_COMMAND_HYPERLINK_END = 11,
    GHOSTTY_OSC_COMMAND_CONEMU_SLEEP = 12,
    GHOSTTY_OSC_COMMAND_CONEMU_SHOW_MESSAGE_BOX = 13,
    GHOSTTY_OSC_COMMAND_CONEMU_CHANGE_TAB_TITLE = 14,
    GHOSTTY_OSC_COMMAND_CONEMU_PROGRESS_REPORT = 15,
    GHOSTTY_OSC_COMMAND_CONEMU_WAIT_INPUT = 16,
    GHOSTTY_OSC_COMMAND_CONEMU_GUIMACRO = 17,
    GHOSTTY_OSC_COMMAND_CONEMU_RUN_PROCESS = 18,
    GHOSTTY_OSC_COMMAND_CONEMU_OUTPUT_ENVIRONMENT_VARIABLE = 19,
    GHOSTTY_OSC_COMMAND_CONEMU_XTERM_EMULATION = 20,
    GHOSTTY_OSC_COMMAND_CONEMU_COMMENT = 21,
    GHOSTTY_OSC_COMMAND_KITTY_TEXT_SIZING = 22,
}
#[repr(u32)]
#[derive(Debug, Copy, Clone, Hash, PartialEq, Eq)]
pub enum GhosttyOscCommandData {
    GHOSTTY_OSC_DATA_INVALID = 0,
    GHOSTTY_OSC_DATA_CHANGE_WINDOW_TITLE_STR = 1,
}
unsafe extern "C" {
    pub fn ghostty_osc_new(
        allocator: *const GhosttyAllocator,
        parser: *mut GhosttyOscParser_ptr,
    ) -> GhosttyResult;
}
unsafe extern "C" {
    pub fn ghostty_osc_free(parser: GhosttyOscParser_ptr);
}
unsafe extern "C" {
    pub fn ghostty_osc_reset(parser: GhosttyOscParser_ptr);
}
unsafe extern "C" {
    pub fn ghostty_osc_next(parser: GhosttyOscParser_ptr, byte: u8);
}
unsafe extern "C" {
    pub fn ghostty_osc_end(parser: GhosttyOscParser_ptr, terminator: u8) -> GhosttyOscCommand_ptr;
}
unsafe extern "C" {
    pub fn ghostty_osc_command_type(command: GhosttyOscCommand_ptr) -> GhosttyOscCommandType;
}
unsafe extern "C" {
    pub fn ghostty_osc_command_data(
        command: GhosttyOscCommand_ptr,
        data: GhosttyOscCommandData,
        out: *mut ::std::os::raw::c_void,
    ) -> bool;
}
#[repr(C)]
#[derive(Debug, Copy, Clone)]
pub struct GhosttySgrParser {
    _unused: [u8; 0],
}
pub type GhosttySgrParser_ptr = *mut GhosttySgrParser;
#[repr(u32)]
#[derive(Debug, Copy, Clone, Hash, PartialEq, Eq)]
pub enum GhosttySgrAttributeTag {
    GHOSTTY_SGR_ATTR_UNSET = 0,
    GHOSTTY_SGR_ATTR_UNKNOWN = 1,
    GHOSTTY_SGR_ATTR_BOLD = 2,
    GHOSTTY_SGR_ATTR_RESET_BOLD = 3,
    GHOSTTY_SGR_ATTR_ITALIC = 4,
    GHOSTTY_SGR_ATTR_RESET_ITALIC = 5,
    GHOSTTY_SGR_ATTR_FAINT = 6,
    GHOSTTY_SGR_ATTR_UNDERLINE = 7,
    GHOSTTY_SGR_ATTR_UNDERLINE_COLOR = 8,
    GHOSTTY_SGR_ATTR_UNDERLINE_COLOR_256 = 9,
    GHOSTTY_SGR_ATTR_RESET_UNDERLINE_COLOR = 10,
    GHOSTTY_SGR_ATTR_OVERLINE = 11,
    GHOSTTY_SGR_ATTR_RESET_OVERLINE = 12,
    GHOSTTY_SGR_ATTR_BLINK = 13,
    GHOSTTY_SGR_ATTR_RESET_BLINK = 14,
    GHOSTTY_SGR_ATTR_INVERSE = 15,
    GHOSTTY_SGR_ATTR_RESET_INVERSE = 16,
    GHOSTTY_SGR_ATTR_INVISIBLE = 17,
    GHOSTTY_SGR_ATTR_RESET_INVISIBLE = 18,
    GHOSTTY_SGR_ATTR_STRIKETHROUGH = 19,
    GHOSTTY_SGR_ATTR_RESET_STRIKETHROUGH = 20,
    GHOSTTY_SGR_ATTR_DIRECT_COLOR_FG = 21,
    GHOSTTY_SGR_ATTR_DIRECT_COLOR_BG = 22,
    GHOSTTY_SGR_ATTR_BG_8 = 23,
    GHOSTTY_SGR_ATTR_FG_8 = 24,
    GHOSTTY_SGR_ATTR_RESET_FG = 25,
    GHOSTTY_SGR_ATTR_RESET_BG = 26,
    GHOSTTY_SGR_ATTR_BRIGHT_BG_8 = 27,
    GHOSTTY_SGR_ATTR_BRIGHT_FG_8 = 28,
    GHOSTTY_SGR_ATTR_BG_256 = 29,
    GHOSTTY_SGR_ATTR_FG_256 = 30,
}
#[repr(u32)]
#[derive(Debug, Copy, Clone, Hash, PartialEq, Eq)]
pub enum GhosttySgrUnderline {
    GHOSTTY_SGR_UNDERLINE_NONE = 0,
    GHOSTTY_SGR_UNDERLINE_SINGLE = 1,
    GHOSTTY_SGR_UNDERLINE_DOUBLE = 2,
    GHOSTTY_SGR_UNDERLINE_CURLY = 3,
    GHOSTTY_SGR_UNDERLINE_DOTTED = 4,
    GHOSTTY_SGR_UNDERLINE_DASHED = 5,
}
#[repr(C)]
#[derive(Debug, Copy, Clone)]
pub struct GhosttySgrUnknown {
    pub full_ptr: *const u16,
    pub full_len: usize,
    pub partial_ptr: *const u16,
    pub partial_len: usize,
}
#[repr(C)]
#[derive(Copy, Clone)]
pub union GhosttySgrAttributeValue {
    pub unknown: GhosttySgrUnknown,
    pub underline: GhosttySgrUnderline,
    pub underline_color: GhosttyColorRgb,
    pub underline_color_256: GhosttyColorPaletteIndex,
    pub direct_color_fg: GhosttyColorRgb,
    pub direct_color_bg: GhosttyColorRgb,
    pub bg_8: GhosttyColorPaletteIndex,
    pub fg_8: GhosttyColorPaletteIndex,
    pub bright_bg_8: GhosttyColorPaletteIndex,
    pub bright_fg_8: GhosttyColorPaletteIndex,
    pub bg_256: GhosttyColorPaletteIndex,
    pub fg_256: GhosttyColorPaletteIndex,
    pub _padding: [u64; 8usize],
}
#[repr(C)]
#[derive(Copy, Clone)]
pub struct GhosttySgrAttribute {
    pub tag: GhosttySgrAttributeTag,
    pub value: GhosttySgrAttributeValue,
}
unsafe extern "C" {
    pub fn ghostty_sgr_new(
        allocator: *const GhosttyAllocator,
        parser: *mut GhosttySgrParser_ptr,
    ) -> GhosttyResult;
}
unsafe extern "C" {
    pub fn ghostty_sgr_free(parser: GhosttySgrParser_ptr);
}
unsafe extern "C" {
    pub fn ghostty_sgr_reset(parser: GhosttySgrParser_ptr);
}
unsafe extern "C" {
    pub fn ghostty_sgr_set_params(
        parser: GhosttySgrParser_ptr,
        params: *const u16,
        separators: *const ::std::os::raw::c_char,
        len: usize,
    ) -> GhosttyResult;
}
unsafe extern "C" {
    pub fn ghostty_sgr_next(parser: GhosttySgrParser_ptr, attr: *mut GhosttySgrAttribute) -> bool;
}
unsafe extern "C" {
    pub fn ghostty_sgr_unknown_full(unknown: GhosttySgrUnknown, ptr: *mut *const u16) -> usize;
}
unsafe extern "C" {
    pub fn ghostty_sgr_unknown_partial(unknown: GhosttySgrUnknown, ptr: *mut *const u16) -> usize;
}
unsafe extern "C" {
    pub fn ghostty_sgr_attribute_tag(attr: GhosttySgrAttribute) -> GhosttySgrAttributeTag;
}
unsafe extern "C" {
    pub fn ghostty_sgr_attribute_value(
        attr: *mut GhosttySgrAttribute,
    ) -> *mut GhosttySgrAttributeValue;
}
#[repr(C)]
#[derive(Debug, Copy, Clone)]
pub struct GhosttyKeyEvent {
    _unused: [u8; 0],
}
pub type GhosttyKeyEvent_ptr = *mut GhosttyKeyEvent;
#[repr(u32)]
#[derive(Debug, Copy, Clone, Hash, PartialEq, Eq)]
pub enum GhosttyKeyAction {
    GHOSTTY_KEY_ACTION_RELEASE = 0,
    GHOSTTY_KEY_ACTION_PRESS = 1,
    GHOSTTY_KEY_ACTION_REPEAT = 2,
}
pub type GhosttyMods = u16;
#[repr(u32)]
#[derive(Debug, Copy, Clone, Hash, PartialEq, Eq)]
pub enum GhosttyKey {
    GHOSTTY_KEY_UNIDENTIFIED = 0,
    GHOSTTY_KEY_BACKQUOTE = 1,
    GHOSTTY_KEY_BACKSLASH = 2,
    GHOSTTY_KEY_BRACKET_LEFT = 3,
    GHOSTTY_KEY_BRACKET_RIGHT = 4,
    GHOSTTY_KEY_COMMA = 5,
    GHOSTTY_KEY_DIGIT_0 = 6,
    GHOSTTY_KEY_DIGIT_1 = 7,
    GHOSTTY_KEY_DIGIT_2 = 8,
    GHOSTTY_KEY_DIGIT_3 = 9,
    GHOSTTY_KEY_DIGIT_4 = 10,
    GHOSTTY_KEY_DIGIT_5 = 11,
    GHOSTTY_KEY_DIGIT_6 = 12,
    GHOSTTY_KEY_DIGIT_7 = 13,
    GHOSTTY_KEY_DIGIT_8 = 14,
    GHOSTTY_KEY_DIGIT_9 = 15,
    GHOSTTY_KEY_EQUAL = 16,
    GHOSTTY_KEY_INTL_BACKSLASH = 17,
    GHOSTTY_KEY_INTL_RO = 18,
    GHOSTTY_KEY_INTL_YEN = 19,
    GHOSTTY_KEY_A = 20,
    GHOSTTY_KEY_B = 21,
    GHOSTTY_KEY_C = 22,
    GHOSTTY_KEY_D = 23,
    GHOSTTY_KEY_E = 24,
    GHOSTTY_KEY_F = 25,
    GHOSTTY_KEY_G = 26,
    GHOSTTY_KEY_H = 27,
    GHOSTTY_KEY_I = 28,
    GHOSTTY_KEY_J = 29,
    GHOSTTY_KEY_K = 30,
    GHOSTTY_KEY_L = 31,
    GHOSTTY_KEY_M = 32,
    GHOSTTY_KEY_N = 33,
    GHOSTTY_KEY_O = 34,
    GHOSTTY_KEY_P = 35,
    GHOSTTY_KEY_Q = 36,
    GHOSTTY_KEY_R = 37,
    GHOSTTY_KEY_S = 38,
    GHOSTTY_KEY_T = 39,
    GHOSTTY_KEY_U = 40,
    GHOSTTY_KEY_V = 41,
    GHOSTTY_KEY_W = 42,
    GHOSTTY_KEY_X = 43,
    GHOSTTY_KEY_Y = 44,
    GHOSTTY_KEY_Z = 45,
    GHOSTTY_KEY_MINUS = 46,
    GHOSTTY_KEY_PERIOD = 47,
    GHOSTTY_KEY_QUOTE = 48,
    GHOSTTY_KEY_SEMICOLON = 49,
    GHOSTTY_KEY_SLASH = 50,
    GHOSTTY_KEY_ALT_LEFT = 51,
    GHOSTTY_KEY_ALT_RIGHT = 52,
    GHOSTTY_KEY_BACKSPACE = 53,
    GHOSTTY_KEY_CAPS_LOCK = 54,
    GHOSTTY_KEY_CONTEXT_MENU = 55,
    GHOSTTY_KEY_CONTROL_LEFT = 56,
    GHOSTTY_KEY_CONTROL_RIGHT = 57,
    GHOSTTY_KEY_ENTER = 58,
    GHOSTTY_KEY_META_LEFT = 59,
    GHOSTTY_KEY_META_RIGHT = 60,
    GHOSTTY_KEY_SHIFT_LEFT = 61,
    GHOSTTY_KEY_SHIFT_RIGHT = 62,
    GHOSTTY_KEY_SPACE = 63,
    GHOSTTY_KEY_TAB = 64,
    GHOSTTY_KEY_CONVERT = 65,
    GHOSTTY_KEY_KANA_MODE = 66,
    GHOSTTY_KEY_NON_CONVERT = 67,
    GHOSTTY_KEY_DELETE = 68,
    GHOSTTY_KEY_END = 69,
    GHOSTTY_KEY_HELP = 70,
    GHOSTTY_KEY_HOME = 71,
    GHOSTTY_KEY_INSERT = 72,
    GHOSTTY_KEY_PAGE_DOWN = 73,
    GHOSTTY_KEY_PAGE_UP = 74,
    GHOSTTY_KEY_ARROW_DOWN = 75,
    GHOSTTY_KEY_ARROW_LEFT = 76,
    GHOSTTY_KEY_ARROW_RIGHT = 77,
    GHOSTTY_KEY_ARROW_UP = 78,
    GHOSTTY_KEY_NUM_LOCK = 79,
    GHOSTTY_KEY_NUMPAD_0 = 80,
    GHOSTTY_KEY_NUMPAD_1 = 81,
    GHOSTTY_KEY_NUMPAD_2 = 82,
    GHOSTTY_KEY_NUMPAD_3 = 83,
    GHOSTTY_KEY_NUMPAD_4 = 84,
    GHOSTTY_KEY_NUMPAD_5 = 85,
    GHOSTTY_KEY_NUMPAD_6 = 86,
    GHOSTTY_KEY_NUMPAD_7 = 87,
    GHOSTTY_KEY_NUMPAD_8 = 88,
    GHOSTTY_KEY_NUMPAD_9 = 89,
    GHOSTTY_KEY_NUMPAD_ADD = 90,
    GHOSTTY_KEY_NUMPAD_BACKSPACE = 91,
    GHOSTTY_KEY_NUMPAD_CLEAR = 92,
    GHOSTTY_KEY_NUMPAD_CLEAR_ENTRY = 93,
    GHOSTTY_KEY_NUMPAD_COMMA = 94,
    GHOSTTY_KEY_NUMPAD_DECIMAL = 95,
    GHOSTTY_KEY_NUMPAD_DIVIDE = 96,
    GHOSTTY_KEY_NUMPAD_ENTER = 97,
    GHOSTTY_KEY_NUMPAD_EQUAL = 98,
    GHOSTTY_KEY_NUMPAD_MEMORY_ADD = 99,
    GHOSTTY_KEY_NUMPAD_MEMORY_CLEAR = 100,
    GHOSTTY_KEY_NUMPAD_MEMORY_RECALL = 101,
    GHOSTTY_KEY_NUMPAD_MEMORY_STORE = 102,
    GHOSTTY_KEY_NUMPAD_MEMORY_SUBTRACT = 103,
    GHOSTTY_KEY_NUMPAD_MULTIPLY = 104,
    GHOSTTY_KEY_NUMPAD_PAREN_LEFT = 105,
    GHOSTTY_KEY_NUMPAD_PAREN_RIGHT = 106,
    GHOSTTY_KEY_NUMPAD_SUBTRACT = 107,
    GHOSTTY_KEY_NUMPAD_SEPARATOR = 108,
    GHOSTTY_KEY_NUMPAD_UP = 109,
    GHOSTTY_KEY_NUMPAD_DOWN = 110,
    GHOSTTY_KEY_NUMPAD_RIGHT = 111,
    GHOSTTY_KEY_NUMPAD_LEFT = 112,
    GHOSTTY_KEY_NUMPAD_BEGIN = 113,
    GHOSTTY_KEY_NUMPAD_HOME = 114,
    GHOSTTY_KEY_NUMPAD_END = 115,
    GHOSTTY_KEY_NUMPAD_INSERT = 116,
    GHOSTTY_KEY_NUMPAD_DELETE = 117,
    GHOSTTY_KEY_NUMPAD_PAGE_UP = 118,
    GHOSTTY_KEY_NUMPAD_PAGE_DOWN = 119,
    GHOSTTY_KEY_ESCAPE = 120,
    GHOSTTY_KEY_F1 = 121,
    GHOSTTY_KEY_F2 = 122,
    GHOSTTY_KEY_F3 = 123,
    GHOSTTY_KEY_F4 = 124,
    GHOSTTY_KEY_F5 = 125,
    GHOSTTY_KEY_F6 = 126,
    GHOSTTY_KEY_F7 = 127,
    GHOSTTY_KEY_F8 = 128,
    GHOSTTY_KEY_F9 = 129,
    GHOSTTY_KEY_F10 = 130,
    GHOSTTY_KEY_F11 = 131,
    GHOSTTY_KEY_F12 = 132,
    GHOSTTY_KEY_F13 = 133,
    GHOSTTY_KEY_F14 = 134,
    GHOSTTY_KEY_F15 = 135,
    GHOSTTY_KEY_F16 = 136,
    GHOSTTY_KEY_F17 = 137,
    GHOSTTY_KEY_F18 = 138,
    GHOSTTY_KEY_F19 = 139,
    GHOSTTY_KEY_F20 = 140,
    GHOSTTY_KEY_F21 = 141,
    GHOSTTY_KEY_F22 = 142,
    GHOSTTY_KEY_F23 = 143,
    GHOSTTY_KEY_F24 = 144,
    GHOSTTY_KEY_F25 = 145,
    GHOSTTY_KEY_FN = 146,
    GHOSTTY_KEY_FN_LOCK = 147,
    GHOSTTY_KEY_PRINT_SCREEN = 148,
    GHOSTTY_KEY_SCROLL_LOCK = 149,
    GHOSTTY_KEY_PAUSE = 150,
    GHOSTTY_KEY_BROWSER_BACK = 151,
    GHOSTTY_KEY_BROWSER_FAVORITES = 152,
    GHOSTTY_KEY_BROWSER_FORWARD = 153,
    GHOSTTY_KEY_BROWSER_HOME = 154,
    GHOSTTY_KEY_BROWSER_REFRESH = 155,
    GHOSTTY_KEY_BROWSER_SEARCH = 156,
    GHOSTTY_KEY_BROWSER_STOP = 157,
    GHOSTTY_KEY_EJECT = 158,
    GHOSTTY_KEY_LAUNCH_APP_1 = 159,
    GHOSTTY_KEY_LAUNCH_APP_2 = 160,
    GHOSTTY_KEY_LAUNCH_MAIL = 161,
    GHOSTTY_KEY_MEDIA_PLAY_PAUSE = 162,
    GHOSTTY_KEY_MEDIA_SELECT = 163,
    GHOSTTY_KEY_MEDIA_STOP = 164,
    GHOSTTY_KEY_MEDIA_TRACK_NEXT = 165,
    GHOSTTY_KEY_MEDIA_TRACK_PREVIOUS = 166,
    GHOSTTY_KEY_POWER = 167,
    GHOSTTY_KEY_SLEEP = 168,
    GHOSTTY_KEY_AUDIO_VOLUME_DOWN = 169,
    GHOSTTY_KEY_AUDIO_VOLUME_MUTE = 170,
    GHOSTTY_KEY_AUDIO_VOLUME_UP = 171,
    GHOSTTY_KEY_WAKE_UP = 172,
    GHOSTTY_KEY_COPY = 173,
    GHOSTTY_KEY_CUT = 174,
    GHOSTTY_KEY_PASTE = 175,
}
unsafe extern "C" {
    pub fn ghostty_key_event_new(
        allocator: *const GhosttyAllocator,
        event: *mut GhosttyKeyEvent_ptr,
    ) -> GhosttyResult;
}
unsafe extern "C" {
    pub fn ghostty_key_event_free(event: GhosttyKeyEvent_ptr);
}
unsafe extern "C" {
    pub fn ghostty_key_event_set_action(event: GhosttyKeyEvent_ptr, action: GhosttyKeyAction);
}
unsafe extern "C" {
    pub fn ghostty_key_event_get_action(event: GhosttyKeyEvent_ptr) -> GhosttyKeyAction;
}
unsafe extern "C" {
    pub fn ghostty_key_event_set_key(event: GhosttyKeyEvent_ptr, key: GhosttyKey);
}
unsafe extern "C" {
    pub fn ghostty_key_event_get_key(event: GhosttyKeyEvent_ptr) -> GhosttyKey;
}
unsafe extern "C" {
    pub fn ghostty_key_event_set_mods(event: GhosttyKeyEvent_ptr, mods: GhosttyMods);
}
unsafe extern "C" {
    pub fn ghostty_key_event_get_mods(event: GhosttyKeyEvent_ptr) -> GhosttyMods;
}
unsafe extern "C" {
    pub fn ghostty_key_event_set_consumed_mods(
        event: GhosttyKeyEvent_ptr,
        consumed_mods: GhosttyMods,
    );
}
unsafe extern "C" {
    pub fn ghostty_key_event_get_consumed_mods(event: GhosttyKeyEvent_ptr) -> GhosttyMods;
}
unsafe extern "C" {
    pub fn ghostty_key_event_set_composing(event: GhosttyKeyEvent_ptr, composing: bool);
}
unsafe extern "C" {
    pub fn ghostty_key_event_get_composing(event: GhosttyKeyEvent_ptr) -> bool;
}
unsafe extern "C" {
    pub fn ghostty_key_event_set_utf8(
        event: GhosttyKeyEvent_ptr,
        utf8: *const ::std::os::raw::c_char,
        len: usize,
    );
}
unsafe extern "C" {
    pub fn ghostty_key_event_get_utf8(
        event: GhosttyKeyEvent_ptr,
        len: *mut usize,
    ) -> *const ::std::os::raw::c_char;
}
unsafe extern "C" {
    pub fn ghostty_key_event_set_unshifted_codepoint(event: GhosttyKeyEvent_ptr, codepoint: u32);
}
unsafe extern "C" {
    pub fn ghostty_key_event_get_unshifted_codepoint(event: GhosttyKeyEvent_ptr) -> u32;
}
#[repr(C)]
#[derive(Debug, Copy, Clone)]
pub struct GhosttyKeyEncoder {
    _unused: [u8; 0],
}
pub type GhosttyKeyEncoder_ptr = *mut GhosttyKeyEncoder;
pub type GhosttyKittyKeyFlags = u8;
#[repr(u32)]
#[derive(Debug, Copy, Clone, Hash, PartialEq, Eq)]
pub enum GhosttyOptionAsAlt {
    GHOSTTY_OPTION_AS_ALT_FALSE = 0,
    GHOSTTY_OPTION_AS_ALT_TRUE = 1,
    GHOSTTY_OPTION_AS_ALT_LEFT = 2,
    GHOSTTY_OPTION_AS_ALT_RIGHT = 3,
}
#[repr(u32)]
#[derive(Debug, Copy, Clone, Hash, PartialEq, Eq)]
pub enum GhosttyKeyEncoderOption {
    GHOSTTY_KEY_ENCODER_OPT_CURSOR_KEY_APPLICATION = 0,
    GHOSTTY_KEY_ENCODER_OPT_KEYPAD_KEY_APPLICATION = 1,
    GHOSTTY_KEY_ENCODER_OPT_IGNORE_KEYPAD_WITH_NUMLOCK = 2,
    GHOSTTY_KEY_ENCODER_OPT_ALT_ESC_PREFIX = 3,
    GHOSTTY_KEY_ENCODER_OPT_MODIFY_OTHER_KEYS_STATE_2 = 4,
    GHOSTTY_KEY_ENCODER_OPT_KITTY_FLAGS = 5,
    GHOSTTY_KEY_ENCODER_OPT_MACOS_OPTION_AS_ALT = 6,
}
unsafe extern "C" {
    pub fn ghostty_key_encoder_new(
        allocator: *const GhosttyAllocator,
        encoder: *mut GhosttyKeyEncoder_ptr,
    ) -> GhosttyResult;
}
unsafe extern "C" {
    pub fn ghostty_key_encoder_free(encoder: GhosttyKeyEncoder_ptr);
}
unsafe extern "C" {
    pub fn ghostty_key_encoder_setopt(
        encoder: GhosttyKeyEncoder_ptr,
        option: GhosttyKeyEncoderOption,
        value: *const ::std::os::raw::c_void,
    );
}
unsafe extern "C" {
    pub fn ghostty_key_encoder_setopt_from_terminal(
        encoder: GhosttyKeyEncoder_ptr,
        terminal: GhosttyTerminal_ptr,
    );
}
unsafe extern "C" {
    pub fn ghostty_key_encoder_encode(
        encoder: GhosttyKeyEncoder_ptr,
        event: GhosttyKeyEvent_ptr,
        out_buf: *mut ::std::os::raw::c_char,
        out_buf_size: usize,
        out_len: *mut usize,
    ) -> GhosttyResult;
}
#[repr(C)]
#[derive(Debug, Copy, Clone)]
pub struct GhosttyMouseEvent {
    _unused: [u8; 0],
}
pub type GhosttyMouseEvent_ptr = *mut GhosttyMouseEvent;
#[repr(u32)]
#[derive(Debug, Copy, Clone, Hash, PartialEq, Eq)]
pub enum GhosttyMouseAction {
    GHOSTTY_MOUSE_ACTION_PRESS = 0,
    GHOSTTY_MOUSE_ACTION_RELEASE = 1,
    GHOSTTY_MOUSE_ACTION_MOTION = 2,
}
#[repr(u32)]
#[derive(Debug, Copy, Clone, Hash, PartialEq, Eq)]
pub enum GhosttyMouseButton {
    GHOSTTY_MOUSE_BUTTON_UNKNOWN = 0,
    GHOSTTY_MOUSE_BUTTON_LEFT = 1,
    GHOSTTY_MOUSE_BUTTON_RIGHT = 2,
    GHOSTTY_MOUSE_BUTTON_MIDDLE = 3,
    GHOSTTY_MOUSE_BUTTON_FOUR = 4,
    GHOSTTY_MOUSE_BUTTON_FIVE = 5,
    GHOSTTY_MOUSE_BUTTON_SIX = 6,
    GHOSTTY_MOUSE_BUTTON_SEVEN = 7,
    GHOSTTY_MOUSE_BUTTON_EIGHT = 8,
    GHOSTTY_MOUSE_BUTTON_NINE = 9,
    GHOSTTY_MOUSE_BUTTON_TEN = 10,
    GHOSTTY_MOUSE_BUTTON_ELEVEN = 11,
}
#[repr(C)]
#[derive(Debug, Copy, Clone)]
pub struct GhosttyMousePosition {
    pub x: f32,
    pub y: f32,
}
unsafe extern "C" {
    pub fn ghostty_mouse_event_new(
        allocator: *const GhosttyAllocator,
        event: *mut GhosttyMouseEvent_ptr,
    ) -> GhosttyResult;
}
unsafe extern "C" {
    pub fn ghostty_mouse_event_free(event: GhosttyMouseEvent_ptr);
}
unsafe extern "C" {
    pub fn ghostty_mouse_event_set_action(event: GhosttyMouseEvent_ptr, action: GhosttyMouseAction);
}
unsafe extern "C" {
    pub fn ghostty_mouse_event_get_action(event: GhosttyMouseEvent_ptr) -> GhosttyMouseAction;
}
unsafe extern "C" {
    pub fn ghostty_mouse_event_set_button(event: GhosttyMouseEvent_ptr, button: GhosttyMouseButton);
}
unsafe extern "C" {
    pub fn ghostty_mouse_event_clear_button(event: GhosttyMouseEvent_ptr);
}
unsafe extern "C" {
    pub fn ghostty_mouse_event_get_button(
        event: GhosttyMouseEvent_ptr,
        out_button: *mut GhosttyMouseButton,
    ) -> bool;
}
unsafe extern "C" {
    pub fn ghostty_mouse_event_set_mods(event: GhosttyMouseEvent_ptr, mods: GhosttyMods);
}
unsafe extern "C" {
    pub fn ghostty_mouse_event_get_mods(event: GhosttyMouseEvent_ptr) -> GhosttyMods;
}
unsafe extern "C" {
    pub fn ghostty_mouse_event_set_position(
        event: GhosttyMouseEvent_ptr,
        position: GhosttyMousePosition,
    );
}
unsafe extern "C" {
    pub fn ghostty_mouse_event_get_position(event: GhosttyMouseEvent_ptr) -> GhosttyMousePosition;
}
#[repr(C)]
#[derive(Debug, Copy, Clone)]
pub struct GhosttyMouseEncoder {
    _unused: [u8; 0],
}
pub type GhosttyMouseEncoder_ptr = *mut GhosttyMouseEncoder;
#[repr(u32)]
#[derive(Debug, Copy, Clone, Hash, PartialEq, Eq)]
pub enum GhosttyMouseTrackingMode {
    GHOSTTY_MOUSE_TRACKING_NONE = 0,
    GHOSTTY_MOUSE_TRACKING_X10 = 1,
    GHOSTTY_MOUSE_TRACKING_NORMAL = 2,
    GHOSTTY_MOUSE_TRACKING_BUTTON = 3,
    GHOSTTY_MOUSE_TRACKING_ANY = 4,
}
#[repr(u32)]
#[derive(Debug, Copy, Clone, Hash, PartialEq, Eq)]
pub enum GhosttyMouseFormat {
    GHOSTTY_MOUSE_FORMAT_X10 = 0,
    GHOSTTY_MOUSE_FORMAT_UTF8 = 1,
    GHOSTTY_MOUSE_FORMAT_SGR = 2,
    GHOSTTY_MOUSE_FORMAT_URXVT = 3,
    GHOSTTY_MOUSE_FORMAT_SGR_PIXELS = 4,
}
#[repr(C)]
#[derive(Debug, Copy, Clone)]
pub struct GhosttyMouseEncoderSize {
    pub size: usize,
    pub screen_width: u32,
    pub screen_height: u32,
    pub cell_width: u32,
    pub cell_height: u32,
    pub padding_top: u32,
    pub padding_bottom: u32,
    pub padding_right: u32,
    pub padding_left: u32,
}
#[repr(u32)]
#[derive(Debug, Copy, Clone, Hash, PartialEq, Eq)]
pub enum GhosttyMouseEncoderOption {
    GHOSTTY_MOUSE_ENCODER_OPT_EVENT = 0,
    GHOSTTY_MOUSE_ENCODER_OPT_FORMAT = 1,
    GHOSTTY_MOUSE_ENCODER_OPT_SIZE = 2,
    GHOSTTY_MOUSE_ENCODER_OPT_ANY_BUTTON_PRESSED = 3,
    GHOSTTY_MOUSE_ENCODER_OPT_TRACK_LAST_CELL = 4,
}
unsafe extern "C" {
    pub fn ghostty_mouse_encoder_new(
        allocator: *const GhosttyAllocator,
        encoder: *mut GhosttyMouseEncoder_ptr,
    ) -> GhosttyResult;
}
unsafe extern "C" {
    pub fn ghostty_mouse_encoder_free(encoder: GhosttyMouseEncoder_ptr);
}
unsafe extern "C" {
    pub fn ghostty_mouse_encoder_setopt(
        encoder: GhosttyMouseEncoder_ptr,
        option: GhosttyMouseEncoderOption,
        value: *const ::std::os::raw::c_void,
    );
}
unsafe extern "C" {
    pub fn ghostty_mouse_encoder_setopt_from_terminal(
        encoder: GhosttyMouseEncoder_ptr,
        terminal: GhosttyTerminal_ptr,
    );
}
unsafe extern "C" {
    pub fn ghostty_mouse_encoder_reset(encoder: GhosttyMouseEncoder_ptr);
}
unsafe extern "C" {
    pub fn ghostty_mouse_encoder_encode(
        encoder: GhosttyMouseEncoder_ptr,
        event: GhosttyMouseEvent_ptr,
        out_buf: *mut ::std::os::raw::c_char,
        out_buf_size: usize,
        out_len: *mut usize,
    ) -> GhosttyResult;
}
unsafe extern "C" {
    pub fn ghostty_paste_is_safe(data: *const ::std::os::raw::c_char, len: usize) -> bool;
}
#[repr(u32)]
#[derive(Debug, Copy, Clone, Hash, PartialEq, Eq)]
pub enum GhosttySizeReportStyle {
    GHOSTTY_SIZE_REPORT_MODE_2048 = 0,
    GHOSTTY_SIZE_REPORT_CSI_14_T = 1,
    GHOSTTY_SIZE_REPORT_CSI_16_T = 2,
    GHOSTTY_SIZE_REPORT_CSI_18_T = 3,
}
#[repr(C)]
#[derive(Debug, Copy, Clone)]
pub struct GhosttySizeReportSize {
    pub rows: u16,
    pub columns: u16,
    pub cell_width: u32,
    pub cell_height: u32,
}
unsafe extern "C" {
    pub fn ghostty_size_report_encode(
        style: GhosttySizeReportStyle,
        size: GhosttySizeReportSize,
        buf: *mut ::std::os::raw::c_char,
        buf_len: usize,
        out_written: *mut usize,
    ) -> GhosttyResult;
}
