"""Render a spinning ASCII globe as an animated SVG.

Pipeline: equirectangular earth texture -> land mask -> orthographic
projection per frame -> ASCII shading -> stacked SVG text frames
animated with CSS steps(). Land renders in the foreground color, ocean
in the muted color, matching the house README palette.
"""

from __future__ import annotations

import math
import sys
from pathlib import Path

import numpy as np
from PIL import Image

COLS = 64
ROWS = 32
FRAMES = 36
SECONDS = 9.0
TILT = math.radians(18.0)
RAMP = ":-=+*#%@"  # land, dark -> lit
LIGHT = (-0.45, 0.55, 0.75)
CW = 7.2  # char advance at font-size 12
RH = 14.4  # row height = 2 * CW so cells are square on screen
PAD = 10.0


def land_mask(path: str, width: int = 1440) -> np.ndarray:
    img = Image.open(path).convert("RGB")
    img = img.resize((width, width // 2), Image.BILINEAR)
    a = np.asarray(img).astype(np.int16)
    r, g, b = a[..., 0], a[..., 1], a[..., 2]
    return ~((b > r + 8) & (b > g + 8))  # ocean = blue-dominant


def cell(mask: np.ndarray, i: int, j: int, lon0: float,
         lit: tuple[float, float, float], ct: float, st: float) -> str:
    h, w = mask.shape
    hits = 0
    shade = 0.0
    on_sphere = 0
    for di, dj in ((0.25, 0.25), (0.25, 0.75), (0.75, 0.25), (0.75, 0.75)):
        x = 2.0 * (j + dj) / COLS - 1.0
        y = 2.0 * (i + di) / ROWS - 1.0
        rr = x * x + y * y
        if rr > 1.0:
            continue
        on_sphere += 1
        z = math.sqrt(1.0 - rr)
        y2 = y * ct - z * st
        z2 = y * st + z * ct
        lat = math.asin(max(-1.0, min(1.0, -y2)))
        lon = math.atan2(x, z2) + lon0
        u = int(((lon / (2 * math.pi) + 0.5) % 1.0) * w) % w
        v = int((0.5 - lat / math.pi) * (h - 1))
        if mask[v, u]:
            hits += 1
        shade += max(0.0, x * lit[0] + (-y) * lit[1] + z * lit[2])
    if on_sphere < 2:
        return " "
    shade /= on_sphere
    if hits * 2 > on_sphere:
        k = int((0.30 + 0.70 * shade ** 1.2) * (len(RAMP) - 1) + 0.5)
        return RAMP[min(len(RAMP) - 1, k)]
    return "."


def render_frame(mask: np.ndarray, lon0: float) -> list[str]:
    lx, ly, lz = LIGHT
    n = math.sqrt(lx * lx + ly * ly + lz * lz)
    lit = (lx / n, ly / n, lz / n)
    ct, st = math.cos(TILT), math.sin(TILT)
    return [
        "".join(cell(mask, i, j, lon0, lit, ct, st) for j in range(COLS))
        for i in range(ROWS)
    ]


def esc(s: str) -> str:
    return s.replace("&", "&amp;").replace("<", "&lt;").replace(">", "&gt;")


def layer_rows(rows: list[str], *, keep_land: bool) -> list[str]:
    """One SVG <text> per row, trimmed, width pinned with textLength."""
    out = []
    cls = "lnd" if keep_land else "sea"
    for i, row in enumerate(rows):
        s = "".join(
            c if (c not in " ." if keep_land else c == ".") else " "
            for c in row
        )
        core = s.rstrip()
        lead = len(core) - len(core.lstrip())
        core = core.lstrip()
        if not core:
            continue
        x = PAD + lead * CW
        y = PAD + i * RH + RH * 0.78
        out.append(
            f'<text class="{cls}" x="{x:.1f}" y="{y:.1f}" '
            f'textLength="{len(core) * CW:.1f}" xml:space="preserve">'
            f"{esc(core)}</text>"
        )
    return out


def main() -> None:
    mask = land_mask(sys.argv[1])
    wpx = PAD * 2 + COLS * CW
    hpx = PAD * 2 + ROWS * RH
    frames = []
    for f in range(FRAMES):
        rows = render_frame(mask, 2 * math.pi * f / FRAMES)
        body = "\n".join(
            layer_rows(rows, keep_land=False) + layer_rows(rows, keep_land=True)
        )
        frames.append(f'<g class="fr" id="f{f}">\n{body}\n</g>')
    slice_pct = 100.0 / FRAMES
    delays = "\n".join(
        f"    #f{k} {{ animation-delay: {(k / FRAMES - 1) * SECONDS:.4f}s; }}"
        for k in range(FRAMES)
    )
    svg = f"""<!-- generated by packages/readme-globe/render.py; regenerate: nix build .#readme-globe -->\n<svg xmlns="http://www.w3.org/2000/svg" viewBox="0 0 {wpx:.0f} {hpx:.0f}" role="img" aria-label="a spinning ascii globe: the whole world, rendered as text">
  <style>
    :root {{ --fg: #18181b; --muted: #8a8f98; }}
    @media (prefers-color-scheme: dark) {{
      :root {{ --fg: #e6e6e9; --muted: #7f838c; }}
    }}
    text {{ font-family: ui-monospace, "SF Mono", Menlo, Consolas, monospace; font-size: 12px; lengthAdjust: spacing; }}
    .lnd {{ fill: var(--fg); }}
    .sea {{ fill: var(--muted); opacity: 0.55; }}
    .fr {{ visibility: hidden; animation: cyc {SECONDS}s steps(1, end) infinite; }}
    @keyframes cyc {{
      0% {{ visibility: visible; }}
      {slice_pct:.4f}% {{ visibility: hidden; }}
    }}
{delays}
    @media (prefers-reduced-motion: reduce) {{
      .fr {{ animation: none; }}
      #f0 {{ visibility: visible; }}
    }}
  </style>
{chr(10).join(frames)}
</svg>
"""
    Path(sys.argv[2]).write_text(svg)
    print(f"{len(svg)} bytes, {FRAMES} frames")


if __name__ == "__main__":
    main()
