name: Publish CI budget

on:
  pull_request_target:
    types: [opened, synchronize, reopened, labeled, unlabeled]

permissions:
  contents: read

jobs:
  publish:
    permissions:
      actions: read
      contents: read
      issues: write
      pull-requests: write
    uses: indexable-inc/index/.github/workflows/ci-budget.yml@main
    with:
      pull-request-number: ${{ github.event.pull_request.number }}
