//! Assemble the generated Java class: one `public final class` per
//! interface carrying the public methods, the nested records and exception
//! hierarchy, and the private FFM plumbing.

mod api;
mod data;
mod java;
mod plumbing;

use std::fmt::Write as _;

use unibind_core::ir;

use crate::{module, names, RenderError};

/// One generated Java source file.
pub struct HostClass {
    /// The simple name of the generated class.
    pub class_name: String,
    /// `<ClassName>.java`, the file name javac requires.
    pub file_name: String,
    /// The complete source text.
    pub source: String,
}

/// Render the Java class for one interface, optionally inside `package`.
///
/// # Errors
///
/// Fails for everything [`crate::render`] fails for — the glue pass runs
/// first as the shared validator — plus a class name Java cannot declare.
pub fn host_class(
    interface: &ir::Interface,
    package: Option<&str>,
) -> Result<HostClass, RenderError> {
    // The glue pass validates the surface both halves depend on.
    module::render(interface)?;
    let class_name = names::checked(
        names::class_name(interface),
        &format!("module `{}`", interface.name),
    )?;

    let uses = Uses::scan(interface);
    let api = api::render(interface)?;
    let data = data::render(interface)?;
    let plumbing = plumbing::render(interface, &uses);

    let mut source = String::from("// Generated by unibind; do not edit.\n");
    if let Some(package) = package {
        let _ = writeln!(source, "package {package};");
    }
    source.push('\n');
    for import in imports(&uses) {
        let _ = writeln!(source, "import {import};");
    }
    source.push('\n');
    source.push_str(&class_javadoc(interface));
    let _ = writeln!(source, "public final class {class_name} {{");
    let _ = writeln!(source, "    private {class_name}() {{}}");
    source.push('\n');
    source.push_str(&java::indent(&api, 1));
    source.push_str("\n\n");
    source.push_str(&java::indent(&data, 1));
    source.push_str("\n\n");
    source.push_str(&java::indent(&plumbing, 1));
    source.push_str("\n}\n");

    Ok(HostClass {
        file_name: format!("{class_name}.java"),
        class_name,
        source,
    })
}

/// The imports the generated class needs, sorted the way javac tools like
/// them; the fixed FFM set plus whatever the surface's types pull in.
fn imports(uses: &Uses) -> Vec<&'static str> {
    let mut imports = vec![
        "java.lang.foreign.Arena",
        "java.lang.foreign.FunctionDescriptor",
        "java.lang.foreign.Linker",
        "java.lang.foreign.MemorySegment",
        "java.lang.foreign.SymbolLookup",
        "java.lang.foreign.ValueLayout",
        "java.lang.invoke.MethodHandle",
        "java.nio.charset.StandardCharsets",
        "java.util.Arrays",
    ];
    if uses.io_exception {
        imports.push("java.io.IOException");
    }
    if uses.path {
        imports.push("java.nio.file.Path");
    }
    if uses.vec {
        imports.push("java.util.ArrayList");
        imports.push("java.util.List");
    }
    if uses.map {
        imports.push("java.util.HashMap");
        imports.push("java.util.Map");
    }
    if uses.vec || uses.map {
        imports.push("java.util.function.BiConsumer");
        imports.push("java.util.function.Function");
    }
    imports.sort_unstable();
    imports
}

/// The class javadoc: the module's doc comment plus the fixed notes about
/// the wire, library resolution, and native access.
fn class_javadoc(interface: &ir::Interface) -> String {
    let key = names::library_key(interface);
    let mut lines: Vec<String> = interface
        .docs
        .iter()
        .map(|line| java::javadoc_escape(line.trim()))
        .collect();
    if !lines.is_empty() {
        lines.push(String::new());
    }
    lines.push(format!(
        "<p>Generated by unibind from the Rust module {}. Values cross a",
        java::code(&interface.name),
    ));
    lines.push(
        "C ABI in unibind's length-prefixed little-endian wire format; unsigned Rust".to_owned(),
    );
    lines.push("integers reinterpret as the signed Java type of the same width.".to_owned());
    lines.push(String::new());
    lines.push(format!(
        "<p>The native library resolves through the {} system",
        java::code(&format!("unibind.library.{key}")),
    ));
    lines.push(format!(
        "property (an explicit path) when set, else through {}",
        java::code(&format!("System.mapLibraryName(\"{key}\")")),
    ));
    lines.push("on the library search path. The JVM needs".to_owned());
    lines.push(format!(
        "{} to bind the symbols.",
        java::code("--enable-native-access=ALL-UNNAMED"),
    ));
    java::javadoc(&lines)
}

/// Which optional imports and plumbing helpers the surface's types pull in.
// Four independent yes/no facts about the surface, not a state machine.
#[allow(clippy::struct_excessive_bools)]
pub struct Uses {
    /// Any `Vec<T>`: the `List` types and the list codec helpers.
    pub vec: bool,
    /// Any `HashMap<K, V>`: the `Map` types and the map codec helpers.
    pub map: bool,
    /// Any path: `java.nio.file.Path`.
    pub path: bool,
    /// Any `jvm(base = "IOException")` error: `java.io.IOException`.
    pub io_exception: bool,
}

impl Uses {
    fn scan(interface: &ir::Interface) -> Self {
        let mut uses = Self {
            vec: false,
            map: false,
            path: false,
            io_exception: interface
                .errors
                .iter()
                .any(|error| error.jvm_base.as_deref() == Some("IOException")),
        };
        for function in &interface.functions {
            for arg in &function.args {
                uses.ty(&arg.ty);
            }
            if let Some(ret) = &function.ret {
                uses.ty(ret);
            }
        }
        for record in &interface.records {
            for field in &record.fields {
                uses.ty(&field.ty);
            }
        }
        uses
    }

    fn ty(&mut self, ty: &ir::Type) {
        match ty {
            ir::Type::Vec(inner) => {
                self.vec = true;
                self.ty(inner);
            }
            ir::Type::Map { key, value } => {
                self.map = true;
                self.ty(key);
                self.ty(value);
            }
            ir::Type::Option(inner) => self.ty(inner),
            ir::Type::Path { .. } => self.path = true,
            ir::Type::Bool
            | ir::Type::Int(_)
            | ir::Type::Float(_)
            | ir::Type::String { .. }
            | ir::Type::Bytes { .. }
            | ir::Type::Named(_)
            | ir::Type::Stream(_) => {}
        }
    }
}
